using System.Collections;
using CosmicBlock.Core;
using UnityEngine;
using UnityEngine.UI;
namespace CosmicBlock.UI {
 public sealed class PlanetRestorationView:MonoBehaviour {
  [SerializeField] Image currentImage,nextImage,progressFill; [SerializeField] Text titleText,percentText,energyText,awardText,completionText; [SerializeField] CanvasGroup awardGroup,completionGroup; [SerializeField] RectTransform planetRoot; [SerializeField] Image[] sparks; [SerializeField] Sprite[] stages;
  Coroutine transitionRoutine,feedbackRoutine,completionRoutine; int shownStage;
  public int ShownStage=>shownStage; public bool TransitionActive=>transitionRoutine!=null; public bool FeedbackActive=>feedbackRoutine!=null||(awardGroup!=null&&awardGroup.gameObject.activeSelf); public bool CompletionActive=>completionRoutine!=null||(completionGroup!=null&&completionGroup.gameObject.activeSelf);
  public void Configure(Image current,Image next,Image fill,Text title,Text percent,Text energy,Text award,CanvasGroup awardCanvas,Text completion,CanvasGroup completionCanvas,RectTransform root,Image[] sparkPool,Sprite[] stageSprites){currentImage=current;nextImage=next;progressFill=fill;titleText=title;percentText=percent;energyText=energy;awardText=award;awardGroup=awardCanvas;completionText=completion;completionGroup=completionCanvas;planetRoot=root;sparks=sparkPool;stages=stageSprites;}
  public void Render(PlanetRestoration model,bool animate){int stage=model.Stage;titleText.text=model.IsRestored?"PLANET 01  ·  RESTORED":"PLANET 01";percentText.text=model.Percent+"%";energyText.text=model.CurrentEnergy+" / "+PlanetRestoration.RequiredEnergy+" ENERGY";progressFill.fillAmount=model.CurrentEnergy/(float)PlanetRestoration.RequiredEnergy;if(shownStage==0||!animate||stage==shownStage){shownStage=stage;currentImage.sprite=stages[stage-1];currentImage.color=Color.white;nextImage.gameObject.SetActive(false);return;}if(transitionRoutine!=null)StopCoroutine(transitionRoutine);transitionRoutine=StartCoroutine(CrossFade(stage));}
  IEnumerator CrossFade(int stage){nextImage.sprite=stages[stage-1];nextImage.color=new Color(1,1,1,0);nextImage.gameObject.SetActive(true);for(float t=0;t<.65f;t+=Time.unscaledDeltaTime){float p=t/.65f;nextImage.color=new Color(1,1,1,p);currentImage.color=new Color(1,1,1,1-p*.55f);yield return null;}shownStage=stage;currentImage.sprite=nextImage.sprite;currentImage.color=Color.white;nextImage.gameObject.SetActive(false);transitionRoutine=null;}
  public void PlayAward(int amount,bool completed){if(amount<=0)return;if(feedbackRoutine!=null)StopCoroutine(feedbackRoutine);feedbackRoutine=StartCoroutine(EnergyFeedback(amount));if(completed&&!CompletionActive)completionRoutine=StartCoroutine(Completion());}
  IEnumerator EnergyFeedback(int amount){awardText.text="+"+amount+" ENERGY";awardGroup.alpha=1;awardGroup.gameObject.SetActive(true);for(int i=0;i<sparks.Length;i++){var s=sparks[i];s.gameObject.SetActive(true);s.color=new Color(i%2==0?1f:.45f,i%2==0?.78f:.8f,1f,1f);s.rectTransform.anchoredPosition=new Vector2((i-2.5f)*18,-105-(i%2)*12);}for(float t=0;t<.55f;t+=Time.unscaledDeltaTime){float p=t/.55f;foreach(var s in sparks)s.rectTransform.anchoredPosition=Vector2.Lerp(s.rectTransform.anchoredPosition,Vector2.zero,p*.16f);planetRoot.localScale=Vector3.one*Mathf.Lerp(1,1.06f,Mathf.Sin(p*Mathf.PI));yield return null;}foreach(var s in sparks)s.gameObject.SetActive(false);planetRoot.localScale=Vector3.one;yield return new WaitForSecondsRealtime(.25f);awardGroup.alpha=0;awardGroup.gameObject.SetActive(false);feedbackRoutine=null;}
  IEnumerator Completion(){completionText.text="PLANET RESTORED!\nNEXT WORLD AWAITS...";completionGroup.alpha=0;completionGroup.gameObject.SetActive(true);for(float t=0;t<.35f;t+=Time.unscaledDeltaTime){completionGroup.alpha=t/.35f;yield return null;}yield return new WaitForSecondsRealtime(1.35f);for(float t=0;t<.35f;t+=Time.unscaledDeltaTime){completionGroup.alpha=1-t/.35f;yield return null;}completionGroup.alpha=0;completionGroup.gameObject.SetActive(false);completionRoutine=null;}
  public void ResetTransient(){if(transitionRoutine!=null)StopCoroutine(transitionRoutine);if(feedbackRoutine!=null)StopCoroutine(feedbackRoutine);if(completionRoutine!=null)StopCoroutine(completionRoutine);transitionRoutine=feedbackRoutine=completionRoutine=null;if(nextImage!=null)nextImage.gameObject.SetActive(false);if(awardGroup!=null){awardGroup.alpha=0;awardGroup.gameObject.SetActive(false);}if(completionGroup!=null){completionGroup.alpha=0;completionGroup.gameObject.SetActive(false);}if(sparks!=null)foreach(var s in sparks)if(s!=null)s.gameObject.SetActive(false);if(planetRoot!=null)planetRoot.localScale=Vector3.one;}
 }
}