using System;
using System.Collections;
using CosmicBlock.Board;
using CosmicBlock.Core;
using UnityEngine;
using UnityEngine.UI;
namespace CosmicBlock.UI {
 public sealed class PlanetRestorationView:MonoBehaviour {
  [SerializeField] Image currentImage,nextImage,progressFill;[SerializeField] Text titleText,percentText,energyText,awardText,completionText;[SerializeField] CanvasGroup awardGroup,completionGroup;[SerializeField] RectTransform planetRoot,fragmentRoot;[SerializeField] Image[] sparks,fragments,centralImages;[SerializeField] Sprite[] stages;
  bool holdEnergy;Coroutine presentationRoutine;Action pendingComplete;int shownStage,presentedEnergy,completionPlayCount;Vector2[] fragmentStarts;
  public int ShownStage=>shownStage;public int PresentedEnergy=>presentedEnergy;public bool TransitionActive=>presentationRoutine!=null&&completionGroup.gameObject.activeSelf;public bool FeedbackActive=>presentationRoutine!=null||(awardGroup!=null&&awardGroup.gameObject.activeSelf);public bool CompletionActive=>completionGroup!=null&&completionGroup.gameObject.activeSelf;public int ActiveFragmentCount=>CountActive(fragments);public int FragmentPoolCapacity=>fragments==null?0:fragments.Length;public int CompletionPlayCount=>completionPlayCount;public float ProgressFill=>progressFill==null?0:progressFill.rectTransform.anchorMax.x;public float ImageFillAmount=>progressFill==null?0:progressFill.fillAmount;public Vector2[] LastFragmentStarts=>fragmentStarts;
  public void Configure(Image current,Image next,Image fill,Text title,Text percent,Text energy,Text award,CanvasGroup awardCanvas,Text completion,CanvasGroup completionCanvas,RectTransform root,Image[] sparkPool,Sprite[] stageSprites,RectTransform flightRoot,Image[] fragmentPool,Image[] centerPool){currentImage=current;nextImage=next;progressFill=fill;titleText=title;percentText=percent;energyText=energy;awardText=award;awardGroup=awardCanvas;completionText=completion;completionGroup=completionCanvas;planetRoot=root;sparks=sparkPool;stages=stageSprites;fragmentRoot=flightRoot;fragments=fragmentPool;centralImages=centerPool;}
  public void Render(PlanetRestoration model,bool animate){if(presentationRoutine==null&&!holdEnergy)RenderEnergy(model.CurrentEnergy,animate);}
  public void HoldEnergy(int total){holdEnergy=true;RenderEnergy(total,false);}
  public void RenderEnergy(int total,bool animate){total=Mathf.Clamp(total,0,PlanetRestoration.RequiredEnergy);RenderStage(PlanetRestoration.StageForEnergy(total),PlanetRestoration.StageEnergyForTotal(total),total);currentImage.color=Color.white;nextImage.gameObject.SetActive(false);}
  public bool PresentClear(LineClearResult clear,BoardView board,int before,int after,Action complete){if(clear==null||clear.LineCount==0||after<=before||before>=PlanetRestoration.RequiredEnergy){complete?.Invoke();return false;}ResetTransient();pendingComplete=complete;presentationRoutine=StartCoroutine(Present(clear,board,before,after,complete));return true;}
  IEnumerator Present(LineClearResult clear,BoardView board,int before,int after,Action complete){RenderEnergy(before,false);int count=Mathf.Clamp(6+(clear.LineCount-1)*2,6,12);fragmentStarts=new Vector2[count];Vector2 target=fragmentRoot.InverseTransformPoint(planetRoot.TransformPoint(Vector3.zero));for(int i=0;i<count;i++){var f=fragments[i];int cellIndex=Mathf.Min(clear.UniqueClearedCells.Count-1,i*clear.UniqueClearedCells.Count/count);Vector2 start=fragmentRoot.InverseTransformPoint(board.GetCellWorld(clear.UniqueClearedCells[cellIndex]));fragmentStarts[i]=start;f.rectTransform.anchoredPosition=start;f.rectTransform.sizeDelta=Vector2.one*140;f.color=i%2==0?new Color(1,.78f,.28f,1):new Color(.45f,.82f,1,1);f.gameObject.SetActive(true);}float duration=.72f,stagger=.022f,total=duration+stagger*(count-1);for(float t=0;t<total;t+=Time.unscaledDeltaTime){for(int i=0;i<count;i++){float p=Mathf.Clamp01((t-i*stagger)/duration);Vector2 a=fragmentStarts[i],control=(a+target)*.5f+Vector2.up*(55+i%3*18);fragments[i].rectTransform.anchoredPosition=Bezier(a,control,target,Smooth(p));SetAlpha(fragments[i],1-Mathf.Clamp01((p-.78f)/.22f));}yield return null;}foreach(var f in fragments)f.gameObject.SetActive(false);awardText.text="별빛 +"+(after-before);awardGroup.alpha=1;awardGroup.gameObject.SetActive(true);for(float t=0;t<.25f;t+=Time.unscaledDeltaTime){planetRoot.localScale=Vector3.one*Mathf.Lerp(1,1.07f,Mathf.Sin(t/.25f*Mathf.PI));yield return null;}planetRoot.localScale=Vector3.one;int cursor=before;while(cursor<after){int stage=PlanetRestoration.StageForEnergy(cursor);int stageEnd=PlanetRestoration.StartForStage(stage)+PlanetRestoration.RequiredForStage(stage);int end=Mathf.Min(after,stageEnd);bool crosses=end==stageEnd;yield return AnimateEnergy(cursor,end,.30f,crosses);cursor=end;if(crosses&&stage<5){yield return StageTransition(stage,stage+1);RenderEnergy(cursor,false);}else if(cursor==PlanetRestoration.RequiredEnergy){yield return StageTransition(5,5);RenderEnergy(cursor,false);}}yield return new WaitForSecondsRealtime(.18f);awardGroup.alpha=0;awardGroup.gameObject.SetActive(false);presentationRoutine=null;holdEnergy=false;var done=pendingComplete;pendingComplete=null;done?.Invoke();}
  IEnumerator AnimateEnergy(int from,int to,float duration,bool boundary){int stage=PlanetRestoration.StageForEnergy(from);for(float t=0;t<duration;t+=Time.unscaledDeltaTime){int total=Mathf.RoundToInt(Mathf.Lerp(from,to,t/duration));RenderStage(stage,total-PlanetRestoration.StartForStage(stage),total);yield return null;}if(boundary)RenderStage(stage,PlanetRestoration.RequiredForStage(stage),to);else RenderEnergy(to,false);}
  void RenderStage(int stage,int energy,int total){presentedEnergy=total;titleText.text="행성 01 · "+PlanetRestoration.Planet01DisplayName;percentText.text=total>=PlanetRestoration.RequiredEnergy?"5단계 · 완성 ✓":stage+"단계 · "+PlanetRestoration.NameForStage(stage);energyText.text="별빛 "+energy+" / "+PlanetRestoration.RequiredForStage(stage);SetProgress(PlanetRestoration.OverallProgressForTotal(total));shownStage=stage;currentImage.sprite=stages[stage-1];}
  void SetProgress(float value){value=Mathf.Clamp01(value);progressFill.fillAmount=value;var r=progressFill.rectTransform;r.anchorMin=Vector2.zero;r.anchorMax=new Vector2(value,1);r.offsetMin=r.offsetMax=Vector2.zero;}
  IEnumerator StageTransition(int fromStage,int toStage){completionPlayCount++;completionText.text=fromStage==5&&toStage==5?PlanetRestoration.Planet01DisplayName+" 복원 완료\n새로운 세계가 기다립니다":"행성 각성\n복원 단계 "+toStage+" / 5";completionGroup.alpha=0;completionGroup.gameObject.SetActive(true);centralImages[0].sprite=stages[fromStage-1];centralImages[1].sprite=stages[toStage-1];centralImages[0].color=Color.white;centralImages[1].color=new Color(1,1,1,0);for(float t=0;t<.25f;t+=Time.unscaledDeltaTime){completionGroup.alpha=t/.25f;centralImages[0].rectTransform.localScale=Vector3.one*Mathf.Lerp(.92f,1,t/.25f);yield return null;}for(float t=0;t<.45f;t+=Time.unscaledDeltaTime){float p=t/.45f;centralImages[0].rectTransform.localScale=Vector3.one*Mathf.Lerp(1,1.05f,p);yield return null;}for(float t=0;t<.45f;t+=Time.unscaledDeltaTime){float p=t/.45f;centralImages[0].color=new Color(1,1,1,1-p);centralImages[1].color=new Color(1,1,1,p);yield return null;}yield return new WaitForSecondsRealtime(.35f);for(float t=0;t<.3f;t+=Time.unscaledDeltaTime){completionGroup.alpha=1-t/.3f;yield return null;}completionGroup.alpha=0;completionGroup.gameObject.SetActive(false);centralImages[0].rectTransform.localScale=Vector3.one;shownStage=toStage;}
  public void ResetTransient(){var done=pendingComplete;pendingComplete=null;if(presentationRoutine!=null)StopCoroutine(presentationRoutine);presentationRoutine=null;holdEnergy=false;if(nextImage!=null)nextImage.gameObject.SetActive(false);if(awardGroup!=null){awardGroup.alpha=0;awardGroup.gameObject.SetActive(false);}if(completionGroup!=null){completionGroup.alpha=0;completionGroup.gameObject.SetActive(false);}Hide(sparks);Hide(fragments);if(planetRoot!=null)planetRoot.localScale=Vector3.one;if(centralImages!=null)foreach(var i in centralImages)if(i!=null){i.color=Color.white;i.rectTransform.localScale=Vector3.one;}done?.Invoke();}
  static Vector2 Bezier(Vector2 a,Vector2 b,Vector2 c,float t){float u=1-t;return u*u*a+2*u*t*b+t*t*c;}static float Smooth(float p)=>p*p*(3-2*p);static void SetAlpha(Graphic g,float a){var c=g.color;c.a=a;g.color=c;}static int CountActive(Image[] pool){int n=0;if(pool!=null)foreach(var i in pool)if(i!=null&&i.gameObject.activeSelf)n++;return n;}static void Hide(Image[] pool){if(pool!=null)foreach(var i in pool)if(i!=null)i.gameObject.SetActive(false);}
 }
}
