using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using CosmicBlock.Core;
using CosmicBlock.Board;
using CosmicBlock.Blocks;
using CosmicBlock.UI;
using CosmicBlock.Effects;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Polish001PlayProbe {
 static Dictionary<string,int> saved=new Dictionary<string,int>();static List<string> keys=new List<string>(),results=new List<string>();static GameSession game;static GameFlowController flow;static BoardView board;static GameFeedbackController feedback;static double began;static int frames;static string errors="";
 public static void Run(){keys.Add(PlanetSelection.Key);keys.Add(PlanetRestoration.VersionKey);keys.Add(GameSession.DefaultBestScoreKey);foreach(var d in PlanetDefinitions.All){keys.Add(d.EnergyKey);keys.Add(d.UnlockKey);keys.Add(PlanetCompletionNotice.Key(d.Id));}foreach(var k in keys){if(PlayerPrefs.HasKey(k))saved[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.SetInt(GameSession.DefaultBestScoreKey,19000);foreach(var d in PlanetDefinitions.All)PlayerPrefs.SetInt(d.UnlockKey,1);PlayerPrefs.Save();EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");began=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Log(string m,string s,LogType t){if(t==LogType.Warning||t==LogType.Error||t==LogType.Exception)errors+=m+"\n";}
 static void Check(){if(EditorApplication.timeSinceStartup-began>240){Finish(false,"시간 초과");return;}if(!EditorApplication.isPlaying||++frames<35)return;EditorApplication.update-=Check;game=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();board=UnityEngine.Object.FindAnyObjectByType<BoardView>();feedback=game.Feedback;RunSaveStore.Delete();game.StartCoroutine(Guard());}
 static IEnumerator Guard(){var e=Body();while(true){object v;try{if(!e.MoveNext())break;v=e.Current;}catch(Exception ex){Finish(false,ex.ToString());yield break;}yield return v;}Finish(errors.Length==0,errors);}
 static IEnumerator Body(){
  var rows=new[]{new[]{3},new[]{3},new[]{2,3},new[]{2,3}};var cols=new[]{new int[0],new[]{3},new[]{3},new[]{2,3}};var shapes=new[]{BlockCatalog.Shapes[0],BlockCatalog.Shapes[0],BlockCatalog.Shapes[3],BlockCatalog.Shapes[5]};var anchors=new[]{new Vector2Int(3,3),new Vector2Int(3,3),new Vector2Int(3,2),new Vector2Int(2,2)};
  for(int n=0;n<4;n++){Prepare(rows[n],cols[n],shapes[n],anchors[n],0);yield return Case(anchors[n],shapes[n].Cells.Count,new[]{10,25,45,70}[n],"정상 "+(n+1)+"라인",n==0);}
  Prepare(rows[1],cols[1],shapes[1],anchors[1],1495);yield return Case(anchors[1],1,5,"목표 초과 2라인 실제 +5",false);
  for(int id=1;id<=5;id++){PlanetSelection.Select(id);game.LoadSelectedPlanet();Prepare(rows[0],cols[0],shapes[0],anchors[0],game.Restoration.Total);yield return Case(anchors[0],1,0,"완료 행성 "+id+" 실제 +0",false);}
  PlanetSelection.Select(1);game.LoadSelectedPlanet();Prepare(rows[0],cols[0],shapes[0],anchors[0],0);yield return Case(anchors[0],1,10,"연속 Combo 첫 턴",false);game.DebugPrepareNextRow();yield return Case(anchors[0],1,10,"연속 Combo 두 번째 턴",false);Req(game.Combo==2,"기존 턴 Combo 유지");
  Prepare(rows[0],cols[0],shapes[0],anchors[0],0);game.TryPlacePiece(game.Slots[0],3,3);flow.ShowHome();Req(!feedback.EnergyPopupVisible&&feedback.EnergyPopupText=="","HOME cleanup");flow.Play();Req(!feedback.EnergyPopupVisible,"이어하기 stale 별빛 없음");results.Add("PASS HOME/이어하기 정리");
 }
 static IEnumerator Case(Vector2Int anchor,int placedCells,int expectedEnergy,string label,bool render){int beforeEnergy=game.Restoration.CurrentEnergy,beforeScore=game.Score;Req(game.TryPlacePiece(game.Slots[0],anchor.x,anchor.y),"배치 "+label);int lines=game.LastClear.LineCount,seen=0,sum=0,points=0;
  while(seen<lines){if(game.LineComboIndex==seen+1){seen++;int linePoints=ScoreRules.LinePoints(seen);Req(feedback.ScorePopupText=="+"+linePoints+" SCORE","실제 SCORE 텍스트");Req(feedback.EnergyPopupText=="별빛 +"+feedback.LastEnergyDelta&&feedback.EnergyPopupVisible,"별빛 텍스트/표시");sum+=feedback.LastEnergyDelta;points+=linePoints;Req(game.Score==beforeScore+placedCells*10+points,"라인별 보너스와 배치 점수 분리");Req(seen==1?feedback.ComboPopupText=="CLEAR!":feedback.ComboPopupText==seen+" COMBO","기존 제목/Combo");Req(PlayerPrefs.GetInt(game.Restoration.Definition.EnergyKey)==beforeEnergy+expectedEnergy,"실제 영구 별빛 적립");if(render){foreach(int h in new[]{1920,2400,1440})Capture(h);render=false;}}yield return null;}
  Req(sum==expectedEnergy&&game.Restoration.CurrentEnergy-beforeEnergy==sum,"표시 합계와 실제 적립 일치 "+label);game.DebugCompleteTurnForProbe();Req(RunSaveStore.Load().score==game.Score&&RunSaveStore.Load().planetEnergy==game.Restoration.CurrentEnergy,"저장 일치");yield return new WaitForSecondsRealtime(.75f);Req(!feedback.EnergyPopupVisible&&feedback.EnergyPopupText=="","Fade 종료 stale 없음");results.Add("PASS "+label+" 별빛 표시 합계="+sum+" SCORE 보너스="+points);
 }
 static void Prepare(int[] rows,int[] cols,BlockShape shape,Vector2Int anchor,int energy){PlayerPrefs.SetInt(PlanetCompletionNotice.Key(PlanetSelection.Current),2);flow.ShowHome();flow.StartNewRun();game.DebugSetPlanetEnergy(energy);var layer=(RectTransform)GameObject.Find("GameCanvas").transform.Find("DragLayer");foreach(var piece in game.Slots)piece.Initialize(shape,board,layer,game);for(int y=0;y<8;y++)for(int x=0;x<8;x++)if(Array.IndexOf(rows,y)>=0||Array.IndexOf(cols,x)>=0){bool gap=false;foreach(var c in shape.Cells)if(x==anchor.x+c.x&&y==anchor.y+c.y)gap=true;if(!gap){board.Model.SetOccupied(x,y,true);board.PaintPlacement(BlockCatalog.Shapes[0],x,y,board.BlockSprite((x+y)%3));}}}
 static void Capture(int h){var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var safe=(RectTransform)canvas.transform.Find("SafeArea");var area=safe.GetComponent<SafeArea>();var cam=Camera.main;var oldMode=canvas.renderMode;var oldCamera=canvas.worldCamera;var oldTarget=cam.targetTexture;var oldActive=RenderTexture.active;var min=safe.anchorMin;var max=safe.anchorMax;bool enabled=area.enabled;var rt=new RenderTexture(1080,h,24);Texture2D tex=null;try{area.enabled=false;rt.Create();cam.targetTexture=rt;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=10;safe.anchorMin=h==2400?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=h==2400?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>().RefreshVisual();board.SendMessage("LateUpdate");Canvas.ForceUpdateCanvases();feedback.RefreshLayout();foreach(var name in new[]{"ComboPop","ScorePop","EnergyPop"}){var t=feedback.transform.Find(name).GetComponent<Text>();Req(t.cachedTextGenerator.characterCountVisible>=t.text.Length,"잘림 "+name+" "+h);}cam.Render();RenderTexture.active=rt;tex=new Texture2D(1080,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1080,h),0,0);tex.Apply();File.WriteAllBytes("Validation/polish001_clear_"+h+".png",tex.EncodeToPNG());}finally{canvas.renderMode=oldMode;canvas.worldCamera=oldCamera;cam.targetTexture=oldTarget;RenderTexture.active=oldActive;safe.anchorMin=min;safe.anchorMax=max;area.enabled=enabled;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}
 static void Req(bool b,string m){if(!b)throw new Exception(m);}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;Application.logMessageReceived-=Log;if(game!=null)game.LeaveForHome();RunSaveStore.Delete();foreach(var k in keys){if(saved.TryGetValue(k,out int v))PlayerPrefs.SetInt(k,v);else PlayerPrefs.DeleteKey(k);}PlayerPrefs.Save();File.WriteAllText("Validation/polish001_tests.txt",string.Join("\n",results)+"\n"+(pass?"POLISH001_PASS":failure));if(pass)Debug.Log("POLISH001_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
