using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using CosmicBlock.Core;
using CosmicBlock.Blocks;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class RunSavePlayProbe {
 static double started;static int frames,count;static string errors="",warnings="";static GameSession session;static GameFlowController flow;static HomeRunControls controls;static Dictionary<string,int> saved=new Dictionary<string,int>();static List<string> keys=new List<string>(),results=new List<string>();
 public static void Run(){RunSaveStore.PathOverride=Path.GetFullPath("Validation/run-save-test.json");RunSaveStore.Delete();keys.Add(PlanetSelection.Key);keys.Add(PlanetRestoration.VersionKey);keys.Add(GameSession.DefaultBestScoreKey);foreach(var d in PlanetDefinitions.All){keys.Add(d.EnergyKey);keys.Add(d.UnlockKey);}foreach(var k in keys){if(PlayerPrefs.HasKey(k))saved[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.SetInt(GameSession.DefaultBestScoreKey,15930);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,1500);PlayerPrefs.Save();EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>180){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<35)return;EditorApplication.update-=Check;RunSaveStore.PathOverride=Path.GetFullPath("Validation/run-save-test.json");session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();controls=flow.HomeRoot.GetComponent<HomeRunControls>();session.StartCoroutine(Tests());}
 static IEnumerator Tests(){var routine=Body();while(true){object value;try{if(!routine.MoveNext())break;value=routine.Current;}catch(Exception e){Finish(false,e.ToString());yield break;}yield return value;}Finish(errors.Length==0,errors);}
 static IEnumerator Body(){
  Req(flow.Screen==FlowScreen.Home&&!flow.HasSavedRun,"cold HOME no run");Req(Primary().sprite.name=="home_play_button"&&Primary().GetComponentsInChildren<Text>(true).Length==0,"PLAY asset no duplicate text");Capture("fresh");
  flow.Play();session.DebugSetScore(980);SetShapes(BlockCatalog.Shapes[0]);Req(session.TryPlacePiece(session.Slots[0],0,0)&&session.TryPlacePiece(session.Slots[1],2,0),"two placements");var before=RunSaveStore.Load();Req(before.score==1000&&before.consumed[0]&&before.consumed[1]&&!before.consumed[2],"autosaved two consumed");var drag=session.Slots[2].GetComponent<BlockDragHandler>();var origin=drag.transform.parent;var pointer=new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current){pointerId=91,position=new Vector2(Screen.width*.5f,Screen.height*.3f)};drag.OnBeginDrag(pointer);Req(drag.IsDragging,"drag before pause");session.SendMessage("OnApplicationPause",true);Req(!drag.IsDragging&&drag.transform.parent==origin,"pause cancels drag into original slot");Equal(before,"drag pause leaves only committed placement");flow.RequestHome();Req(GameObject.Find("GameCanvas").transform.Find("SafeArea/ExitConfirm/Card/Question").GetComponent<Text>().text=="게임을 저장하고 홈으로 이동할까요?","HOME save confirmation wording");flow.ConfirmHome();Req(flow.HasSavedRun&&Primary().sprite.name=="home_continue_button","HOME resume asset");Capture("continue");flow.Play();Equal(before,"A/B Score Board colors pieces exact restore");Req(session.BestScore==15930,"BEST preserved");
  session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"clear one");session.DebugCompleteTurnForProbe();session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"clear combo2");session.DebugCompleteTurnForProbe();Req(session.Combo==2,"combo2");flow.ShowHome();var combo=RunSaveStore.Load();flow.Play();Equal(combo,"C combo restored");
  flow.ShowHome();string disk=File.ReadAllText(RunSaveStore.SavePath);controls.RequestNewGame();Req(controls.NewGameVisible,"new game confirm");Capture("confirm");controls.CancelNewGame();Req(!controls.NewGameVisible&&File.ReadAllText(RunSaveStore.SavePath)==disk,"E cancel no overwrite");controls.RequestNewGame();controls.ConfirmNewGame();Req(session.Score==0&&session.Combo==0&&Empty()&&AllPieces()&&session.BestScore==15930,"F explicit new run");
  session.DebugSetPlanetEnergy(100);session.DebugPrepareCross();Req(session.TryPlacePiece(session.Slots[0],3,3),"cross resolving");var projected=RunSaveStore.Load();Req(projected.score==260&&projected.planetEnergy==125&&Array.TrueForAll(projected.cells,c=>c==-1),"safe completed logical checkpoint during clear");flow.RequestHome();flow.ConfirmHome();Req(session.Restoration.CurrentEnergy==125,"H durable award once");PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,100);PlayerPrefs.Save();flow.Play();Equal(projected,"clear interrupted HOME stable restore");Req(PlayerPrefs.GetInt(PlanetRestoration.DefaultKey)==125,"interrupted preference flush recovered once");Req(session.Restoration.CurrentEnergy==125,"H no duplicated energy");yield return new WaitForSecondsRealtime(2);Req(session.Restoration.CurrentEnergy==125&&session.State==GameState.Playing,"no stale callback");
  flow.ShowHome();Req(PlanetSelection.Select(2),"unlock2");session.LoadSelectedPlanet();flow.RefreshHome();controls.RequestNewGame();controls.ConfirmNewGame();Req(session.Restoration.PlanetId==2,"selected2 new run");session.DebugSetScore(1000);SetShapes(BlockCatalog.Shapes[0]);session.TryPlacePiece(session.Slots[0],1,1);session.SendMessage("OnApplicationPause",true);var persisted=RunSaveStore.Load();Req(persisted.score==1010,"K background writes");flow.ShowHome();Req(PlanetSelection.Select(1),"select1 while run2 saved");session.LoadSelectedPlanet();flow.RefreshHome();flow.Play();Equal(persisted,"I run planet independent selection");Req(session.Restoration.PlanetId==2&&PlanetSelection.Current==1,"run2 vs selected1");
  session.LeaveForHome();session.Model.Clear();session.DebugSetScore(0);Req(session.ResumeSavedRun(),"D reload from disk");Equal(persisted,"D restored persisted model");
  session.DebugForceGameOver();Req(session.State==GameState.GameOver&&!flow.HasSavedRun,"G gameover invalidates");flow.ShowHome();Req(Primary().sprite.name=="home_play_button","GAME OVER HOME play image");flow.Play();Req(session.Score==0&&session.State==GameState.Playing,"new run after GAME OVER");session.DebugForceGameOver();session.Retry();Req(session.Score==0&&session.State==GameState.Playing&&flow.HasSavedRun,"Retry creates saved run");
  flow.ShowHome();File.WriteAllText(RunSaveStore.SavePath,"{ broken");Req(!flow.HasSavedRun,"J malformed safe");flow.RefreshHome();Req(Primary().sprite.name=="home_play_button","J malformed play fallback");flow.Play();Req(session.State==GameState.Playing&&flow.HasSavedRun,"J fresh after malformed");var valid=RunSaveStore.Load();valid.version=99;File.WriteAllText(RunSaveStore.SavePath,JsonUtility.ToJson(valid));Req(!flow.HasSavedRun,"future version rejected");valid.version=1;valid.cells[0]=9;Req(!RunSaveStore.Valid(valid),"invalid palette rejected");valid.cells[0]=-1;valid.shapes[0]=99;Req(!RunSaveStore.Valid(valid),"invalid shape rejected");valid.shapes[0]=0;valid.planetId=3;Req(!RunSaveStore.Valid(valid),"unprepared planet rejected");Req(!PlanetSelection.Select(3),"existing3 content guard retained");
  flow.StartNewRun();SetShapes(BlockCatalog.Shapes[0]);session.Slots[0].Consume();session.Slots[1].Consume();session.DebugPrepareNextRow();session.Slots[0].Consume();session.Slots[1].Consume();Req(session.TryPlacePiece(session.Slots[2],3,3),"last piece clear");var supply=RunSaveStore.Load();Req(supply.blockSetNumber==session.BlockSetNumber+1&&Array.TrueForAll(supply.consumed,c=>!c),"checkpoint includes next three pieces");session.DebugCompleteTurnForProbe();Equal(supply,"supply exactly matches reserved checkpoint");
  results.Add("PASS A-L (I uses ready planet02 vs01; planet03 remains unavailable), stable clear checkpoints, pending supply, corruption/version, persisted model");Req(warnings.Length==0,"runtime warnings "+warnings);
 }
 static void SetShapes(BlockShape s)=>typeof(GameSession).GetMethod("DebugSetShapes",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(session,new object[]{s});
 static bool Empty(){for(int y=0;y<8;y++)for(int x=0;x<8;x++)if(session.Model.IsOccupied(x,y))return false;return true;}
 static bool AllPieces(){foreach(var p in session.Slots)if(p.IsConsumed)return false;return true;}
 static Image Primary()=>flow.HomeRoot.transform.Find("MainActions/GameStartButton").GetComponent<Image>();
 static void Equal(RunSnapshot s,string label){Req(session.Score==s.score&&session.Combo==s.combo&&session.BlockSetNumber==s.blockSetNumber&&session.Restoration.PlanetId==s.planetId,label+" counters");var b=UnityEngine.Object.FindAnyObjectByType<CosmicBlock.Board.BoardView>().CaptureCells();for(int i=0;i<64;i++)Req(b[i]==s.cells[i],label+" cell"+i);for(int i=0;i<3;i++)Req(session.Slots[i].Shape==BlockCatalog.Shapes[s.shapes[i]]&&session.Slots[i].AppearanceIndex==s.appearances[i]&&session.Slots[i].IsConsumed==s.consumed[i],label+" piece"+i);results.Add("PASS "+label);}
 static void Capture(string state){foreach(var size in new[]{new Vector2Int(1080,1920),new Vector2Int(1080,2400),new Vector2Int(1080,1440)}){var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var camera=Camera.main;var safe=(RectTransform)flow.HomeRoot.transform.parent;var sa=safe.GetComponent<SafeArea>();var mode=canvas.renderMode;var wc=canvas.worldCamera;var target=camera.targetTexture;var active=RenderTexture.active;var amin=safe.anchorMin;var amax=safe.anchorMax;bool enabled=sa.enabled;bool ortho=camera.orthographic;float os=camera.orthographicSize;var rt=new RenderTexture(size.x,size.y,24);Texture2D tex=null;try{sa.enabled=false;rt.Create();camera.targetTexture=rt;camera.orthographic=true;camera.orthographicSize=size.y/2f;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=camera;canvas.planeDistance=10;safe.anchorMin=size.y==2400?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=size.y==2400?new Vector2(.98f,.94f):Vector2.one;Canvas.ForceUpdateCanvases();flow.HomeRoot.GetComponent<HomeFinalLayout>().Apply();controls.Layout();Canvas.ForceUpdateCanvases();var bg=flow.HomeRoot.transform.Find("HomeBackground")as RectTransform;var full=(RectTransform)canvas.transform;var reference=new Vector2(940,1672);bg.sizeDelta=reference*Mathf.Max(full.rect.width/reference.x,full.rect.height/reference.y);bg.anchoredPosition=((RectTransform)flow.HomeRoot.transform).InverseTransformPoint(full.TransformPoint(full.rect.center));Canvas.ForceUpdateCanvases();var root=World((RectTransform)flow.HomeRoot.transform);var newRect=World(flow.HomeRoot.transform.Find("NewGameButton")as RectTransform);Req(root.Contains(newRect.min)&&root.Contains(newRect.max),"new game safe area "+size);if(state!="fresh"){Req(!newRect.Overlaps(World(flow.HomeRoot.transform.Find("DevButton")as RectTransform)),"no DEV overlap "+size);foreach(string path in new[]{"BottomActions/SettingsButton","BottomActions/QuitButton","BestScoreArea","MainActions/GameStartButton","MainActions/PlanetCollectionButton"})Req(!newRect.Overlaps(World(flow.HomeRoot.transform.Find(path)as RectTransform)),"no overlap "+path+" "+size);}camera.Render();RenderTexture.active=rt;tex=new Texture2D(size.x,size.y,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,size.x,size.y),0,0);tex.Apply();File.WriteAllBytes("Validation/run_save_"+state+"_"+size.y+".png",tex.EncodeToPNG());}finally{canvas.renderMode=mode;canvas.worldCamera=wc;camera.targetTexture=target;camera.orthographic=ortho;camera.orthographicSize=os;RenderTexture.active=active;safe.anchorMin=amin;safe.anchorMax=amax;sa.enabled=enabled;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}}
 static Rect World(RectTransform r){var c=new Vector3[4];r.GetWorldCorners(c);return Rect.MinMaxRect(c[0].x,c[0].y,c[2].x,c[2].y);}
 static void Req(bool v,string why){count++;if(!v)throw new Exception(why);}
 static void Log(string m,string s,LogType type){if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors+=m+"\n";if(type==LogType.Warning)warnings+=m+"\n";}
 static void Finish(bool pass,string why){EditorApplication.update-=Check;Application.logMessageReceived-=Log;session?.LeaveForHome();RunSaveStore.Delete();foreach(var k in keys){if(saved.TryGetValue(k,out int value))PlayerPrefs.SetInt(k,value);else PlayerPrefs.DeleteKey(k);}PlayerPrefs.Save();File.WriteAllText("Validation/run_save_tests.txt",string.Join("\n",results)+"\nAssertions="+count+"\nWarnings="+warnings+"\n"+(pass?"RUN_SAVE_PASS":why));Debug.Log(pass?"RUN_SAVE_PASS":why);EditorApplication.Exit(pass?0:1);}
}
