using System;
using System.Collections.Generic;
using CosmicBlock.Board;
using CosmicBlock.Core;
using CosmicBlock.UI;
using TMPro;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint9GameBuilder {
 const string Art="Assets/Art/UI/Game/";
 static readonly string[] Names={"game_home_button","game_best_score_frame","game_planet_status_frame","game_board_frame","game_empty_cell","game_block_blue","game_block_purple","game_block_gold","game_piece_slot"};
 public static void Build(){
  AssetDatabase.Refresh();foreach(string n in Names){var t=AssetImporter.GetAtPath(Art+n+".png") as TextureImporter;if(t==null)throw new Exception("Missing GAME asset "+n);t.textureType=TextureImporterType.Sprite;t.spriteImportMode=SpriteImportMode.Single;t.alphaSource=TextureImporterAlphaSource.FromInput;t.alphaIsTransparency=true;t.mipmapEnabled=false;t.filterMode=FilterMode.Bilinear;t.wrapMode=TextureWrapMode.Clamp;t.textureCompression=TextureImporterCompression.Uncompressed;t.maxTextureSize=n.Contains("frame")?2048:1024;var settings=new TextureImporterSettings();t.ReadTextureSettings(settings);settings.spriteMeshType=SpriteMeshType.FullRect;t.SetTextureSettings(settings);var a=t.GetPlatformTextureSettings("Android");a.overridden=true;a.maxTextureSize=t.maxTextureSize;a.format=TextureImporterFormat.ASTC_6x6;a.compressionQuality=100;t.SetPlatformTextureSettings(a);t.SaveAndReimport();}
  var font=AssetDatabase.LoadAssetAtPath<TMP_FontAsset>("Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset");if(font==null)throw new Exception("TMP essential font unavailable");
  string original=System.IO.File.ReadAllText("Assets/Scenes/Game.unity");var scene=EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");var canvas=GameObject.Find("GameCanvas");var safe=canvas.transform.Find("SafeArea");var flow=canvas.GetComponent<GameFlowController>();var session=canvas.GetComponent<GameSession>()??UnityEngine.Object.FindAnyObjectByType<GameSession>();var board=UnityEngine.Object.FindAnyObjectByType<BoardView>();
  var br=(RectTransform)board.transform;Set(br,.5f,.415f,.5f,.415f);board.GetComponent<SquareBoardLayout>().ConfigureGameVisual();board.GetComponent<Image>().color=new Color(.015f,.025f,.065f,.93f);board.GetComponent<Outline>().effectDistance=Vector2.zero;board.GetComponent<Outline>().enabled=false;
  board.ConfigureSkin(Sprite(4),new[]{Sprite(5),Sprite(6),Sprite(7)});foreach(Transform cell in board.transform){var im=cell.GetComponent<Image>();im.sprite=Sprite(4);im.color=BoardView.EmptyFill;im.preserveAspect=true;cell.GetComponent<Outline>().effectDistance=Vector2.zero;}
  foreach(string n in new[]{"GameScorePresentation","BoardFrame"}){var old=safe.Find(n);if(old!=null)UnityEngine.Object.DestroyImmediate(old.gameObject);}
  var frame=Image("BoardFrame",safe,Sprite(3),.5f,.415f,.5f,.415f);frame.transform.SetSiblingIndex(board.transform.GetSiblingIndex());
  var home=safe.Find("PlayingHomeButton");var homeFill=home.Find("ThemeFill");if(homeFill!=null)UnityEngine.Object.DestroyImmediate(homeFill.gameObject);Set((RectTransform)home,.02f,.895f,.15f,.985f);home.GetComponent<Image>().sprite=Sprite(0);home.GetComponent<Image>().color=Color.white;home.GetComponent<Image>().preserveAspect=true;home.GetComponent<Image>().type=UnityEngine.UI.Image.Type.Simple;home.GetComponent<Button>().transition=Selectable.Transition.None;foreach(var o in home.GetComponents<Outline>())o.enabled=false;home.Find("Text").GetComponent<Text>().enabled=false;
  safe.Find("Title").GetComponent<Text>().enabled=false;safe.Find("TrayPlaceholder").GetComponent<Text>().enabled=false;safe.Find("ScorePlaceholder").GetComponent<Text>().enabled=false;
  var scores=UI("GameScorePresentation",safe,0,0,1,1);scores.SetSiblingIndex(safe.Find("ScorePlaceholder").GetSiblingIndex()+1);var bestFrame=Image("BestFrame",scores,Sprite(1),.65f,.93f,.98f,.995f);Fit(bestFrame);var best=Tmp("BestValue",bestFrame.transform,font,37,.48f,.24f,.86f,.52f);best.color=new Color(1,.85f,.45f);
  var label=Tmp("ScoreLabel",scores,font,26,.35f,.939f,.65f,.985f);label.text="SCORE";label.color=new Color(.75f,.89f,1);var score=Tmp("CurrentScore",scores,font,70,.28f,.879f,.72f,.927f);score.color=Color.white;
  var panel=(RectTransform)safe.Find("PlanetRestoration");var panelFill=panel.Find("ThemeFill");if(panelFill!=null)UnityEngine.Object.DestroyImmediate(panelFill.gameObject);Set(panel,.5f,.77f,.5f,.77f);panel.GetComponent<Image>().color=Color.clear;panel.GetComponent<Image>().raycastTarget=false;foreach(var o in panel.GetComponents<Outline>())o.enabled=false;
  var oldArt=panel.Find("StatusFrame");if(oldArt!=null)UnityEngine.Object.DestroyImmediate(oldArt.gameObject);var status=Image("StatusFrame",panel,Sprite(2),0,0,1,1);status.transform.SetAsFirstSibling();
  Set((RectTransform)panel.Find("PlanetVisual"),.025f,.19f,.275f,.82f);Set((RectTransform)panel.Find("Title"),.29f,.55f,.60f,.68f);Set((RectTransform)panel.Find("Stage"),.295f,.35f,.475f,.48f);Set((RectTransform)panel.Find("Energy"),.29f,.28f,.47f,.355f);panel.Find("Title").GetComponent<Text>().fontSize=25;panel.Find("Title").GetComponent<Text>().resizeTextMaxSize=25;panel.Find("Stage").GetComponent<Text>().fontSize=18;panel.Find("Stage").GetComponent<Text>().resizeTextMaxSize=18;panel.Find("Energy").GetComponent<Text>().fontSize=16;panel.Find("Energy").GetComponent<Text>().resizeTextMaxSize=16;
  Set((RectTransform)panel.Find("ProgressBar"),.50f,.33f,.91f,.43f);panel.Find("ProgressBar").GetComponent<Image>().color=new Color(.015f,.025f,.07f,.85f);var progressFill=panel.Find("ProgressBar/Fill").GetComponent<Image>();progressFill.sprite=StarlightUiTheme.RoundedSprite;progressFill.type=UnityEngine.UI.Image.Type.Sliced;
  var oldPercent=panel.Find("RestorationPercent");if(oldPercent!=null)UnityEngine.Object.DestroyImmediate(oldPercent.gameObject);var percent=Text("RestorationPercent",panel,28,.70f,.50f,.91f,.61f);percent.color=new Color(1,.8f,.35f);
  var bottom=safe.Find("BlockArea");Set((RectTransform)bottom,.02f,.02f,.98f,.16f);var grid=bottom.GetComponent<HorizontalLayoutGroup>();if(grid!=null){grid.spacing=20;grid.padding=new RectOffset(8,8,0,0);}for(int i=0;i<3;i++){var slot=bottom.Find("Slot_"+i);if(slot==null)throw new Exception("Slot missing");var image=slot.GetComponent<Image>();image.sprite=Sprite(8);image.preserveAspect=true;}
  var presentation=scores.gameObject.AddComponent<GameVisualPresentation>();presentation.Configure(session,score,best,percent,panel.GetComponent<PlanetRestorationView>(),br,frame,panel,status);
  var roots=new List<GameObject>();foreach(var root in flow.GameRoots)if(root!=null&&root.name!="GameScorePresentation"&&root.name!="BoardFrame")roots.Add(root);roots.Add(scores.gameObject);roots.Add(frame.gameObject);var so=new SerializedObject(flow);var property=so.FindProperty("gameRoots");property.arraySize=roots.Count;for(int i=0;i<roots.Count;i++)property.GetArrayElementAtIndex(i).objectReferenceValue=roots[i];so.ApplyModifiedPropertiesWithoutUndo();
  foreach(var r in new[]{scores,frame.rectTransform}){var group=r.GetComponent<CanvasGroup>();if(group==null)group=r.gameObject.AddComponent<CanvasGroup>();group.alpha=0;group.blocksRaycasts=group.interactable=false;}
  safe.Find("GameOverPanel").SetAsLastSibling();safe.Find("ExitConfirm").SetAsLastSibling();presentation.Layout();board.SendMessage("LateUpdate");PreserveHome(original,safe);EditorUtility.SetDirty(board);EditorUtility.SetDirty(flow);EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();Debug.Log("SPRINT9_GAME_VISUAL_READY");
 }
 public static void PreserveHome(string source,Transform safe){var p=safe.Find("HomeRoot/HomeBackground") as RectTransform;if(p==null)return;foreach(System.Text.RegularExpressions.Match block in System.Text.RegularExpressions.Regex.Matches(source,@"(?ms)^--- !u!224 &\d+\r?\n.*?(?=^---|\z)")){var go=System.Text.RegularExpressions.Regex.Match(block.Value,@"m_GameObject: \{fileID: (\d+)\}");var owner=System.Text.RegularExpressions.Regex.Match(source,@"(?ms)^--- !u!1 &"+go.Groups[1].Value+@"\r?\n.*?(?=^---|\z)");if(!owner.Value.Contains("m_Name: HomeBackground"))continue;var size=System.Text.RegularExpressions.Regex.Match(block.Value,@"m_SizeDelta: \{x: ([^,]+), y: ([^}]+)\}");p.sizeDelta=new Vector2(float.Parse(size.Groups[1].Value,System.Globalization.CultureInfo.InvariantCulture),float.Parse(size.Groups[2].Value,System.Globalization.CultureInfo.InvariantCulture));break;}}
 static Sprite Sprite(int i)=>AssetDatabase.LoadAssetAtPath<Sprite>(Art+Names[i]+".png");
 static RectTransform UI(string n,Transform p,float x0,float y0,float x1,float y1){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);Set(r,x0,y0,x1,y1);return r;}
 static void Set(RectTransform r,float x0,float y0,float x1,float y1){r.anchorMin=new Vector2(x0,y0);r.anchorMax=new Vector2(x1,y1);r.offsetMin=r.offsetMax=Vector2.zero;r.localScale=Vector3.one;}
 static Image Image(string n,Transform p,Sprite sprite,float x0,float y0,float x1,float y1){var i=UI(n,p,x0,y0,x1,y1).gameObject.AddComponent<Image>();i.sprite=sprite;i.preserveAspect=true;i.raycastTarget=false;return i;}
 static void Fit(Image i){var r=i.rectTransform;var holder=UI(i.name+"Area",r.parent,r.anchorMin.x,r.anchorMin.y,r.anchorMax.x,r.anchorMax.y);r.SetParent(holder,false);Set(r,0,0,1,1);var fit=r.gameObject.AddComponent<AspectRatioFitter>();fit.aspectMode=AspectRatioFitter.AspectMode.FitInParent;fit.aspectRatio=i.sprite.rect.width/i.sprite.rect.height;}
 static TextMeshProUGUI Tmp(string n,Transform p,TMP_FontAsset font,float size,float x0,float y0,float x1,float y1){var t=UI(n,p,x0,y0,x1,y1).gameObject.AddComponent<TextMeshProUGUI>();t.font=font;t.fontSize=size;t.fontSizeMax=size;t.fontSizeMin=15;t.enableAutoSizing=true;t.fontStyle=FontStyles.Bold;t.alignment=TextAlignmentOptions.Center;t.raycastTarget=false;t.textWrappingMode=TextWrappingModes.NoWrap;return t;}
 static Text Text(string n,Transform p,int size,float x0,float y0,float x1,float y1){var t=UI(n,p,x0,y0,x1,y1).gameObject.AddComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.fontSize=size;t.resizeTextForBestFit=true;t.resizeTextMinSize=15;t.resizeTextMaxSize=size;t.fontStyle=FontStyle.Bold;t.alignment=TextAnchor.MiddleCenter;t.raycastTarget=false;return t;}
}