using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using CosmicBlock.Core;
using CosmicBlock.Blocks;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint103QuitProbe {
 static double started;static int frames,count;static string errors="",warnings="";static GameSession session;static GameFlowController flow;static HomeRunControls controls;static Dictionary<string,int> saved=new Dictionary<string,int>();static List<string> keys=new List<string>(),results=new List<string>();
 public static void Run(){RunSaveStore.PathOverride=Path.GetFullPath("Validation/sprint103-run.json");RunSaveStore.Delete();keys.Add(PlanetSelection.Key);keys.Add(PlanetRestoration.VersionKey);keys.Add(GameSession.DefaultBestScoreKey);foreach(var d in PlanetDefinitions.All){keys.Add(d.EnergyKey);keys.Add(d.UnlockKey);}foreach(var k in keys){if(PlayerPrefs.HasKey(k))saved[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.SetInt(GameSession.DefaultBestScoreKey,15930);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,1500);PlayerPrefs.Save();EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>180){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<35)return;EditorApplication.update-=Check;RunSaveStore.PathOverride=Path.GetFullPath("Validation/sprint103-run.json");session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();controls=flow.HomeRoot.GetComponent<HomeRunControls>();session.StartCoroutine(Tests());}
 static IEnumerator Tests(){var routine=Body();while(true){object value;try{if(!routine.MoveNext())break;value=routine.Current;}catch(Exception e){Finish(false,e.ToString());yield break;}yield return value;}Finish(errors.Length==0,errors);}
 static IEnumerator Body(){
  flow.StartNewRun();SetShapes(BlockCatalog.Shapes[0]);Req(session.TryPlacePiece(session.Slots[0],1,1),"committed run");flow.ShowHome();var before=File.ReadAllBytes(RunSaveStore.SavePath);int best=session.BestScore,energy=session.Restoration.CurrentEnergy;var music=CosmicBlock.Audio.BackgroundMusicController.Current;bool enabled=music.MusicEnabled,sfx=music.SfxEnabled;float volume=music.MusicVolume;
  var home=flow.HomeRoot.transform;home.Find("BottomActions/QuitButton").GetComponent<Button>().onClick.Invoke();Req(flow.HomeView.QuitVisible,"actual quit button opens");Capture("quit");
  var hits=new List<UnityEngine.EventSystems.RaycastResult>();var play=(RectTransform)home.Find("MainActions/GameStartButton");var canvas=home.GetComponentInParent<Canvas>();var cam=canvas.renderMode==RenderMode.ScreenSpaceOverlay?null:canvas.worldCamera;UnityEngine.EventSystems.EventSystem.current.RaycastAll(new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(cam,play.position)},hits);Req(hits.Count>0&&hits[0].gameObject.transform.IsChildOf(home.Find("QuitConfirmPanel")),"overlay blocks HOME play touch");
  home.Find("QuitConfirmPanel/Card/Cancel").GetComponent<Button>().onClick.Invoke();Req(!flow.HomeView.QuitVisible&&flow.Screen==FlowScreen.Home&&!flow.QuitRequested,"cancel HOME");Req(Convert.ToBase64String(before)==Convert.ToBase64String(File.ReadAllBytes(RunSaveStore.SavePath)),"cancel run file unchanged");
  for(int i=0;i<10;i++){flow.HomeView.ShowQuit();flow.HomeView.ShowQuit();flow.HomeView.CancelQuit();}Req(!flow.HomeView.QuitVisible,"rapid open cancel");
  flow.HomeView.ShowQuit();home.Find("QuitConfirmPanel/Card/Confirm").GetComponent<Button>().onClick.Invoke();flow.HomeView.ConfirmQuit();Req(flow.QuitRequested&&!flow.HomeView.QuitVisible&&flow.Screen==FlowScreen.Home,"existing quit request/editor stays running/duplicate ignored");session.SendMessage("OnApplicationQuit");Req(RunSaveStore.Load()!=null&&RunSaveStore.Load().score==10,"quit saves without reset");Req(session.BestScore==best&&session.Restoration.CurrentEnergy==energy,"BEST and planet unchanged");Req(music.MusicEnabled==enabled&&music.SfxEnabled==sfx&&music.MusicVolume==volume,"audio settings unchanged");flow.Play();Req(session.Score==10&&session.Slots[0].IsConsumed,"continue after quit");results.Add("PASS open/cancel/confirm/rapid touches/overlay blocking/Run SCORE BEST planet/audio preserved");yield return null;
 }
 static void SetShapes(BlockShape s)=>typeof(GameSession).GetMethod("DebugSetShapes",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(session,new object[]{s});
 static bool Empty(){for(int y=0;y<8;y++)for(int x=0;x<8;x++)if(session.Model.IsOccupied(x,y))return false;return true;}
 static bool AllPieces(){foreach(var p in session.Slots)if(p.IsConsumed)return false;return true;}
 static Image Primary()=>flow.HomeRoot.transform.Find("MainActions/GameStartButton").GetComponent<Image>();
 static void Equal(RunSnapshot s,string label){Req(session.Score==s.score&&session.Combo==s.combo&&session.BlockSetNumber==s.blockSetNumber&&session.Restoration.PlanetId==s.planetId,label+" counters");var b=UnityEngine.Object.FindAnyObjectByType<CosmicBlock.Board.BoardView>().CaptureCells();for(int i=0;i<64;i++)Req(b[i]==s.cells[i],label+" cell"+i);for(int i=0;i<3;i++)Req(session.Slots[i].Shape==BlockCatalog.Shapes[s.shapes[i]]&&session.Slots[i].AppearanceIndex==s.appearances[i]&&session.Slots[i].IsConsumed==s.consumed[i],label+" piece"+i);results.Add("PASS "+label);}
 static void Capture(string state){foreach(int h in new[]{1920,2400,1440}){var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var camera=Camera.main;var safe=(RectTransform)flow.HomeRoot.transform.parent;var sa=safe.GetComponent<SafeArea>();var mode=canvas.renderMode;var wc=canvas.worldCamera;var target=camera.targetTexture;var active=RenderTexture.active;var amin=safe.anchorMin;var amax=safe.anchorMax;bool enabled=sa.enabled,ortho=camera.orthographic;float size=camera.orthographicSize;var rt=new RenderTexture(1080,h,24);Texture2D tex=null;try{sa.enabled=false;rt.Create();camera.targetTexture=rt;camera.orthographic=true;camera.orthographicSize=h/2f;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=camera;canvas.planeDistance=10;safe.anchorMin=h==2400?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=h==2400?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();flow.HomeRoot.GetComponent<HomeFinalLayout>().Apply();var card=(RectTransform)flow.HomeRoot.transform.Find("QuitConfirmPanel/Card");card.GetComponent<HomeQuitPopupLayout>().Apply();Canvas.ForceUpdateCanvases();var overlay=World((RectTransform)card.parent.Find("DimOverlay"));var full=World((RectTransform)canvas.transform);Req(overlay.xMin<=full.xMin+.1f&&overlay.yMin<=full.yMin+.1f&&overlay.xMax>=full.xMax-.1f&&overlay.yMax>=full.yMax-.1f,"fullscreen dim overlay "+h);var bounds=World(safe);var r=World(card);Req(bounds.Contains(r.min)&&bounds.Contains(r.max),"popup safe area "+h);Req(Mathf.Abs(card.rect.width/card.rect.height-1.5f)<.001f,"frame aspect");foreach(var t in card.GetComponentsInChildren<TMPro.TextMeshProUGUI>()){t.ForceMeshUpdate();Req(t.font.HasCharacters(t.text)&&!t.isTextOverflowing,"Korean glyphs/text fits "+t.name+" "+h);}var cancel=(RectTransform)card.Find("Cancel");var confirm=(RectTransform)card.Find("Confirm");Req(Vector2.Distance(cancel.rect.size,confirm.rect.size)<.01f&&!World(cancel).Overlaps(World(confirm)),"buttons equal separated");camera.Render();RenderTexture.active=rt;tex=new Texture2D(1080,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1080,h),0,0);tex.Apply();File.WriteAllBytes("Validation/sprint103_quit_"+h+".png",tex.EncodeToPNG());results.Add("PASS responsive/ratio/Korean glyph/text/buttons "+h);}finally{canvas.renderMode=mode;canvas.worldCamera=wc;camera.targetTexture=target;camera.orthographic=ortho;camera.orthographicSize=size;RenderTexture.active=active;safe.anchorMin=amin;safe.anchorMax=amax;sa.enabled=enabled;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}}
 static Rect World(RectTransform r){var c=new Vector3[4];r.GetWorldCorners(c);return Rect.MinMaxRect(c[0].x,c[0].y,c[2].x,c[2].y);}
 static void Req(bool v,string why){count++;if(!v)throw new Exception(why);}
 static void Log(string m,string s,LogType type){if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors+=m+"\n";if(type==LogType.Warning)warnings+=m+"\n";}
 static void Finish(bool pass,string why){EditorApplication.update-=Check;Application.logMessageReceived-=Log;session?.LeaveForHome();RunSaveStore.Delete();foreach(var k in keys){if(saved.TryGetValue(k,out int value))PlayerPrefs.SetInt(k,value);else PlayerPrefs.DeleteKey(k);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint103_tests.txt",string.Join("\n",results)+"\nAssertions="+count+"\nWarnings="+warnings+"\n"+(pass?"SPRINT103_PASS":why));Debug.Log(pass?"SPRINT103_PASS":why);EditorApplication.Exit(pass?0:1);}
}
