using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using CosmicBlock.Core;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint94PlayProbe {
 static List<string> keys=new List<string>(),results=new List<string>();static Dictionary<string,int> saved=new Dictionary<string,int>();static int assertions,frames;static double start;static string errors="";static GameSession session;static GameFlowController flow;static PlanetRestorationView view;
 public static void Run(){keys.Add(PlanetSelection.Key);keys.Add(PlanetRestoration.VersionKey);keys.Add(GameSession.DefaultBestScoreKey);foreach(var d in PlanetDefinitions.All){keys.Add(d.EnergyKey);keys.Add(d.UnlockKey);}foreach(var k in keys){if(PlayerPrefs.HasKey(k))saved[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.SetInt(GameSession.DefaultBestScoreKey,15930);try{Domain();}catch(Exception e){Finish(false,e.ToString());return;}EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");start=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Domain(){Req(PlanetSelection.Current==1&&!PlanetDefinitions.IsUnlocked(2),"fresh default locked");Req(!PlanetSelection.Select(2)&&PlanetSelection.Current==1,"locked selection rejected");PlayerPrefs.SetInt(PlanetSelection.Key,99);Req(PlanetSelection.Current==1,"invalid id fallback");PlayerPrefs.SetInt(PlanetSelection.Key,2);Req(PlanetSelection.Current==1,"locked saved id fallback");PlayerPrefs.DeleteKey(PlanetSelection.Key);
 int[] e={0,299,300,799,800,1499,1500,2399,2400,2999,3000,3001};int[] stages={1,1,2,2,3,3,4,4,5,5,5,5};int[] required={300,300,500,500,700,700,900,900,600,600,600,600};for(int i=0;i<e.Length;i++){var m=new PlanetRestoration(PlanetRestoration.Planet02Key,PlanetRestoration.VersionKey,2);m.SetEnergy(e[i]);int total=Math.Min(e[i],3000);Req(m.CurrentEnergy==total&&m.Stage==stages[i]&&m.StageRequired==required[i],"p2 boundary "+e[i]);Req(m.StageEnergy==total-PlanetRestoration.StartForStage(stages[i],2),"local amount");Req(Mathf.Abs(m.OverallProgress-total/3000f)<.000001f&&m.Percent==(int)Math.Floor(total*100.0/3000),"overall "+e[i]);Req(m.StageName==(total>=2400&&total<3000?"최종 복원":PlanetRestoration.NameForStage(stages[i])),"p2 phase label");Req(m.IsRestored==(total==3000)&&m.SpriteStage==(total==3000?5:Math.Min(4,stages[i])),"completed sprite only at max");results.Add("P2 "+e[i]+" stage="+m.Stage+" sprite="+m.SpriteStage+" required="+m.StageRequired);}
 PlayerPrefs.SetInt(PlanetRestoration.Planet02Key,2000);Req(new PlanetRestoration(PlanetRestoration.Planet02Key,PlanetRestoration.VersionKey,2).CurrentEnergy==2000,"old2000 raw preserved incomplete");PlayerPrefs.SetInt(PlanetRestoration.Planet02Key,-10);Req(new PlanetRestoration(PlanetRestoration.Planet02Key,PlanetRestoration.VersionKey,2).CurrentEnergy==0,"negative clamp");PlayerPrefs.SetInt(PlanetRestoration.Planet02Key,0);PlayerPrefs.DeleteKey(PlanetDefinitions.Get(3).UnlockKey);foreach(var d in PlanetDefinitions.All)Req(d.Total==1500*(1<<(d.Id-1)),"central total");Req(!PlanetSelection.Select(3),"unprepared content never playable");}
 static void Check(){if(EditorApplication.timeSinceStartup-start>220){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<35)return;EditorApplication.update-=Check;session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();view=UnityEngine.Object.FindAnyObjectByType<PlanetRestorationView>();session.StartCoroutine(Tests());}
 static IEnumerator Tests(){var body=Body();while(true){object value;try{if(!body.MoveNext())break;value=body.Current;}catch(Exception e){Finish(false,e.ToString());yield break;}yield return value;}Finish(errors.Length==0,errors);}
 static IEnumerator Body(){Req(flow.Screen==FlowScreen.Home,"cold Home");flow.ShowCollection();var c=flow.CollectionView;c.Next();Req(!c.CanSelect&&!c.Choose()&&PlanetSelection.Current==1,"locked collection selection");Req(c.HeroSprite==PlanetArtCatalog.Current.lockedPlanet&&c.transform.Find("Hero/HeroLock").gameObject.activeSelf,"common locked hero");c.GoBack();flow.StartNewRun();session.DebugSetPlanetEnergy(1490);session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3)&&session.Restoration.CurrentEnergy==1500,"p1 immediate completion save");yield return new WaitForSecondsRealtime(5.5f);Req(session.Restoration.LastUnlockedPlanetId==2,"first unlock event");Req(((Text)typeof(PlanetRestorationView).GetField("completionText",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(view)).text.Contains("크리스탈리아 해금"),"unlock feedback text");Req(session.State==GameState.Playing&&session.Score>0&&PlanetDefinitions.IsUnlocked(2),"p1 complete run maintained unlock2");flow.ShowHome();flow.ShowCollection();c.Next();Req(c.CanSelect&&c.Choose()&&flow.Screen==FlowScreen.Home&&PlanetSelection.Current==2,"choose2 returns HOME");flow.StartNewRun();Req(session.Restoration.PlanetId==2&&session.Restoration.CurrentEnergy==0&&session.Score==0,"selected2 playing");flow.ShowHome();var dev=UnityEngine.Object.FindAnyObjectByType<PlanetDebugPanel>();dev.Toggle();var presets=(Button[])typeof(PlanetDebugPanel).GetField("presetButtons",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(dev);int[] qa={0,290,790,1490,2990};for(int i=1;i<5;i++)Req(presets[i].GetComponentInChildren<Text>().text.Contains(qa[i].ToString()),"P2 QA label matches actual preset");dev.Close();flow.StartNewRun();
 foreach(int total in new[]{0,299,300,799,800,1499,1500,2399,2400,2999,3000}){session.DebugSetPlanetEnergy(total);Req(view.PresentedEnergy==total&&Mathf.Abs(view.ProgressFill-total/3000f)<.00001f&&Mathf.Abs(view.ImageFillAmount-total/3000f)<.00001f,"actual p2 fills "+total);var image=(Image)typeof(PlanetRestorationView).GetField("currentImage",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(view);Req(image.sprite==PlanetArtCatalog.Current.Sprite(2,session.Restoration.SpriteStage),"actual p2 sprite "+total);Req(view.transform.Find("Title").GetComponent<Text>().text.Contains("크리스탈리아"),"p2 HUD name");}
 foreach(int before in new[]{299,799,1499,2399,2999}){session.DebugSetPlanetEnergy(before);session.DebugPrepareNextRow();int count=view.CompletionPlayCount;Req(session.TryPlacePiece(session.Slots[0],3,3),"p2 boundary place");int after=Math.Min(3000,before+10);Req(session.Restoration.CurrentEnergy==after&&PlayerPrefs.GetInt(PlanetRestoration.DefaultKey)==1500,"p2 only award saved");Req(view.PresentedEnergy==before,"display delayed");float deadline=Time.unscaledTime+8;while(!view.TransitionActive&&Time.unscaledTime<deadline)yield return null;Req(view.TransitionActive,"boundary cinematic starts");var priorImage=(Image)typeof(PlanetRestorationView).GetField("currentImage",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(view);Req(priorImage.sprite==PlanetArtCatalog.Current.Sprite(2,PlanetDefinitions.Get(2).SpriteStage(before)),"HUD prior sprite until transition ends");yield return new WaitForSecondsRealtime(2.5f);Req(view.PresentedEnergy==after&&view.CompletionPlayCount==count+1&&session.State==GameState.Playing,"p2 transition once/run maintained");}
 Req(!PlanetSelection.Select(3),"complete2 unready3 rejected");int completedCount=view.CompletionPlayCount;session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"complete planet score play");session.DebugCompleteTurnForProbe();Req(session.Restoration.CurrentEnergy==3000&&view.CompletionPlayCount==completedCount,"no overflow/repeated completion");session.Retry();Req(session.Score==0&&session.Restoration.CurrentEnergy==3000&&session.BestScore==15930,"retry globalbest/progress");flow.ShowHome();flow.ShowCollection();c.Previous();Req(c.Choose()&&PlanetSelection.Current==1,"return completed1");flow.StartNewRun();Req(session.Restoration.IsRestored&&session.HasPlaceableRemainingBlock(),"completed1 playable");Req(PlayerPrefs.GetInt(PlanetRestoration.Planet02Key)==3000,"p2 survives switch");Req(new PlanetRestoration(PlanetRestoration.Planet02Key,PlanetRestoration.VersionKey,2).IsRestored,"p2 reload completion");flow.ShowHome();flow.ShowCollection();flow.CollectionView.SelectPlanet(1);Req(flow.CollectionView.Choose(),"reselect2");flow.StartNewRun();session.DebugSetPlanetEnergy(2995);session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3)&&session.Restoration.CurrentEnergy==3000,"partial5 actual reward clamp");yield return new WaitForSecondsRealtime(5.5f);Req(((Text)typeof(PlanetRestorationView).GetField("awardText",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(view)).text=="별빛 +5","partial actual reward shown");
 session.DebugSetPlanetEnergy(100);session.DebugPrepareCross();Req(session.TryPlacePiece(session.Slots[0],3,3),"p2 cross");session.DebugCompleteTurnForProbe();Req(session.Restoration.CurrentEnergy==125&&session.Score==260&&session.LastClear.UniqueClearedCells.Count==15,"cross single award/score/intersection");session.Retry();typeof(GameSession).GetMethod("DebugSetShapes",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(session,new object[]{CosmicBlock.Blocks.BlockCatalog.Shapes[4]});for(int y=0;y<3;y++)for(int x=0;x<8;x++)if(x!=3)session.Model.SetOccupied(x,y,true);Req(session.TryPlacePiece(session.Slots[0],3,0),"three rows");session.DebugCompleteTurnForProbe();Req(session.Restoration.CurrentEnergy==170&&session.Score==480&&session.LastClear.LineCount==3,"three rows unchanged45/450");session.DebugPrepareCross();Req(session.TryPlacePiece(session.Slots[0],3,3)&&session.Restoration.CurrentEnergy==195,"cancel durable award");flow.RequestHome();flow.ConfirmHome();flow.StartNewRun();yield return new WaitForSecondsRealtime(2);Req(session.Restoration.CurrentEnergy==195&&session.Score==0&&session.State==GameState.Playing&&!view.FeedbackActive,"fastHome no double callback");session.DebugForceGameOver();Req(session.State==GameState.GameOver,"p2 real gameover");var hud=UnityEngine.Object.FindAnyObjectByType<GameHud>();var finalText=(Text)typeof(GameHud).GetField("finalScoreText",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(hud);Req(finalText.text.Contains("행성 02 · 크리스탈리아")&&!finalText.text.Contains("푸른 별"),"P2 GameOver planet context");session.Retry();Req(session.State==GameState.Playing&&session.Restoration.CurrentEnergy==195,"p2 retry retained");session.DebugSetScore(15925);session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"p2 global record");session.DebugCompleteTurnForProbe();Req(session.BestScore==16035,"p2 global best improves");flow.ShowHome();flow.ShowCollection();flow.CollectionView.SelectPlanet(0);Req(flow.CollectionView.Choose(),"choose1 preserves globalBest");flow.StartNewRun();Req(session.BestScore==16035&&session.Score==0&&PlayerPrefs.GetInt(PlanetRestoration.Planet02Key)==205,"switch shared best and p2 save");
 results.Add("PASS selection/save/boundaries/actual sprites and fills/durable award/Run continuation/retry/cross/three-line/GameOver/fastHome/globalBest");}
 static void Req(bool pass,string reason){assertions++;if(!pass)throw new Exception(reason);}
 static void Log(string m,string s,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors+=m+"\n";}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;Application.logMessageReceived-=Log;foreach(var k in keys){if(saved.TryGetValue(k,out int value))PlayerPrefs.SetInt(k,value);else PlayerPrefs.DeleteKey(k);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint94_tests.txt",string.Join("\n",results)+"\nAssertions="+assertions+"\n"+(pass?"SPRINT94_PASS":failure));if(pass)Debug.Log("SPRINT94_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
