using System;using System.Collections.Generic;using System.IO;using CosmicBlock.Core;using CosmicBlock.UI;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
public static class Sprint72UiPlayProbe{
 static double started;static int frames,oldEnergy,oldVersion;static bool hadEnergy,hadVersion;static string errors="";static readonly List<string> results=new List<string>();static GameSession session;static GameFlowController flow;static Transform safe,home;
 public static void Run(){hadEnergy=PlayerPrefs.HasKey(PlanetRestoration.DefaultKey);hadVersion=PlayerPrefs.HasKey(PlanetRestoration.VersionKey);oldEnergy=PlayerPrefs.GetInt(PlanetRestoration.DefaultKey,0);oldVersion=PlayerPrefs.GetInt(PlanetRestoration.VersionKey,0);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,0);PlayerPrefs.SetInt(PlanetRestoration.VersionKey,PlanetRestoration.CurrentVersion);PlayerPrefs.Save();EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>180){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<30)return;try{session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();safe=GameObject.Find("GameCanvas").transform.Find("SafeArea");home=safe.Find("HomeRoot");Req(flow.Screen==FlowScreen.Home,"HOME start");Req(ImageAt(home,"TitleArea/Title").sprite.name=="home_title_starlight_block","branding");Req(ImageAt(home,"MainActions/GameStartButton").sprite.name=="home_play_button","image theme");int[] energies={0,20,50,90,400};int[] percents={0,20,50,90,100};float[] fills={0,.2f,.5f,.9f,1};for(int i=0;i<energies.Length;i++){session.DebugSetPlanetEnergy(energies[i]);flow.RefreshHome();Req(home.Find("EnergyArea")==null&&ImageAt(home,"HeroArea/HeroPlanet").sprite.name=="home_planet_hero","final HOME invariant "+energies[i]);}results.Add("PASS HOME image branding and stage-local progress 0/20/50/90/100.");Capture("home",1080,1920);Capture("home_tall",1080,2400);Capture("home_short",1080,1440);home.Find("MainActions/GameStartButton").GetComponent<Button>().onClick.Invoke();Req(flow.Screen==FlowScreen.Game,"PLAY");Req(TextAt(safe,"Title").text=="별빛 블록"&&TextAt(safe,"ScorePlaceholder").text.Contains("최고")&&TextAt(safe,"ScorePlaceholder").text.Contains("점수"),"game title score Korean");Req(TextAt(safe,"PlanetRestoration/Title").text=="행성 01 · 푸른 별"&&TextAt(safe,"PlanetRestoration/Stage").text.Contains("복원")&&TextAt(safe,"PlanetRestoration/Energy").text.StartsWith("에너지"),"planet Korean");Req(TextAt(safe,"PlayingHomeButton/Text").text=="홈","home Korean");Req(GameObject.Find("ComboText")==null,"no persistent combo");Capture("game",1080,1920);Capture("game_tall",1080,2400);Capture("game_short",1080,1440);flow.RequestHome();Req(flow.HomeConfirmVisible&&TextAt(safe,"ExitConfirm/Card/Question").text=="게임을 종료하고 홈으로 이동할까요?","home popup");Req(ImageAt(safe,"ExitConfirm/Card").type==Image.Type.Sliced,"popup shared style");flow.CancelHome();Req(!flow.HomeConfirmVisible,"popup cancel");results.Add("PASS GAME Korean HUD, shared popup style, Combo popup-only contract, HOME confirmation.");Req(errors.Length==0,"runtime errors "+errors);Finish(true,"");}catch(Exception e){Finish(false,e.ToString());}}
 static void Capture(string name,int width,int height){var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var camera=Camera.main;var sr=safe as RectTransform;var mode=canvas.renderMode;var wc=canvas.worldCamera;var target=camera.targetTexture;bool ortho=camera.orthographic;float os=camera.orthographicSize;var active=RenderTexture.active;var rt=new RenderTexture(width,height,24);Texture2D tex=null;try{rt.Create();camera.targetTexture=rt;camera.orthographic=true;camera.orthographicSize=height/2f;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=camera;canvas.planeDistance=10;sr.anchorMin=Vector2.zero;sr.anchorMax=Vector2.one;sr.offsetMin=sr.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();camera.Render();RenderTexture.active=rt;tex=new Texture2D(width,height,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,width,height),0,0);tex.Apply();Directory.CreateDirectory("Validation");File.WriteAllBytes("Validation/sprint72_"+name+".png",tex.EncodeToPNG());}finally{canvas.renderMode=mode;canvas.worldCamera=wc;camera.targetTexture=target;camera.orthographic=ortho;camera.orthographicSize=os;RenderTexture.active=active;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);sr.GetComponent<SafeArea>().SendMessage("Apply");}}
 static Text TextAt(Transform root,string path){var t=root.Find(path);if(t==null)throw new Exception("missing "+path);return t.GetComponent<Text>();}static Image ImageAt(Transform root,string path){var t=root.Find(path);if(t==null)throw new Exception("missing "+path);return t.GetComponent<Image>();}static void Req(bool v,string m){if(!v)throw new Exception("Sprint 7.2 test failed: "+m);}static void Log(string m,string s,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors+=m+"\n";}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;Application.logMessageReceived-=Log;if(hadEnergy)PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,oldEnergy);else PlayerPrefs.DeleteKey(PlanetRestoration.DefaultKey);if(hadVersion)PlayerPrefs.SetInt(PlanetRestoration.VersionKey,oldVersion);else PlayerPrefs.DeleteKey(PlanetRestoration.VersionKey);PlayerPrefs.Save();Directory.CreateDirectory("Validation");File.WriteAllText("Validation/sprint72.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT72_UI_PASS":failure)+"\n");if(pass)Debug.Log("SPRINT72_UI_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}


