using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using CosmicBlock.Core;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint10VisualProbe {
 static Dictionary<string,int> saved=new Dictionary<string,int>();static List<string> keys=new List<string>(),results=new List<string>();static int frames;static double start;static GameSession session;static GameFlowController flow;
 public static void Run(){keys.Add(PlanetSelection.Key);keys.Add(PlanetRestoration.VersionKey);keys.Add(GameSession.DefaultBestScoreKey);foreach(var d in PlanetDefinitions.All){keys.Add(d.EnergyKey);keys.Add(d.UnlockKey);}foreach(var k in keys){if(PlayerPrefs.HasKey(k))saved[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,1500);PlayerPrefs.SetInt(PlanetRestoration.Planet02UnlockKey,1);PlayerPrefs.SetInt(GameSession.DefaultBestScoreKey,15930);EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");start=EditorApplication.timeSinceStartup;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-start>240){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<35)return;EditorApplication.update-=Check;try{
 RunSaveStore.PathOverride=Path.GetFullPath("Validation/sprint10-visual-run.json");RunSaveStore.Delete();session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();
 foreach(int height in new[]{1920,2400,1440}){
  PlayerPrefs.SetInt(PlanetDefinitions.Get(3).UnlockKey,0);PlayerPrefs.SetInt(PlanetDefinitions.Get(2).EnergyKey,0);flow.ShowHome();flow.ShowCollection();flow.CollectionView.SelectPlanet(2);Capture(height,"locked3",()=>flow.CollectionView.SelectPlanet(2));
  foreach(var d in PlanetDefinitions.All){PlayerPrefs.SetInt(d.UnlockKey,1);PlayerPrefs.SetInt(d.EnergyKey,d.Total);}PlayerPrefs.Save();
  for(int id=1;id<=5;id++){var d=PlanetDefinitions.Get(id);PlanetSelection.Select(id);flow.StartNewRun();session.DebugSetPlanetEnergy(PlanetRestoration.StartForStage(3,id));
   Capture(height,"game"+id+"_stage3",()=>UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>().RefreshVisual());
   flow.ShowHome();Capture(height,"home"+id,()=>{flow.HomeRoot.GetComponent<HomeFinalLayout>().Apply();flow.RefreshHome();});
   flow.ShowCollection();flow.CollectionView.SelectPlanet(id-1);Capture(height,"collection"+id+"_stage3",()=>flow.CollectionView.SelectPlanet(id-1));
   new PlanetRestoration(d.EnergyKey,PlanetRestoration.VersionKey,id).SetEnergy(d.Total-1);flow.CollectionView.SelectPlanet(id-1);Req(!flow.CollectionView.Status.Contains("복원 완료"),"stage5 still incomplete");Capture(height,"collection"+id+"_stage5",()=>flow.CollectionView.SelectPlanet(id-1));
   flow.CollectionView.GoBack();
  }
 }Finish(true,"");}catch(Exception e){Finish(false,e.ToString());}}
 static void Capture(int h,string tag,Action refresh){int w=1080;var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var safe=(RectTransform)canvas.transform.Find("SafeArea");var area=safe.GetComponent<SafeArea>();var cam=Camera.main;var oldMode=canvas.renderMode;var oldCamera=canvas.worldCamera;var oldTarget=cam.targetTexture;var oldActive=RenderTexture.active;var oldMin=safe.anchorMin;var oldMax=safe.anchorMax;bool oldEnabled=area.enabled;var rt=new RenderTexture(w,h,24);Texture2D tex=null;var backgrounds=new List<Tuple<AspectFillBackground,Vector2,Vector2,bool>>();try{area.enabled=false;rt.Create();cam.targetTexture=rt;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=10;safe.anchorMin=h==2400?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=h==2400?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();refresh();Canvas.ForceUpdateCanvases();if(flow.Screen==FlowScreen.Collection){var c=flow.CollectionView;var button=(RectTransform)c.transform.Find("SelectPlanet");Req(Inside(button,safe),"selection safe");var icon=(RectTransform)c.transform.Find("Hero/HeroLock");Req(icon.rect.width>0&&icon.rect.height>0,"lock rect valid");foreach(var text in c.GetComponentsInChildren<Text>())Req(text.cachedTextGenerator.characterCountVisible>=text.text.Replace("\n","").Length,"clipped "+tag+" "+h+" "+text.name);if(c.CanSelect){Req(Inside((RectTransform)c.transform.Find("Hero"),safe),"hero inside safe");var track=(RectTransform)c.transform.Find("ProgressFrameArea/ProgressFrame/Progress");var fill=(RectTransform)track.Find("Fill");Req(Mathf.Abs(fill.rect.width/track.rect.width-c.Progress)<.0001f,"actual rendered bar width");}Req(c.transform.Find("Previous/Icon").GetComponent<Image>().preserveAspect&&c.transform.Find("Next/Icon").GetComponent<Image>().preserveAspect,"navigation aspect");}
 if(flow.Screen==FlowScreen.Game){foreach(string path in new[]{"Board","PlanetRestoration","BlockArea","GameScorePresentation/CurrentScore"})Req(Inside((RectTransform)safe.Find(path),safe),"game safe "+path);var v=UnityEngine.Object.FindAnyObjectByType<PlanetRestorationView>();foreach(string field in new[]{"currentImage"}){var image=(Image)typeof(PlanetRestorationView).GetField(field,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(v);Req(image.preserveAspect&&image.sprite!=null,"HUD aspect");}}
 foreach(var bg in canvas.GetComponentsInChildren<AspectFillBackground>(true)){var r=(RectTransform)bg.transform;backgrounds.Add(Tuple.Create(bg,r.sizeDelta,r.anchoredPosition,bg.enabled));bg.enabled=false;var reference=new SerializedObject(bg).FindProperty("referenceSize").vector2Value;var full=(RectTransform)canvas.transform;r.sizeDelta=reference*Mathf.Max(full.rect.width/reference.x,full.rect.height/reference.y);r.anchoredPosition=((RectTransform)r.parent).InverseTransformPoint(full.TransformPoint(full.rect.center));}Canvas.ForceUpdateCanvases();
 cam.Render();RenderTexture.active=rt;tex=new Texture2D(w,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,w,h),0,0);tex.Apply();File.WriteAllBytes("Validation/sprint10_"+tag+"_"+h+".png",tex.EncodeToPNG());results.Add("PASS "+tag+" "+h);
 }finally{foreach(var bg in backgrounds){var r=(RectTransform)bg.Item1.transform;r.sizeDelta=bg.Item2;r.anchoredPosition=bg.Item3;bg.Item1.enabled=bg.Item4;}canvas.renderMode=oldMode;canvas.worldCamera=oldCamera;cam.targetTexture=oldTarget;RenderTexture.active=oldActive;safe.anchorMin=oldMin;safe.anchorMax=oldMax;area.enabled=oldEnabled;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}
 static bool Inside(RectTransform child,RectTransform parent){var c=new Vector3[4];child.GetWorldCorners(c);foreach(var p in c)if(!parent.rect.Contains(parent.InverseTransformPoint(p)))return false;return true;}
 static void Req(bool b,string m){if(!b)throw new Exception(m);}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;if(session!=null)session.LeaveForHome();RunSaveStore.Delete();foreach(var k in keys){if(saved.TryGetValue(k,out int v))PlayerPrefs.SetInt(k,v);else PlayerPrefs.DeleteKey(k);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint10_visual_tests.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT10_VISUAL_PASS":failure));if(pass)Debug.Log("SPRINT10_VISUAL_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
