using System;
using System.Collections.Generic;
using System.IO;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint93HudOverlapProbe {
 static bool overlapFound;static int frames;static double started;static List<string> results=new List<string>();
 public static void Run(){EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");started=EditorApplication.timeSinceStartup;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>240){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<30)return;EditorApplication.update-=Check;try{UnityEngine.Object.FindAnyObjectByType<GameFlowController>().Play();var visual=UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>();foreach(var size in new[]{new[]{1080,1920},new[]{1080,2400},new[]{1080,1440}})foreach(int score in new[]{999999,1000000,9999999,int.MaxValue})foreach(int best in new[]{15930,int.MaxValue})Measure(visual,size[0],size[1],score,best);Finish(!overlapFound,overlapFound?"visible overlap found":"");}catch(Exception e){Finish(false,e.ToString());}}
 static void Measure(GameVisualPresentation visual,int w,int h,int score,int best){var canvas=visual.GetComponentInParent<Canvas>();var safe=(RectTransform)canvas.transform.Find("SafeArea");var area=safe.GetComponent<SafeArea>();var camera=Camera.main;bool oldEnabled=area.enabled;var oldMin=safe.anchorMin;var oldMax=safe.anchorMax;var oldMode=canvas.renderMode;var oldCamera=canvas.worldCamera;var oldTarget=camera.targetTexture;var oldActive=RenderTexture.active;var oldFlags=camera.clearFlags;var oldColor=camera.backgroundColor;var graphics=canvas.GetComponentsInChildren<Graphic>(true);var enabled=new bool[graphics.Length];var frame=visual.transform.Find("BestFrameArea");var currentGraphics=visual.ScoreText.GetComponentsInChildren<Graphic>(true);var rt=new RenderTexture(w,h,24);int top=450;var tex=new Texture2D(w,top,TextureFormat.RGB24,false);try{area.enabled=false;rt.Create();camera.targetTexture=rt;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=camera;canvas.planeDistance=10;safe.anchorMin=h==2400?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=h==2400?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();visual.Layout();Canvas.ForceUpdateCanvases();visual.RenderValues(score,best);visual.ScoreText.ForceMeshUpdate();visual.BestText.ForceMeshUpdate();camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=Color.black;
  for(int i=0;i<graphics.Length;i++){enabled[i]=graphics[i].enabled;graphics[i].enabled=false;}foreach(var g in currentGraphics)g.enabled=true;camera.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,h-top,w,top),0,0);tex.Apply();var scorePixels=tex.GetPixels32();foreach(var g in currentGraphics)g.enabled=false;foreach(var g in frame.GetComponentsInChildren<Graphic>(true))g.enabled=true;camera.Render();tex.ReadPixels(new Rect(0,h-top,w,top),0,0);tex.Apply();var bestPixels=tex.GetPixels32();int overlap=0;for(int i=0;i<scorePixels.Length;i++)if(Bright(scorePixels[i])&&Bright(bestPixels[i]))overlap++;results.Add(w+"x"+h+" score="+score+" best="+best+" overlapPixels="+overlap);if(overlap!=0)overlapFound=true;
  for(int i=0;i<graphics.Length;i++)graphics[i].enabled=enabled[i];camera.Render();tex.ReadPixels(new Rect(0,h-top,w,top),0,0);tex.Apply();File.WriteAllBytes("Validation/sprint93_header_"+h+"_"+score+"_"+best+".png",tex.EncodeToPNG());
 }finally{for(int i=0;i<graphics.Length;i++)graphics[i].enabled=enabled[i];camera.targetTexture=oldTarget;camera.clearFlags=oldFlags;camera.backgroundColor=oldColor;canvas.renderMode=oldMode;canvas.worldCamera=oldCamera;safe.anchorMin=oldMin;safe.anchorMax=oldMax;area.enabled=oldEnabled;RenderTexture.active=oldActive;rt.Release();UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(tex);}}
 static bool Bright(Color32 c)=>Mathf.Max(c.r,Mathf.Max(c.g,c.b))>=20;
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;File.WriteAllText("Validation/sprint93_header_overlap.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT93_HEADER_PASS":failure));if(pass)Debug.Log("SPRINT93_HEADER_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
