using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using CosmicBlock.Core;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using CosmicBlock.Blocks;
using CosmicBlock.Board;
using System.Reflection;
public static class Sprint102PlayProbe {
 static readonly Dictionary<string,int> backup=new Dictionary<string,int>();static readonly List<string> keys=new List<string>();static readonly List<string> results=new List<string>();static GameSession game;static GameFlowController flow;static PlanetCompletionPopup popup;static double began;static int frames;static string errors="";static bool expectedWriteFailure;static int expectedWarnings;
 public static void Run(){keys.Add(PlanetSelection.Key);keys.Add(PlanetRestoration.VersionKey);keys.Add(GameSession.DefaultBestScoreKey);foreach(var d in PlanetDefinitions.All){keys.Add(d.EnergyKey);keys.Add(d.UnlockKey);keys.Add(PlanetCompletionNotice.Key(d.Id));}foreach(var k in keys){if(PlayerPrefs.HasKey(k))backup[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.SetInt(GameSession.DefaultBestScoreKey,19000);foreach(var d in PlanetDefinitions.All)PlayerPrefs.SetInt(d.UnlockKey,1);PlayerPrefs.Save();EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");began=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Log(string m,string s,LogType t){if(expectedWriteFailure&&t==LogType.Warning&&m.StartsWith("Run save could not be written:")){expectedWarnings++;return;}if(t==LogType.Error||t==LogType.Exception||t==LogType.Warning)errors+=m+"\n";}
 static void Check(){if(EditorApplication.timeSinceStartup-began>240){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<30)return;EditorApplication.update-=Check;RunSaveStore.PathOverride=Path.GetFullPath("Validation/sprint102-run.json");RunSaveStore.Delete();game=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();popup=UnityEngine.Object.FindAnyObjectByType<PlanetCompletionPopup>();game.StartCoroutine(Guard());}
 static IEnumerator Guard(){var e=Body();while(true){object v;try{if(!e.MoveNext())break;v=e.Current;}catch(Exception x){Finish(false,x.ToString());yield break;}yield return v;}Finish(errors.Length==0,errors);}
 static IEnumerator Body(){
  var ui=UnityEngine.Object.FindAnyObjectByType<GameAssistView>();var board=UnityEngine.Object.FindAnyObjectByType<BoardView>();Req(ui!=null,"one assist view");flow.StartNewRun();Shapes(BlockCatalog.Shapes[0]);Req(game.TryPlacePiece(game.Slots[0],0,0),"ordinary placement");var before=Snapshot();var consumedShape=game.Slots[0].Shape;int best=game.BestScore;ui.RefreshButton.onClick.Invoke();Req(game.RefreshUses==1&&game.Slots[0].IsConsumed&&game.Slots[0].Shape==consumedShape,"refresh keeps consumed slot");Req(game.Slots[1].Shape!=BlockCatalog.Shapes[0]&&game.Slots[2].Shape!=BlockCatalog.Shapes[0],"unused shapes replaced");Req(SameBoard(before,Snapshot())&&game.Score==before.score&&game.Combo==before.combo&&game.Restoration.CurrentEnergy==before.planetEnergy&&game.BestScore==best,"refresh gameplay unchanged");Req(game.HasPlaceableRemainingBlock()&&!game.TryRefreshBlocks(),"fits/free1/double press");Req(RunSaveStore.Load().refreshUses==1,"refresh saved immediately");flow.ShowHome();flow.Play();Req(game.RefreshUses==1&&game.Slots[0].IsConsumed,"refresh resume");results.Add("PASS refresh consumed slots/score/combo/BEST/energy/board/limit/save/resume");
  flow.StartNewRun();Shapes(BlockCatalog.Shapes[2]);for(int y=0;y<8;y++)for(int x=0;x<8;x++)game.Model.SetOccupied(x,y,(x+y)%2==1);Req(game.TryRefreshBlocks()&&game.HasPlaceableRemainingBlock()&&game.State==GameState.Playing,"guaranteed fit on restrictive checkerboard");results.Add("PASS guaranteed usable refresh shape");
  flow.StartNewRun();game.DebugPrepareNextRow();before=Snapshot();var timer=System.Diagnostics.Stopwatch.StartNew();ui.HintButton.onClick.Invoke();timer.Stop();Req(game.HintUses==1&&game.HintVisible&&game.ActiveHint.Lines==1&&game.ActiveHint.Anchor==new Vector2Int(3,3),"immediate clear priority");Req(game.Model.CanPlace(game.ActiveHint.Shape,3,3)&&ui.HighlightCount==1,"legal visible cells");Req(SameBoard(before,Snapshot())&&game.Score==before.score&&game.Combo==before.combo&&game.Restoration.CurrentEnergy==before.planetEnergy&&game.BestScore==best,"hint never places/scores/awards");Req(RunSaveStore.Load().hintUses==1&&!game.TryHint()&&game.HintUses==1,"hint save/double press");results.Add("PASS deterministic legal line priority/no mutations/hint time ms="+timer.ElapsedMilliseconds);
  var handler=game.Slots[0].GetComponent<BlockDragHandler>();handler.OnBeginDrag(new PointerEventData(EventSystem.current){pointerId=7,button=PointerEventData.InputButton.Left,position=RectTransformUtility.WorldToScreenPoint(null,game.Slots[0].Rect.position)});Req(handler.IsDragging&&!game.HintVisible&&ui.HighlightCount==0,"real drag clears hint");Req(!game.TryRefreshBlocks()&&!game.TryHint(),"drag blocks assists");handler.CancelDrag();yield return new WaitForSecondsRealtime(.3f);
  Req(game.TryHint()&&game.HintUses==2,"second hint");yield return new WaitForSecondsRealtime(4.1f);Req(!game.HintVisible&&ui.HighlightCount==0,"four second cleanup");Req(game.TryHint()&&game.HintUses==3,"third hint");game.ClearHint();yield return new WaitForSecondsRealtime(.3f);Req(!game.TryHint()&&game.HintUses==3&&!ui.HintButton.interactable,"free3 limit");flow.ShowHome();flow.Play();Req(game.HintUses==3&&!game.HintVisible,"hint resume count only");results.Add("PASS drag cleanup/4sec/hint3/disabled/resume");
  var legacy=Snapshot();legacy.refreshUses=legacy.hintUses=0;string json=JsonUtility.ToJson(legacy);json=System.Text.RegularExpressions.Regex.Replace(json,"\"(?:refreshUses|hintUses|refreshAdUses|hintAdUses|confirmedRewardIds)\":(?:[0-9]+|\\[\\]|null),?","");flow.ShowHome();File.WriteAllText(RunSaveStore.SavePath,json);flow.Play();Req(game.RefreshUses==0&&game.HintUses==0&&SameBoard(legacy,Snapshot())&&game.Score==legacy.score,"legacy missing fields defaults0");results.Add("PASS legacy save compatibility");
  flow.StartNewRun();Req(game.RefreshUses==0&&game.HintUses==0,"new run resets");flow.RequestHome();Req(!game.TryHint()&&!game.TryRefreshBlocks(),"home confirm blocked");flow.CancelHome();game.ModalInputBlocked=true;Req(!game.TryHint()&&!game.TryRefreshBlocks(),"completion modal blocked");game.ModalInputBlocked=false;flow.ShowHome();Req(!game.TryHint()&&!game.TryRefreshBlocks(),"home blocked");flow.Play();game.DebugPrepareNextRow();Req(game.TryPlacePiece(game.Slots[0],3,3),"clear resolving");Req(!game.TryHint()&&!game.TryRefreshBlocks(),"clear timeline blocked");game.DebugCompleteTurnForProbe();
  flow.StartNewRun();foreach(var piece in game.Slots)piece.Consume();Req(!game.TryHint()&&!game.TryRefreshBlocks()&&game.HintUses==0&&game.RefreshUses==0,"no unused no cost");flow.StartNewRun();for(int y=0;y<8;y++)for(int x=0;x<8;x++)game.Model.SetOccupied(x,y,true);Req(!game.TryHint()&&game.HintUses==0,"no valid hint no charge");Req(!game.TryRefreshBlocks()&&game.RefreshUses==0&&game.State==GameState.GameOver,"no catalog fits handled");Req(!game.TryHint()&&!game.TryRefreshBlocks(),"gameover blocked");game.Retry();Req(game.State==GameState.Playing&&game.RefreshUses==0&&game.HintUses==0,"retry resets");results.Add("PASS modal/home/clear/no unused/no fit/GameOver/Retry");
  flow.StartNewRun();game.DebugPrepareNextRow();Req(game.TryHint(),"hint before background");game.SendMessage("OnApplicationPause",true);Req(!game.HintVisible&&RunSaveStore.Load().hintUses==1,"pause saves cost clears visuals");Req(!game.TryHint()&&!game.TryRefreshBlocks(),"paused input blocked");game.SendMessage("OnApplicationPause",false);flow.ShowHome();flow.Play();Req(game.HintUses==1&&!game.HintVisible,"pause restore");results.Add("PASS background consistent save/visual cleanup");
 }
 static RunSnapshot Snapshot()=>(RunSnapshot)typeof(GameSession).GetMethod("Capture",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(game,new object[]{false});
 static void Shapes(BlockShape shape)=>typeof(GameSession).GetMethod("DebugSetShapes",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(game,new object[]{shape});
 static bool SameBoard(RunSnapshot a,RunSnapshot b){for(int i=0;i<64;i++)if(a.cells[i]!=b.cells[i])return false;return true;}
 static void Click(GameObject root,string name){root.transform.Find("Card/"+name).GetComponent<Button>().onClick.Invoke();}
 static void Req(bool ok,string m){if(!ok)throw new Exception(m);}
 static void Finish(bool pass,string reason){EditorApplication.update-=Check;Application.logMessageReceived-=Log;if(game!=null)game.LeaveForHome();RunSaveStore.Delete();foreach(var k in keys){if(backup.TryGetValue(k,out int v))PlayerPrefs.SetInt(k,v);else PlayerPrefs.DeleteKey(k);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint102_play_tests.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT102_PASS":reason));if(pass)Debug.Log("SPRINT102_PASS");else Debug.LogError(reason);EditorApplication.Exit(pass?0:1);}
}
