using System;
using CosmicBlock.Core;
using CosmicBlock.UI;
using CosmicBlock.Board;
using UnityEditor;
using UnityEngine;
public static class Sprint102Builder {
 public static void RepairSpriteData(){foreach(string name in new[]{"game_block_refresh_button","game_hint_button"}){var t=(TextureImporter)AssetImporter.GetAtPath("Assets/Art/UI/Game/"+name+".png");t.textureShape=TextureImporterShape.Texture2D;t.textureType=TextureImporterType.Sprite;t.spriteImportMode=SpriteImportMode.Single;t.SaveAndReimport();}InspectSprites();}
 public static void InspectSprites(){var lines=new System.Collections.Generic.List<string>();foreach(string name in new[]{"game_block_refresh_button","game_hint_button"}){var sprite=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/UI/Game/"+name+".png");if(sprite==null){foreach(var asset in AssetDatabase.LoadAllAssetsAtPath("Assets/Art/UI/Game/"+name+".png"))if(asset is Sprite found){sprite=found;break;}}if(sprite==null)throw new Exception("Missing imported Sprite "+name+" objects="+string.Join(",",Array.ConvertAll(AssetDatabase.LoadAllAssetsAtPath("Assets/Art/UI/Game/"+name+".png"),o=>o.GetType().Name+":"+o.name)));AssetDatabase.TryGetGUIDAndLocalFileIdentifier(sprite,out string guid,out long id);lines.Add(name+","+guid+","+id);}System.IO.File.WriteAllLines("Validation/sprint102_sprite_ids.csv",lines);EditorApplication.Exit(0);}
 public static void Build(){foreach(string name in new[]{"game_block_refresh_button","game_hint_button"}){var t=AssetImporter.GetAtPath("Assets/Art/UI/Game/"+name+".png")as TextureImporter;if(t==null)throw new Exception("Missing "+name);t.textureShape=TextureImporterShape.Texture2D;t.textureType=TextureImporterType.Sprite;t.spriteImportMode=SpriteImportMode.Single;t.alphaSource=TextureImporterAlphaSource.FromInput;t.alphaIsTransparency=true;t.mipmapEnabled=false;t.wrapMode=TextureWrapMode.Clamp;t.filterMode=FilterMode.Bilinear;t.maxTextureSize=2048;t.textureCompression=TextureImporterCompression.Uncompressed;var settings=new TextureImporterSettings();t.ReadTextureSettings(settings);settings.spriteMeshType=SpriteMeshType.FullRect;t.SetTextureSettings(settings);var android=t.GetPlatformTextureSettings("Android");android.overridden=true;android.maxTextureSize=2048;android.format=TextureImporterFormat.ASTC_6x6;android.compressionQuality=100;t.SetPlatformTextureSettings(android);t.SaveAndReimport();}AssetDatabase.SaveAssets();Debug.Log("SPRINT102_IMPORT_PASS");RepairSpriteData();}
}
