using System;
using System.Collections.Generic;
using System.IO;
using CosmicBlock.Blocks;
using CosmicBlock.Board;
using CosmicBlock.Core;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;
public static class Sprint911GamePlayProbe {
 static double started;static int frames,count;static string errors="";static GameSession session;static GameFlowController flow;static BoardView board;static GameVisualPresentation visual;static RectTransform safe,layer;
 static readonly List<string> results=new List<string>();static readonly string[] keys={PlanetRestoration.DefaultKey,PlanetRestoration.VersionKey,GameSession.DefaultBestScoreKey};static readonly int[] saved=new int[3];static readonly bool[] had=new bool[3];
 public static void Run(){for(int i=0;i<3;i++){had[i]=PlayerPrefs.HasKey(keys[i]);saved[i]=PlayerPrefs.GetInt(keys[i]);}EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>180){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<40)return;try{
  session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();board=UnityEngine.Object.FindAnyObjectByType<BoardView>();visual=UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>();var canvas=GameObject.Find("GameCanvas").transform;safe=(RectTransform)canvas.Find("SafeArea");layer=(RectTransform)canvas.Find("DragLayer");Req(flow.Screen==FlowScreen.Home,"cold HOME");flow.Play();Req(flow.Screen==FlowScreen.Game&&session.Score==0&&session.Slots.Count==3,"HOME GAME clean run");session.DebugSetPlanetEnergy(400);Req(board.HasVisualSkin&&board.transform.childCount==64,"64 skinned cells");Req(safe.Find("PlayingHomeButton").GetComponent<Image>().sprite.name=="game_home_button"&&safe.Find("PlayingHomeButton/ThemeFill")==null,"HOME asset unobscured");Req(safe.Find("PlanetRestoration/StatusFrame").GetComponent<Image>().sprite.name=="game_planet_status_frame"&&safe.Find("PlanetRestoration/ThemeFill")==null,"status asset unobscured");Req(safe.Find("GameOverPanel").GetSiblingIndex()>safe.Find("PlanetRestoration").GetSiblingIndex()&&safe.Find("GameOverPanel").GetSiblingIndex()>safe.Find("GameScorePresentation").GetSiblingIndex(),"Game Over above game HUD");
  for(int i=0;i<64;i++)Req(board.transform.GetChild(i).GetComponent<Image>().sprite.name=="game_empty_cell","empty sprite "+i);
  var colors=new HashSet<string>();foreach(var shape in BlockCatalog.Shapes){session.Retry();var piece=session.Slots[0];piece.Initialize(shape,board,layer,session);colors.Add(piece.AppearanceSprite.name);var origin=piece.transform.parent;var slot=origin.GetComponent<SlotDragHandler>();var begin=new PointerEventData(EventSystem.current){pointerId=-1,position=Screen(origin.TransformPoint(((RectTransform)origin).rect.min+Vector2.one*10))};slot.OnBeginDrag(begin);Req(piece.GetComponent<BlockDragHandler>().IsDragging&&piece.DragHighlightActive,"slot edge begin "+shape.Id);var data=Data(piece,new Vector2Int(1,1));piece.GetComponent<BlockDragHandler>().OnDrag(data);Req(board.PreviewValid&&board.PreviewCount==shape.Cells.Count,"valid preview "+shape.Id);var sprite=piece.AppearanceSprite;piece.GetComponent<BlockDragHandler>().OnEndDrag(data);Req(piece.IsConsumed&&Sprint1Builder.Count(board.Model)==shape.Cells.Count,"placement "+shape.Id);foreach(var cell in shape.Cells)Req(board.transform.GetChild((1+cell.y)*8+1+cell.x).GetComponent<Image>().sprite==sprite,"placed palette "+shape.Id);Req(!slot.IsInteractable,"consumed slot inert");}
  foreach(var shape in BlockCatalog.Shapes){session.Retry();session.Slots[0].Initialize(shape,board,layer,session);Capture(1080,1920,"slot_"+shape.Id,false);Capture(1080,2400,"slot_tall_"+shape.Id,true);Capture(1080,1440,"slot_short_"+shape.Id,false);}
  Req(Mathf.Abs(board.SpriteVisualScale-1.2f)<.001f,"density configured");Req(colors.Count==3,"all three palette sprites used");results.Add("PASS all catalog shapes: slot-edge drag, gold highlight, preview, exact cell drop, matching palette and consumed input.");
  session.Retry();var invalid=session.Slots[0];invalid.Initialize(BlockCatalog.Shapes[0],board,layer,session);board.Model.SetOccupied(2,2,true);var handler=invalid.GetComponent<BlockDragHandler>();handler.OnBeginDrag(Data(invalid,new Vector2Int(2,2)));handler.OnDrag(Data(invalid,new Vector2Int(2,2)));Req(!board.PreviewValid,"invalid preview");string before=Sprint1Builder.Snapshot(board.Model);handler.OnEndDrag(Data(invalid,new Vector2Int(2,2)));Req(!invalid.IsConsumed&&before==Sprint1Builder.Snapshot(board.Model)&&board.PreviewCount==0,"invalid return inert");
  session.Retry();for(int i=0;i<3;i++){var p=session.Slots[i];p.Initialize(BlockCatalog.Shapes[0],board,layer,session);Req(session.TryPlacePiece(p,i*2,0),"three consumption "+i);}Req(session.BlockSetNumber==2&&!session.Slots[0].IsConsumed,"refill");
  session.Retry();session.DebugSetPlanetEnergy(110);Req(safe.Find("PlanetRestoration/Stage").GetComponent<Text>().enabled&&safe.Find("PlanetRestoration/Energy").GetComponent<Text>().enabled,"stage and starlight details visible");Req(visual.ScoreText.fontSizeMax==106,"large current score");Capture(1080,1920,"game_empty",false);session.Retry();for(int i=0;i<3;i++){var p=session.Slots[i];p.Initialize(BlockCatalog.Shapes[i==0?5:6],board,layer,session);Req(session.TryPlacePiece(p,1+i*2,2+i),"placed render fixture");}Capture(1080,1920,"game_9x16",false);Capture(1080,2400,"game_tall_safe",true);Capture(1080,1440,"game_short",false);Capture(1080,1920,"game_placed",false);Capture(1080,1920,"reference_1280",false,1280,15930);Capture(1080,1920,"drag_valid",false);Capture(1080,1920,"drag_invalid",false);Capture(1080,1920,"clear_feedback",false);session.ResetTransientFeedback();
  foreach(int value in new[]{999,15930,999999,9999999}){Canvas.ForceUpdateCanvases();visual.RenderValues(value,value);Req(FitsTmp(visual.ScoreText)&&FitsTmp(visual.BestText),"TMP score fit "+value);Capture(1080,1920,"best_"+value,false,value);}visual.RefreshVisual();
  int energy=session.Restoration.CurrentEnergy,best=session.BestScore;flow.RequestHome();flow.CancelHome();Req(flow.Screen==FlowScreen.Game,"home cancel");flow.RequestHome();flow.ConfirmHome();Req(flow.Screen==FlowScreen.Home&&session.Restoration.CurrentEnergy==energy&&session.BestScore==best,"home keeps save");flow.ShowCollection();flow.CollectionView.Next();Req(flow.CollectionView.PlanetIndex==1,"collection preserved");flow.CollectionView.GoBack();flow.Play();session.DebugForceGameOver();Req(session.State==GameState.GameOver,"gameover");Capture(1080,1920,"game_over",false);session.Retry();Req(session.State==GameState.Playing&&session.Score==0&&board.PreviewCount==0,"retry");
  Req(errors.Length==0,"runtime errors "+errors);results.Add("PASS TMP 999/15,930/999,999/9,999,999; invalid return, refill, HOME/Collection/GAME, saved values, Game Over and Retry.");Finish(true,"");
 }catch(Exception e){Finish(false,e.ToString());}}
 static void Capture(int w,int h,string name,bool inset,int displayValue=-1,int recordValue=-1){var canvas=safe.GetComponentInParent<Canvas>();var cam=Camera.main;var area=safe.GetComponent<SafeArea>();bool enabled=area.enabled;var mode=canvas.renderMode;var wc=canvas.worldCamera;var target=cam.targetTexture;bool ortho=cam.orthographic;float size=cam.orthographicSize;var active=RenderTexture.active;var min=safe.anchorMin;var max=safe.anchorMax;var omin=safe.offsetMin;var omax=safe.offsetMax;var rt=new RenderTexture(w,h,24);Texture2D tex=null;try{area.enabled=false;rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=h/2f;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=10;safe.anchorMin=inset?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=inset?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();visual.Layout();board.SendMessage("LateUpdate");Canvas.ForceUpdateCanvases();foreach(var p in session.Slots)p.FitSlot();visual.RefreshVisual();Canvas.ForceUpdateCanvases();if(displayValue>=0){visual.RenderValues(displayValue,recordValue>=0?recordValue:displayValue);Req(FitsTmp(visual.ScoreText)&&FitsTmp(visual.BestText),"rendered TMP bounds "+displayValue);}if(name=="drag_valid"||name=="drag_invalid"){session.Retry();var p=session.Slots[0];p.Initialize(BlockCatalog.Shapes[2],board,layer,session);if(name=="drag_invalid")board.Model.SetOccupied(2,2,true);p.GetComponent<BlockDragHandler>().OnBeginDrag(Data(p,new Vector2Int(1,2)));p.GetComponent<BlockDragHandler>().OnDrag(Data(p,new Vector2Int(1,2)));Req(board.PreviewValid==(name=="drag_valid")&&p.DragHighlightActive,"rendered gold drag/preview "+name);}if(name=="clear_feedback"){session.DebugPrepareCross();Req(session.TryPlacePiece(session.Slots[0],3,3)&&session.LastClear.LineCount==2,"cross clear feedback");visual.RefreshVisual();Canvas.ForceUpdateCanvases();}Bounds(name);var bg=safe.Find("Background");if(bg!=null)bg.GetComponent<AspectFillBackground>()?.SendMessage("LateUpdate");cam.Render();RenderTexture.active=rt;tex=new Texture2D(w,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,w,h),0,0);tex.Apply();File.WriteAllBytes("Validation/sprint911_"+name+".png",tex.EncodeToPNG());}finally{foreach(var p in session.Slots)if(p.GetComponent<BlockDragHandler>().IsDragging)p.GetComponent<BlockDragHandler>().CancelDrag();canvas.renderMode=mode;canvas.worldCamera=wc;cam.targetTexture=target;cam.orthographic=ortho;cam.orthographicSize=size;RenderTexture.active=active;safe.anchorMin=min;safe.anchorMax=max;safe.offsetMin=omin;safe.offsetMax=omax;area.enabled=enabled;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);visual.Layout();}}
 static readonly Dictionary<Sprite,Rect> alphaBounds=new Dictionary<Sprite,Rect>();
 static Rect PixelBounds(Image image){var sprite=image.sprite;if(!alphaBounds.TryGetValue(sprite,out var uv)){var tex=new Texture2D(2,2);tex.LoadImage(File.ReadAllBytes(AssetDatabase.GetAssetPath(sprite)));var pixels=tex.GetPixels32();int left=tex.width,bottom=tex.height,right=0,top=0;for(int y=0;y<tex.height;y++)for(int x=0;x<tex.width;x++)if(pixels[y*tex.width+x].a>=20){left=Mathf.Min(left,x);right=Mathf.Max(right,x+1);bottom=Mathf.Min(bottom,y);top=Mathf.Max(top,y+1);}uv=Rect.MinMaxRect((float)left/tex.width,(float)bottom/tex.height,(float)right/tex.width,(float)top/tex.height);alphaBounds[sprite]=uv;UnityEngine.Object.DestroyImmediate(tex);}var r=image.rectTransform.rect;float scale=board.SpriteVisualScale;var low=image.rectTransform.TransformPoint(r.center+new Vector2((uv.xMin-.5f)*r.width*scale,(uv.yMin-.5f)*r.height*scale));var high=image.rectTransform.TransformPoint(r.center+new Vector2((uv.xMax-.5f)*r.width*scale,(uv.yMax-.5f)*r.height*scale));return Rect.MinMaxRect(low.x,low.y,high.x,high.y);}
 static void DensityBounds(string name){var frame=World((RectTransform)safe.Find("BoardFrame"));var pixels=new Rect[64];for(int i=0;i<64;i++){pixels[i]=PixelBounds(board.transform.GetChild(i).GetComponent<Image>());Req(frame.Contains(pixels[i].min)&&frame.Contains(pixels[i].max),"actual alpha pixels inside frame "+name+" "+i);if(i%8>0)Req(pixels[i-1].xMax<pixels[i].xMin,"positive horizontal pixel gap "+name+" "+i);if(i>=8)Req(pixels[i].yMax<pixels[i-8].yMin,"positive vertical pixel gap "+name+" "+i);}foreach(var p in session.Slots){if(p.IsConsumed||p.GetComponent<BlockDragHandler>().IsDragging)continue;var slot=World((RectTransform)p.transform.parent);foreach(var cell in p.GetComponentsInChildren<Image>()){if(cell.transform==p.transform||!cell.name.StartsWith("BlockCell_"))continue;var bounds=PixelBounds(cell);Req(slot.Contains(bounds.min)&&slot.Contains(bounds.max),"actual piece pixels inside slot "+name+" "+p.Shape.Id);}}results.Add("DENSITY "+name+" pixel="+pixels[0].size+" pitch="+(board.CellSize+board.CellSpacing));}
 static void Bounds(string name){DensityBounds(name);Rect area=World(safe),b=World((RectTransform)board.transform);Req(Mathf.Abs(b.width-b.height)<.1f,"square board "+name);foreach(string path in new[]{"PlayingHomeButton","GameScorePresentation/BestFrameArea","GameScorePresentation/CurrentScore","PlanetRestoration","BoardFrame","BlockArea"}){Rect r=World((RectTransform)safe.Find(path));Req(r.xMin>=area.xMin-.1f&&r.xMax<=area.xMax+.1f&&r.yMin>=area.yMin-.1f&&r.yMax<=area.yMax+.1f,"safe bounds "+name+" "+path);}Rect slot0=World((RectTransform)safe.Find("BlockArea/Slot_0"));for(int i=1;i<3;i++){Rect slot=World((RectTransform)safe.Find("BlockArea/Slot_"+i));Req(Mathf.Abs(slot.width-slot0.width)<.1f&&Mathf.Abs(slot.height-slot0.height)<.1f,"equal slots "+i);}results.Add("METRICS "+name+" board="+b+" slot="+slot0+" planet="+World((RectTransform)safe.Find("PlanetRestoration"))+" board-to-slots="+(b.yMin-World((RectTransform)safe.Find("BlockArea")).yMax)+" planet-to-board="+(World((RectTransform)safe.Find("PlanetRestoration")).yMin-b.yMax));Rect frame=World((RectTransform)safe.Find("BoardFrame")),planet=World((RectTransform)safe.Find("PlanetRestoration")),bottom=World((RectTransform)safe.Find("BlockArea"));Req(frame.yMax<=planet.yMin+.1f&&frame.yMin>=bottom.yMax-.1f,"board/frame vertical gaps "+name);Req(frame.Contains(b.min)&&frame.Contains(b.max),"board within frame "+name);for(int i=0;i<64;i++){Rect c=World((RectTransform)board.transform.GetChild(i));Req(b.Contains(c.min)&&b.Contains(c.max)&&Mathf.Abs(c.width-c.height)<.1f,"cell bounds "+i);Req(board.TryScreenToCell(Screen(board.GetCellWorld(new Vector2Int(i%8,i/8))),Cam(),out var got)&&got==new Vector2Int(i%8,i/8),"cell coordinate roundtrip "+i);}results.Add("PASS "+name+": Safe Area, square 8x8 board, 64 coordinate roundtrips, nonoverlapping frame/status/slots. Board="+b.size);}
 static bool FitsTmp(TMPro.TMP_Text t){t.ForceMeshUpdate(true,true);Rect r=t.rectTransform.rect;results.Add("TMP FIT "+t.name+" text="+t.text+" font="+t.fontSize+" rect="+r.size);for(int i=0;i<t.textInfo.characterCount;i++){var c=t.textInfo.characterInfo[i];if(!c.isVisible)continue;if(c.bottomLeft.x<r.xMin-1||c.topRight.x>r.xMax+1||c.bottomLeft.y<r.yMin-1||c.topRight.y>r.yMax+1){results.Add("CLIP "+t.name+" "+c.bottomLeft+" "+c.topRight+" rect="+r);return false;}}return !t.isTextTruncated;}
 static Camera Cam(){var c=safe.GetComponentInParent<Canvas>();return c.renderMode==RenderMode.ScreenSpaceOverlay?null:c.worldCamera;}static Vector2 Screen(Vector3 w)=>RectTransformUtility.WorldToScreenPoint(Cam(),w);
 static PointerEventData Data(BlockPiece p,Vector2Int anchor){Canvas.ForceUpdateCanvases();float pitch=board.CellSize+board.CellSpacing;Vector3 center=board.GetCellWorld(anchor)+layer.TransformVector(new Vector3((p.Shape.Width-1)*pitch/2,-(p.Shape.Height-1)*pitch/2-session.DragFingerOffset));return new PointerEventData(EventSystem.current){pointerId=-1,position=Screen(center)};}
 static Rect World(RectTransform r){var c=new Vector3[4];r.GetWorldCorners(c);return Rect.MinMaxRect(c[0].x,c[0].y,c[2].x,c[2].y);}static void Req(bool v,string message){count++;if(!v)throw new Exception("Sprint911: "+message);}static void Log(string m,string trace,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors+=m+"\n";}
 static void Finish(bool pass,string fail){EditorApplication.update-=Check;Application.logMessageReceived-=Log;for(int i=0;i<3;i++){if(had[i])PlayerPrefs.SetInt(keys[i],saved[i]);else PlayerPrefs.DeleteKey(keys[i]);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint911_game.txt",string.Join("\n",results)+"\nAssertions="+count+"\n"+(pass?"SPRINT911_GAME_PASS":fail));if(pass)Debug.Log("SPRINT911_GAME_PASS");else Debug.LogError(fail);EditorApplication.Exit(pass?0:1);}
}