using System;
using System.Collections.Generic;
using System.IO;
using CosmicBlock.Core;
using CosmicBlock.Effects;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class Sprint66PlayProbe
{
 static double started,phaseStarted,firstFillChange;static int frames,phase,oldEnergy,oldVersion;static bool hadEnergy,hadVersion;static float maxFill;static string errors="";
 static int oldUnlock;static bool hadUnlock;static GameSession session;static GameFlowController flow;static PlanetRestorationView planet;static GameFeedbackController feedback;static readonly List<string> results=new List<string>();
 public static void Run(){hadUnlock=PlayerPrefs.HasKey(PlanetRestoration.Planet02UnlockKey);oldUnlock=PlayerPrefs.GetInt(PlanetRestoration.Planet02UnlockKey);hadEnergy=PlayerPrefs.HasKey(PlanetRestoration.DefaultKey);hadVersion=PlayerPrefs.HasKey(PlanetRestoration.VersionKey);oldEnergy=PlayerPrefs.GetInt(PlanetRestoration.DefaultKey,0);oldVersion=PlayerPrefs.GetInt(PlanetRestoration.VersionKey,0);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,0);PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.Save();GameFlowController.StartInGameForAutomation=true;EditorSceneManager.OpenScene(Sprint6Builder.ScenePath);started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>240){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying)return;try{
  if(phase==0){if(++frames<30)return;session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();planet=UnityEngine.Object.FindAnyObjectByType<PlanetRestorationView>(FindObjectsInactive.Include);feedback=UnityEngine.Object.FindAnyObjectByType<GameFeedbackController>(FindObjectsInactive.Include);Req(session!=null&&flow!=null&&planet!=null&&feedback!=null,"runtime references");Req(flow.Screen==FlowScreen.Game&&!flow.HomeConfirmVisible,"starts clean in game");Req(GameObject.Find("ComboText")==null,"legacy always-on ComboText removed");Req(UnityEngine.Object.FindObjectsByType<GameFeedbackController>(FindObjectsInactive.Include).Length==1,"one feedback controller");Req(!PlanetDebugPanel.ShouldShow(false)&&PlanetDebugPanel.ShouldShow(true),"release DEV hidden contract");
   foreach(int value in new[]{0,20,50,90}){session.DebugSetPlanetEnergy(value);Req(Near(planet.ProgressFill,value/1500f)&&Near(planet.ImageFillAmount,value/1500f),"actual fill "+value);}results.Add("PASS Energy actual Rect width and Image value: 0/20/50/90.");
   session.DebugSetPlanetEnergy(1500);for(int combo=1;combo<=4;combo++){session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"combo placement "+combo);Req(session.Combo==combo,"combo rule "+combo);Req(feedback.ComboPopupVisible&&feedback.ComboPopupText=="CLEAR!","single-line feedback ignores placement streak");session.DebugCompleteTurnForProbe();}results.Add("PASS placement streak 1/2/3/4 retained; each single Line shows CLEAR; popup safely restarts.");phase=1;phaseStarted=EditorApplication.timeSinceStartup;return;}
  if(phase==1){if(EditorApplication.timeSinceStartup-phaseStarted<.9)return;Req(!feedback.ComboPopupVisible&&feedback.ComboPopupText==""&&!feedback.IsPlaying,"combo stale cleanup");session.DebugSetPlanetEnergy(140);session.DebugPrepareCross();Req(session.TryPlacePiece(session.Slots[0],3,3)&&session.Restoration.CurrentEnergy==165,"140+25 saved immediately");Req(Near(planet.ProgressFill,140/1500f),"fill waits for fragment arrival");maxFill=planet.ProgressFill;firstFillChange=0;phase=2;phaseStarted=EditorApplication.timeSinceStartup;return;}
  if(phase==2){maxFill=Mathf.Max(maxFill,planet.ProgressFill);double elapsed=EditorApplication.timeSinceStartup-phaseStarted;if(firstFillChange==0&&planet.ProgressFill>140/1500f+.0001f)firstFillChange=elapsed;if(elapsed<5.0)return;Req(firstFillChange>=1.29&&firstFillChange<=2.8,"fill begins after fragment arrival: "+firstFillChange);Req(maxFill>=.109f,"boundary reaches 100: "+maxFill);Req(session.State==GameState.Playing&&planet.ShownStage==2&&Near(planet.ProgressFill,.11f),"stage 2 overflow 15%");results.Add("PASS Fragment arrival -> 0.30s overall fill, 140->150, transition, Stage 2 15/250 and overall 11%.");
   flow.RequestHome();Req(flow.HomeConfirmVisible&&flow.Screen==FlowScreen.Game,"home confirmation opens");flow.CancelHome();Req(!flow.HomeConfirmVisible&&flow.Screen==FlowScreen.Game,"continue cancels");int persistent=session.Restoration.CurrentEnergy;session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"feedback before home");flow.RequestHome();flow.ConfirmHome();Req(flow.Screen==FlowScreen.Home&&!flow.HomeConfirmVisible,"confirmed home");Req(session.Restoration.CurrentEnergy==persistent+10,"planet progress retained");Req(!feedback.IsPlaying&&!planet.FeedbackActive&&planet.ActiveFragmentCount==0,"home cleanup");flow.StartNewRun();Req(flow.Screen==FlowScreen.Game&&session.State==GameState.Playing&&session.Score==0&&session.Combo==0&&session.HasPlaceableRemainingBlock(),"clean new run");results.Add("PASS Playing->Home cancel/confirm, cleanup, persistent progression, clean PLAY.");
   flow.ShowHome();flow.RequestQuit();Req(flow.QuitRequested,"home exit request");CheckResponsive();flow.Play();session.DebugForceGameOver();Req(session.State==GameState.GameOver,"game over path");session.Retry();Req(session.State==GameState.Playing&&!feedback.IsPlaying&&!planet.FeedbackActive,"retry cleanup");session.DebugForceGameOver();flow.ShowHome();Req(flow.Screen==FlowScreen.Home&&!flow.HasSavedRun,"game over home");Req(errors.Length==0,"runtime errors "+errors);results.Add("PASS Home exit, Game Over Retry/Home, DEV contract, responsive anchors.");Finish(true,"");}
 }catch(Exception e){Finish(false,e.ToString());}}
 static void CheckResponsive(){var safe=GameObject.Find("GameCanvas").transform.Find("SafeArea");var home=safe.Find("PlayingHomeButton") as RectTransform;var confirm=safe.Find("ExitConfirm/Card") as RectTransform;var exit=safe.Find("HomeRoot/BottomActions/QuitButton") as RectTransform;var dev=safe.Find("HomeRoot/DevButton") as RectTransform;Req(home!=null&&confirm!=null&&exit!=null&&dev!=null,"responsive controls exist");foreach(var size in new[]{new Vector2Int(1080,1920),new Vector2Int(1080,2400),new Vector2Int(1080,1440)}){Req(Inside(home)&&Inside(confirm)&&Inside(exit),"inside SafeArea "+size);Req(!WorldRect(exit).Overlaps(WorldRect(dev)),"exit does not overlap DEV "+size);}}
 static Rect WorldRect(RectTransform r){var c=new Vector3[4];r.GetWorldCorners(c);return Rect.MinMaxRect(c[0].x,c[0].y,c[2].x,c[2].y);}static bool Inside(RectTransform r)=>r.anchorMin.x>=0&&r.anchorMin.y>=0&&r.anchorMax.x<=1&&r.anchorMax.y<=1;static bool Overlap(RectTransform a,RectTransform b)=>a.anchorMin.x<b.anchorMax.x&&a.anchorMax.x>b.anchorMin.x&&a.anchorMin.y<b.anchorMax.y&&a.anchorMax.y>b.anchorMin.y;static bool Near(float a,float b)=>Mathf.Abs(a-b)<.011f;
 static void Log(string m,string s,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors+=m+"\n";}static void Req(bool v,string m){if(!v)throw new Exception("Sprint 6.6 test failed: "+m);}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;Application.logMessageReceived-=Log;if(hadEnergy)PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,oldEnergy);else PlayerPrefs.DeleteKey(PlanetRestoration.DefaultKey);if(hadVersion)PlayerPrefs.SetInt(PlanetRestoration.VersionKey,oldVersion);else PlayerPrefs.DeleteKey(PlanetRestoration.VersionKey);if(hadUnlock)PlayerPrefs.SetInt(PlanetRestoration.Planet02UnlockKey,oldUnlock);else PlayerPrefs.DeleteKey(PlanetRestoration.Planet02UnlockKey);PlayerPrefs.Save();Directory.CreateDirectory("Validation");File.WriteAllText("Validation/sprint66.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT66_PLAY_PASS":failure)+"\n");if(pass)Debug.Log("SPRINT66_PLAY_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
