using System;
using System.Collections.Generic;
using System.IO;
using CosmicBlock.Core;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint6PlayProbe {
 static GameSession session;static GameFlowController flow;static GameHud hud;static PlanetRestorationView view;static int stage,frames,oldEnergy;static double started,wait;static string errors="";static readonly List<string> results=new List<string>();
 public static void Run(){oldEnergy=PlayerPrefs.GetInt(PlanetRestoration.DefaultKey,0);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,0);EditorSceneManager.OpenScene(Sprint6Builder.ScenePath);started=EditorApplication.timeSinceStartup;stage=frames=0;results.Clear();Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Log(string m,string s,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors+=m+"\n";}
 static void Check(){if(EditorApplication.timeSinceStartup-started>180){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying)return;try{
  if(stage==0){if(++frames<30)return;session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();hud=UnityEngine.Object.FindAnyObjectByType<GameHud>();view=UnityEngine.Object.FindAnyObjectByType<PlanetRestorationView>(FindObjectsInactive.Include);
   Req(PlanetRestoration.AwardForLines(0)==0&&PlanetRestoration.AwardForLines(1)==10&&PlanetRestoration.AwardForLines(2)==25&&PlanetRestoration.AwardForLines(3)==45&&PlanetRestoration.AwardForLines(4)==70&&PlanetRestoration.AwardForLines(8)==70,"energy matrix");
   int[] energy={0,120,125,245,250,370,375,495,500};int[] stages={1,1,2,2,3,3,4,4,5};for(int i=0;i<energy.Length;i++)Req(PlanetRestoration.StageForEnergy(energy[i])==stages[i],"stage matrix "+energy[i]);
   Req(UnityEngine.Object.FindObjectsByType<PlanetRestorationView>(FindObjectsInactive.Include,FindObjectsSortMode.None).Length==1,"one view");Req(!GameObject.Find("GameCanvas").transform.Find("SafeArea/Journey").gameObject.activeSelf,"Journey hidden");
   flow.Play();session.DebugSetPlanetEnergy(0);var p=session.Slots[0];Req(session.TryPlacePiece(p,0,0)&&session.Restoration.CurrentEnergy==0,"placement no energy");
   session.DebugSetPlanetEnergy(0);session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3)&&session.Restoration.CurrentEnergy==10&&view.FeedbackActive,"clear +10 and feedback");
   results.Add("PASS energy/stage matrix, no-clear +0, line-clear +10, feedback active.");wait=EditorApplication.timeSinceStartup;stage=1;return;}
  if(stage==1){if(EditorApplication.timeSinceStartup-wait<1.1)return;Req(!view.FeedbackActive,"feedback hides");session.DebugSetPlanetEnergy(120);session.DebugSetPlanetEnergy(125);Req(view.TransitionActive,"crossfade starts");wait=EditorApplication.timeSinceStartup;stage=2;return;}
  if(stage==2){if(EditorApplication.timeSinceStartup-wait<.8)return;Req(view.ShownStage==2&&!view.TransitionActive,"crossfade completes");session.DebugSetPlanetEnergy(245);session.Retry();Req(session.Restoration.CurrentEnergy==245&&!view.FeedbackActive&&!view.CompletionActive,"retry persistence/cleanup");session.DebugForceGameOver();flow.ShowHome();Req(session.Restoration.CurrentEnergy==245,"home persistence");flow.Play();Req(session.Restoration.CurrentEnergy==245&&!view.FeedbackActive&&!view.CompletionActive,"play persistence/cleanup");var loaded=new PlanetRestoration();Req(loaded.CurrentEnergy==245,"reload persistence");loaded.SetEnergy(999);Req(loaded.CurrentEnergy==500,"clamp");session.DebugSetPlanetEnergy(495);int before=session.Restoration.CurrentEnergy;int added=session.Restoration.AddEnergy(10);hud.Render(session);hud.NotifyPlanetEnergy(added,before<500&&session.Restoration.IsRestored);Req(session.Restoration.CurrentEnergy==500&&view.CompletionActive,"completion starts");results.Add("PASS crossfade, persistence, clamp, transient cleanup, completion.");wait=EditorApplication.timeSinceStartup;stage=3;return;}
  if(stage==3){if(EditorApplication.timeSinceStartup-wait<2.3)return;Req(!view.CompletionActive,"completion hides");session.Retry();Req(!view.CompletionActive&&!view.FeedbackActive&&session.State==GameState.Playing&&!hud.GameOverRoot.activeSelf,"new run UI state");Capture(1080,1920,"9x16",false);Capture(1080,2400,"tall",true);Capture(1080,1440,"short",false);Req(errors.Length==0,"runtime errors "+errors);Finish(true,"");}
 }catch(Exception ex){Finish(false,ex.ToString());}}
 static void Capture(int w,int h,string name,bool inset){var safe=GameObject.Find("GameCanvas").transform.Find("SafeArea") as RectTransform;var panel=safe.Find("PlanetRestoration") as RectTransform;var canvas=safe.GetComponentInParent<Canvas>();var cam=Camera.main;var oldMode=canvas.renderMode;var oldCam=canvas.worldCamera;var oldTarget=cam.targetTexture;var oldMin=safe.anchorMin;var oldMax=safe.anchorMax;var oldOffMin=safe.offsetMin;var oldOffMax=safe.offsetMax;var rt=new RenderTexture(w,h,24);Texture2D image=null;try{rt.Create();cam.targetTexture=rt;cam.orthographic=true;cam.orthographicSize=h/2f;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;safe.anchorMin=inset?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=inset?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();var pc=new Vector3[4];var sc=new Vector3[4];panel.GetWorldCorners(pc);safe.GetWorldCorners(sc);foreach(var c in pc)Req(c.x>=sc[0].x-.1f&&c.x<=sc[2].x+.1f&&c.y>=sc[0].y-.1f&&c.y<=sc[2].y+.1f,name+" Planet bounds");cam.Render();RenderTexture.active=rt;image=new Texture2D(w,h,TextureFormat.RGB24,false);image.ReadPixels(new Rect(0,0,w,h),0,0);image.Apply();File.WriteAllBytes("Validation/sprint6_"+name+".png",image.EncodeToPNG());results.Add("PASS responsive "+name+" Planet within SafeArea.");}finally{canvas.renderMode=oldMode;canvas.worldCamera=oldCam;cam.targetTexture=oldTarget;safe.anchorMin=oldMin;safe.anchorMax=oldMax;safe.offsetMin=oldOffMin;safe.offsetMax=oldOffMax;if(image!=null)UnityEngine.Object.DestroyImmediate(image);rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}
 static void Req(bool v,string m){if(!v)throw new Exception("Sprint 6 failed: "+m);}
 static void Finish(bool pass,string fail){EditorApplication.update-=Check;Application.logMessageReceived-=Log;PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,oldEnergy);PlayerPrefs.Save();Directory.CreateDirectory("Validation");File.WriteAllText("Validation/sprint6.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT6_PLAY_PASS":fail));if(pass)Debug.Log("SPRINT6_PLAY_PASS");else Debug.LogError(fail);EditorApplication.Exit(pass?0:1);}
}