using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using CosmicBlock.Board;
using CosmicBlock.Blocks;
using CosmicBlock.Core;
using CosmicBlock.Effects;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint92PlayProbe {
 static double started;static int frames,count;static bool running;static GameSession session;static BoardView board;static GameFeedbackController feedback;static GameFlowController flow;static string errors="",legacy="";
 static readonly List<string> results=new List<string>();static readonly string[] keys={PlanetRestoration.DefaultKey,PlanetRestoration.VersionKey,GameSession.DefaultBestScoreKey,PlanetRestoration.Planet02UnlockKey};static readonly int[] saved=new int[4];static readonly bool[] had=new bool[4];
 public static int CaptureBestOverride=-1,CaptureScoreOverride=-1;
 public static void Run()=>Begin("");public static void RunLegacyFeedback()=>Begin("Sprint4");
 static void Begin(string name){legacy=name;for(int i=0;i<keys.Length;i++){had[i]=PlayerPrefs.HasKey(keys[i]);saved[i]=PlayerPrefs.GetInt(keys[i]);}EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>600){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<30||running)return;running=true;session=UnityEngine.Object.FindAnyObjectByType<GameSession>();board=UnityEngine.Object.FindAnyObjectByType<BoardView>();feedback=session.Feedback;flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();flow.Play();session.gameObject.AddComponent<Sprint92ProbeRunner>().StartCoroutine(Guard(Tests()));}
 static IEnumerator Guard(IEnumerator steps){while(true){object current;try{if(!steps.MoveNext())break;current=steps.Current;}catch(Exception e){Finish(false,e.ToString());yield break;}yield return current;}Finish(true,"");}
 static IEnumerator Tests(){
  Req(feedback.CellPoolCapacity==64&&feedback.StarPoolCapacity==48,"fixed 64/48 pools");int hierarchy=feedback.transform.childCount;
  foreach(var image in feedback.GetComponentsInChildren<Image>(true))if(image.name.StartsWith("Starlight_"))Req(image.sprite!=null&&image.sprite.name=="game_clear_starlight"&&image.preserveAspect&&!image.raycastTarget,"starlight sprite/aspect/noninteractive");
  var rows=new[]{new List<int>{3},new List<int>(),new List<int>{2,3},new List<int>(),new List<int>{3},new List<int>(),new List<int>{2,3}};
  var cols=new[]{new List<int>(),new List<int>{3},new List<int>(),new List<int>{2,3},new List<int>{3},new List<int>{2,3,4},new List<int>{2,3}};
  var shapes=new[]{BlockCatalog.Shapes[0],BlockCatalog.Shapes[0],BlockCatalog.Shapes[3],BlockCatalog.Shapes[1],BlockCatalog.Shapes[0],BlockCatalog.Shapes[2],BlockCatalog.Shapes[5]};
  var anchors=new[]{new Vector2Int(3,3),new Vector2Int(3,3),new Vector2Int(3,2),new Vector2Int(2,3),new Vector2Int(3,3),new Vector2Int(2,3),new Vector2Int(2,2)};
  for(int test=0;test<rows.Length;test++){
   Prepare(rows[test],cols[test],shapes[test],anchors[test]);var expected=board.Model.SnapshotCompletedLines();Req(expected.LineCount==0,"pre-placement gap prevents clear");int h=feedback.HapticRequestCount,a=feedback.AudioRequestCount,spawns=feedback.TotalCellSpawns;
   Req(session.TryPlacePiece(session.Slots[0],anchors[test].x,anchors[test].y),"placement "+test);var snapshot=session.LastClear;var plan=new SequentialClearPlan(snapshot);int lines=rows[test].Count+cols[test].Count;Req(snapshot.LineCount==lines&&session.State==GameState.Resolving,"frozen plan and lock "+test);Req(session.LineComboIndex==1&&session.Score==shapes[test].Cells.Count*10+100,"first line score "+test);Req(!session.TryPlacePiece(session.Slots[1],7,7),"drop locked");session.EvaluateGameOver();Req(session.State==GameState.Resolving,"no premature game over");var drag=session.Slots[1].GetComponent<BlockDragHandler>();Req(!session.TryBeginDrag(drag),"drag locked");
   double lastLineTime=feedback.LastLineStartTime;string first=feedback.ComboPopupText;Req(first=="CLEAR!","first CLEAR");Req(Mathf.Abs(feedback.GetComponent<AudioSource>().pitch-1)<.001f,"first SFX pitch");Req(Order(plan)==new[]{"Row3","Column3","Row2,Row3","Column2,Column3","Column3,Row3","Column2,Column3,Column4","Column2,Column3,Row2,Row3"}[test],"independent expected top-left order");AssertOriginalSprites();
   yield return new WaitForSecondsRealtime(.06f);Req(session.LineComboIndex==1,"no second before interval");Capture("case_"+test+"_flash",1080,1920);
   double firstTime=EditorApplication.timeSinceStartup-.06;int awarded=100;
   for(int line=2;line<=lines;line++){
    double deadline=EditorApplication.timeSinceStartup+2;while(session.LineComboIndex<line){Req(EditorApplication.timeSinceStartup<deadline,"sequence deadline");yield return null;}
    Req(feedback.LastLineStartTime-lastLineTime>=.319,"actual interval lower bound");results.Add("INTERVAL "+(feedback.LastLineStartTime-lastLineTime));lastLineTime=feedback.LastLineStartTime;awarded+=ScoreRules.LinePoints(line);Req(session.Score==shapes[test].Cells.Count*10+awarded&&feedback.ComboPopupText==line+" COMBO","step combo/score "+line);Req(feedback.LastScoreDelta==ScoreRules.LinePoints(line),"line-only score pop");Req(Mathf.Abs(feedback.GetComponent<AudioSource>().pitch-Mathf.Min(1.15f,1+(line-1)*.05f))<.001f,"actual per-line SFX source pitch");Req(feedback.HapticRequestCount==h+line&&feedback.AudioRequestCount==a+line,"per-line feedback counts");AssertOriginalSprites();Capture("case_"+test+"_line_"+line,1080,1920);
   }
   Req(feedback.TotalCellSpawns-spawns==snapshot.UniqueClearedCells.Count,"intersection appears once");Req(session.State==GameState.Resolving,"last visual still locks");
   yield return new WaitForSecondsRealtime(.85f);Req(session.State==GameState.Playing&&!session.ClearSequenceActive&&CountBoard()==0,"finish/unlock/frozen remaining lines "+test);Req(!feedback.IsPlaying&&feedback.ActiveCellCount==0&&feedback.ActiveStarCount==0&&!feedback.ComboPopupVisible&&feedback.ComboPopupText=="","full cleanup");Req(feedback.transform.childCount==hierarchy&&feedback.PeakActiveStars<=48,"bounded pool/hierarchy");Req(session.Restoration.CurrentEnergy==1500,"restored energy never overflows");results.Add("PASS case "+test+" lines="+lines+" score="+session.Score+" unique="+snapshot.UniqueClearedCells.Count+" order="+Order(plan));
  }
  // Measure the production timeline without synchronous screenshot rendering between starts.
  Prepare(new List<int>(),new List<int>{2,3,4},BlockCatalog.Shapes[2],new Vector2Int(2,3));session.DebugSetPlanetEnergy(0);
  Req(session.TryPlacePiece(session.Slots[0],2,3),"uncaptured three-line placement");double cleanTime=feedback.LastLineStartTime;
  for(int line=2;line<=3;line++){double deadline=EditorApplication.timeSinceStartup+2;while(session.LineComboIndex<line){Req(EditorApplication.timeSinceStartup<deadline,"uncaptured interval deadline");yield return null;}double interval=feedback.LastLineStartTime-cleanTime;Req(interval>=.319&&interval<.40,"uncaptured actual interval");results.Add("UNCAPTURED_INTERVAL "+interval);cleanTime=feedback.LastLineStartTime;}
  yield return new WaitForSecondsRealtime(.85f);Req(session.Restoration.CurrentEnergy==45&&session.Score==480,"three-line energy exactly 45/score 480");session.Retry();Req(session.Restoration.CurrentEnergy==45,"energy persists after retry");Req(PlanetRestoration.AwardForLines(1)==10&&PlanetRestoration.AwardForLines(2)==25&&PlanetRestoration.AwardForLines(3)==45&&PlanetRestoration.AwardForLines(4)==70,"unchanged award table");
  // Placement streak is retained, but it is not an extra source of points.
  session.Retry();session.DebugSetPlanetEnergy(1500);for(int i=0;i<3;i++){session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"streak clear");yield return new WaitForSecondsRealtime(.85f);Req(session.PlacementCombo==i+1&&session.LineComboIndex==1&&session.Score==(i+1)*110,"no placement-streak double count");}
  feedback.SoundEnabled=false;feedback.HapticsEnabled=false;int mutedH=feedback.HapticRequestCount,mutedA=feedback.AudioRequestCount;session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"muted clear");yield return new WaitForSecondsRealtime(.85f);Req(feedback.HapticRequestCount==mutedH&&feedback.AudioRequestCount==mutedA,"sound/haptic off gates");feedback.SoundEnabled=feedback.HapticsEnabled=true;
  // Three supplied Pieces must not refill until the final Clear/Planet callback.
  session.Retry();session.DebugSetPlanetEnergy(1500);for(int i=0;i<3;i++)session.Slots[i].Initialize(BlockCatalog.Shapes[0],board,GameObject.Find("GameCanvas").transform.Find("DragLayer") as RectTransform,session);Req(session.TryPlacePiece(session.Slots[0],0,0)&&session.TryPlacePiece(session.Slots[1],1,0),"two slots consume");for(int x=2;x<8;x++)if(x!=3)board.Model.SetOccupied(x,0,true);Req(session.TryPlacePiece(session.Slots[2],3,0),"third completes row");Req(session.BlockSetNumber==1&&session.Slots[2].IsConsumed,"refill deferred");yield return new WaitForSecondsRealtime(.85f);Req(session.BlockSetNumber==2&&session.HasPlaceableRemainingBlock(),"refill after finish");
  // Same frozen cross awards exactly 25 energy, at every boundary/overflow.
  foreach(int energy in new[]{0,140,390,740,1190,1490}){
   session.Retry();session.DebugSetPlanetEnergy(energy);session.DebugPrepareCross();int before=PlayerPrefs.GetInt(PlanetRestoration.VersionKey,-1);Req(session.TryPlacePiece(session.Slots[0],3,3),"energy cross");Req(session.Restoration.CurrentEnergy==Mathf.Min(1500,energy+25),"energy durable immediately");yield return new WaitForSecondsRealtime(.95f);Req(session.Restoration.CurrentEnergy==Mathf.Min(1500,energy+25),"single total award for 2 lines");Req(PlayerPrefs.GetInt(PlanetRestoration.VersionKey,-1)==before,"migration preserved");session.Retry();Req(session.State==GameState.Playing&&!feedback.IsPlaying&&!session.ClearSequenceActive,"retry clears pending animation");Req(session.Restoration.CurrentEnergy==Mathf.Min(1500,energy+25),"retry keeps awarded energy");}
  session.Retry();session.DebugSetPlanetEnergy(90);session.DebugPrepareCross();Req(session.TryPlacePiece(session.Slots[0],3,3),"cancel pending cross");flow.RequestHome();flow.CancelHome();Req(session.State==GameState.Resolving,"cancel confirmation preserves turn");flow.RequestHome();flow.ConfirmHome();Req(flow.Screen==FlowScreen.Home&&session.Restoration.CurrentEnergy==115&&!feedback.IsPlaying&&!session.ClearSequenceActive,"home settles frozen turn once");flow.StartNewRun();Req(session.Score==0&&CountBoard()==0&&session.State==GameState.Playing,"new run clean");yield return new WaitForSecondsRealtime(1);Req(session.Score==0&&CountBoard()==0&&session.State==GameState.Playing,"no stale callback");flow.ShowHome();flow.ShowCollection();flow.CollectionView.Next();Req(flow.CollectionView.PlanetIndex==1,"collection unchanged");flow.CollectionView.GoBack();flow.Play();session.DebugForceGameOver();Req(session.State==GameState.GameOver,"real unplaceable condition");session.Retry();Req(session.State==GameState.Playing,"gameover retry");
  // Pure 16-line plan catches empty later intersections, deterministic ties and score saturation.
  var all=new List<int>();for(int i=0;i<8;i++)all.Add(i);var full=new SequentialClearPlan(new LineClearResult(all,all,new List<Vector2Int>()));var unique=new HashSet<Vector2Int>();foreach(var step in full.Steps)foreach(var cell in step.Cells)Req(unique.Add(cell),"full plan no duplicate");Req(full.Steps.Count==16&&unique.Count==64&&full.Steps[0].IsRow&&full.Steps[1].Coordinate==0&&!full.Steps[1].IsRow,"16 lines tie/order");Req(ScoreRules.AddPlacement(0,0,1,100)==100&&ScoreRules.AddPlacement(0,0,2,1)==250&&ScoreRules.AddPlacement(0,0,3,1)==450&&ScoreRules.AddPlacement(int.MaxValue-1,4,16,0)==int.MaxValue,"line scoring and saturation");
  session.DebugSetPlanetEnergy(1500);session.DebugPrepareCross();Req(session.TryPlacePiece(session.Slots[0],3,3),"responsive clear");yield return new WaitForSecondsRealtime(.18f);Capture("clear_9x16",1080,1920);Capture("clear_tall",1080,2400);Capture("clear_short",1080,1440);Req(errors.Length==0,"runtime errors "+errors);results.Add("PASS timing/input lock, original sprites, star pool, score/energy/cleanup/refill/home/retry/settings gates and responsive captures.");
 }
 static void Prepare(List<int> rows,List<int> columns,BlockShape shape,Vector2Int anchor){session.Retry();session.DebugSetPlanetEnergy(1500);var layer=GameObject.Find("GameCanvas").transform.Find("DragLayer") as RectTransform;foreach(var piece in session.Slots)piece.Initialize(shape,board,layer,session);for(int y=0;y<8;y++)for(int x=0;x<8;x++)if(rows.Contains(y)||columns.Contains(x)){bool gap=false;foreach(var c in shape.Cells)if(x==anchor.x+c.x&&y==anchor.y+c.y)gap=true;if(!gap){board.Model.SetOccupied(x,y,true);board.PaintPlacement(BlockCatalog.Shapes[0],x,y,board.BlockSprite((x+y)%3));}}}
 static Vector2Int FirstRepresentative(List<int> rows,List<int> cols){var plan=new SequentialClearPlan(new LineClearResult(rows,cols,new List<Vector2Int>()));return plan.Steps[0].Representative;}
 static string Order(SequentialClearPlan p){var parts=new List<string>();foreach(var s in p.Steps)parts.Add((s.IsRow?"Row":"Column")+s.Coordinate);return string.Join(",",parts);}
 static int CountBoard(){int n=0;for(int y=0;y<8;y++)for(int x=0;x<8;x++)if(board.Model.IsOccupied(x,y))n++;return n;}
 static void AssertOriginalSprites(){foreach(var image in feedback.GetComponentsInChildren<Image>())if(image.name.StartsWith("ClearCell_")){Req(image.sprite!=null&&image.sprite.name.StartsWith("game_block_"),"pop retains original block sprite");Req(image.GetComponent<CellSpriteDensity>()!=null,"pop same density");}}
 sealed class BackgroundSnapshot { public RectTransform Rect;public Vector2 Size,Position;public AspectFillBackground Component;public bool Enabled; }
 static void Capture(string name,int w,int h){var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var safe=canvas.transform.Find("SafeArea") as RectTransform;var area=safe.GetComponent<SafeArea>();var cam=Camera.main;var oldTarget=cam.targetTexture;var oldMode=canvas.renderMode;var oldCamera=canvas.worldCamera;var oldActive=RenderTexture.active;var rt=new RenderTexture(w,h,24);var min=safe.anchorMin;var max=safe.anchorMax;bool active=area.enabled;var backgrounds=new List<BackgroundSnapshot>();try{area.enabled=false;rt.Create();cam.targetTexture=rt;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=10;safe.anchorMin=h==2400?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=h==2400?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>().RefreshVisual();board.SendMessage("LateUpdate");Canvas.ForceUpdateCanvases();foreach(var piece in session.Slots)piece.FitSlot();feedback.RefreshLayout();AssertResponsive(safe,name);foreach(var bg in canvas.GetComponentsInChildren<AspectFillBackground>(true)){if(bg.transform.IsChildOf(safe.Find("HomeRoot"))||bg.transform.IsChildOf(safe.Find("CollectionRoot")))continue;var r=(RectTransform)bg.transform;backgrounds.Add(new BackgroundSnapshot{Rect=r,Size=r.sizeDelta,Position=r.anchoredPosition,Component=bg,Enabled=bg.enabled});bg.enabled=false;var source=new SerializedObject(bg).FindProperty("referenceSize").vector2Value;var canvasRect=(RectTransform)canvas.transform;float fill=Mathf.Max(canvasRect.rect.width/source.x,canvasRect.rect.height/source.y);r.sizeDelta=source*fill;r.anchoredPosition=((RectTransform)r.parent).InverseTransformPoint(canvasRect.TransformPoint(canvasRect.rect.center));}if(CaptureBestOverride>=0){var display=UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>();display.RenderValues(CaptureScoreOverride,CaptureBestOverride);display.BestText.ForceMeshUpdate();}cam.Render();RenderTexture.active=rt;var tex=new Texture2D(w,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,w,h),0,0);tex.Apply();File.WriteAllBytes("Validation/sprint92_"+name+".png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);}finally{foreach(var bg in backgrounds){bg.Rect.sizeDelta=bg.Size;bg.Rect.anchoredPosition=bg.Position;bg.Component.enabled=bg.Enabled;}RenderTexture.active=oldActive;cam.targetTexture=oldTarget;canvas.renderMode=oldMode;canvas.worldCamera=oldCamera;safe.anchorMin=min;safe.anchorMax=max;area.enabled=active;rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}
 static Rect WorldRect(RectTransform r){var corners=new Vector3[4];r.GetWorldCorners(corners);float minX=float.MaxValue,minY=float.MaxValue,maxX=float.MinValue,maxY=float.MinValue;foreach(var c in corners){minX=Mathf.Min(minX,c.x);minY=Mathf.Min(minY,c.y);maxX=Mathf.Max(maxX,c.x);maxY=Mathf.Max(maxY,c.y);}return Rect.MinMaxRect(minX,minY,maxX,maxY);}
 static void AssertResponsive(RectTransform safe,string name){var bounds=WorldRect(safe);foreach(string path in new[]{"BoardFrame","BlockArea","PlanetRestoration","GameScorePresentation/CurrentScore"}){var r=WorldRect((RectTransform)safe.Find(path));Req(r.xMin>=bounds.xMin-.01f&&r.xMax<=bounds.xMax+.01f&&r.yMin>=bounds.yMin-.01f&&r.yMax<=bounds.yMax+.01f,"responsive safe "+path+" "+name);}var hud=WorldRect((RectTransform)safe.Find("PlanetRestoration"));foreach(string textName in new[]{"ComboPop","ScorePop"}){var r=WorldRect((RectTransform)feedback.transform.Find(textName));Req(r.xMin>=bounds.xMin-.01f&&r.xMax<=bounds.xMax+.01f&&r.yMin>=bounds.yMin-.01f&&r.yMax<=bounds.yMax+.01f&&r.yMax<hud.yMin,"popup safe and below HUD "+name);}foreach(var image in feedback.GetComponentsInChildren<Image>())if(image.name.StartsWith("Starlight_")){var r=WorldRect(image.rectTransform);Req(r.xMin>=bounds.xMin-.01f&&r.xMax<=bounds.xMax+.01f&&r.yMin>=bounds.yMin-.01f&&r.yMax<=bounds.yMax+.01f,"starlight no clipping "+name);}}
 static void Req(bool value,string text){count++;if(!value)throw new Exception("Sprint92 "+text);}static void Log(string message,string trace,LogType type){if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors+=message+"\n";}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;Application.logMessageReceived-=Log;for(int i=0;i<keys.Length;i++){if(had[i])PlayerPrefs.SetInt(keys[i],saved[i]);else PlayerPrefs.DeleteKey(keys[i]);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint92"+(legacy==""?"":"_"+legacy)+"_tests.txt",string.Join("\n",results)+"\nAssertions="+count+"\n"+(pass?"SPRINT92_PASS":failure));if(pass)Debug.Log("SPRINT92_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
public sealed class Sprint92ProbeRunner:MonoBehaviour {}
