using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using CosmicBlock.Core;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint94VisualProbe {
 static Dictionary<string,int> saved=new Dictionary<string,int>();static List<string> keys=new List<string>(),results=new List<string>();static int frames;static double start;static GameSession session;static GameFlowController flow;
 public static void Run(){keys.Add(PlanetSelection.Key);keys.Add(PlanetRestoration.VersionKey);keys.Add(GameSession.DefaultBestScoreKey);foreach(var d in PlanetDefinitions.All){keys.Add(d.EnergyKey);keys.Add(d.UnlockKey);}foreach(var k in keys){if(PlayerPrefs.HasKey(k))saved[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,1500);PlayerPrefs.SetInt(PlanetRestoration.Planet02UnlockKey,1);PlayerPrefs.SetInt(GameSession.DefaultBestScoreKey,15930);EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");start=EditorApplication.timeSinceStartup;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-start>180){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<35)return;EditorApplication.update-=Check;try{session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();foreach(int height in new[]{1920,2400,1440}){
  PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,0);PlayerPrefs.DeleteKey(PlanetRestoration.Planet02UnlockKey);flow.ShowHome();flow.ShowCollection();flow.CollectionView.SelectPlanet(1);Capture(height,"locked2",()=>flow.CollectionView.SelectPlanet(1));PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,1500);PlayerPrefs.SetInt(PlanetRestoration.Planet02UnlockKey,1);flow.CollectionView.SelectPlanet(1);
  foreach(int e in new[]{0,300,800,1500,2400,2999,3000}){var m=new PlanetRestoration(PlanetRestoration.Planet02Key,PlanetRestoration.VersionKey,2);m.SetEnergy(e);flow.CollectionView.Open(m);Capture(height,"collection_"+e,()=>flow.CollectionView.Open(m));}
  flow.CollectionView.SelectPlanet(2);Capture(height,"locked3",()=>flow.CollectionView.SelectPlanet(2));flow.CollectionView.SelectPlanet(1);flow.CollectionView.Choose();Capture(height,"home2",()=>flow.RefreshHome());flow.Play();Capture(height,"game2_complete",()=>{UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>().RefreshVisual();});session.DebugSetPlanetEnergy(2400);Capture(height,"game2_final_segment",()=>UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>().RefreshVisual());session.DebugForceGameOver();Capture(height,"game2_gameover",()=>UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>().RefreshVisual());
 }Finish(true,"");}catch(Exception e){Finish(false,e.ToString());}}
 static void Capture(int h,string tag,Action refresh){int w=1080;var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var safe=(RectTransform)canvas.transform.Find("SafeArea");var area=safe.GetComponent<SafeArea>();var cam=Camera.main;var oldMode=canvas.renderMode;var oldCamera=canvas.worldCamera;var oldTarget=cam.targetTexture;var oldActive=RenderTexture.active;var oldMin=safe.anchorMin;var oldMax=safe.anchorMax;bool oldEnabled=area.enabled;var rt=new RenderTexture(w,h,24);Texture2D tex=null;try{area.enabled=false;rt.Create();cam.targetTexture=rt;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=10;safe.anchorMin=h==2400?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=h==2400?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();foreach(var background in canvas.GetComponentsInChildren<AspectFillBackground>(true)){var br=(RectTransform)background.transform;var img=background.GetComponent<Image>();var full=(RectTransform)canvas.transform;float scale=Mathf.Max(full.rect.width/img.sprite.rect.width,full.rect.height/img.sprite.rect.height);br.anchorMin=br.anchorMax=Vector2.one*.5f;br.sizeDelta=img.sprite.rect.size*scale;br.anchoredPosition=br.parent.InverseTransformPoint(full.TransformPoint(full.rect.center));}flow.HomeRoot.GetComponent<HomeFinalLayout>().Apply();Canvas.ForceUpdateCanvases();refresh();Canvas.ForceUpdateCanvases();if(flow.Screen==FlowScreen.Collection){var c=flow.CollectionView;var button=(RectTransform)c.transform.Find("SelectPlanet");Req(Inside(button,safe),"selection safe");var icon=(RectTransform)c.transform.Find("Hero/HeroLock");Req(icon.rect.width>0&&icon.rect.height>0,"lock rect valid");foreach(var text in c.GetComponentsInChildren<Text>())Req(text.cachedTextGenerator.characterCountVisible>=text.text.Replace("\n","").Length,"clipped "+tag+" "+h+" "+text.name);if(c.CanSelect){var track=(RectTransform)c.transform.Find("ProgressFrameArea/ProgressFrame/Progress");var fill=(RectTransform)track.Find("Fill");Req(Mathf.Abs(fill.rect.width/track.rect.width-c.Progress)<.0001f,"actual rendered bar width");}Req(c.transform.Find("Previous/Icon").GetComponent<Image>().preserveAspect&&c.transform.Find("Next/Icon").GetComponent<Image>().preserveAspect,"navigation aspect");}
 if(flow.Screen==FlowScreen.Home){var info=flow.HomeRoot.transform.Find("HeroArea/SelectedPlanetInfo").GetComponent<Text>();Req(info.cachedTextGenerator.characterCountVisible>=info.text.Replace("\n","").Length,"home planet information clipping "+h);Req(Inside(info.rectTransform,safe),"home information safe area");} if(flow.Screen==FlowScreen.Game&&session.State==GameState.GameOver){var hud=UnityEngine.Object.FindAnyObjectByType<GameHud>();var final=(Text)typeof(GameHud).GetField("finalScoreText",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(hud);Req(final.text.Contains("행성 02 · 크리스탈리아"),"GameOver planet context");Req(final.cachedTextGenerator.characterCountVisible>=final.text.Replace("\n","").Length,"GameOver text clipping "+h);} cam.Render();RenderTexture.active=rt;tex=new Texture2D(w,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,w,h),0,0);tex.Apply();File.WriteAllBytes("Validation/sprint94_"+tag+"_"+h+".png",tex.EncodeToPNG());results.Add("PASS "+tag+" "+h);
 }finally{canvas.renderMode=oldMode;canvas.worldCamera=oldCamera;cam.targetTexture=oldTarget;RenderTexture.active=oldActive;safe.anchorMin=oldMin;safe.anchorMax=oldMax;area.enabled=oldEnabled;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}
 static bool Inside(RectTransform child,RectTransform parent){var c=new Vector3[4];child.GetWorldCorners(c);foreach(var p in c)if(!parent.rect.Contains(parent.InverseTransformPoint(p)))return false;return true;}
 static void Req(bool b,string m){if(!b)throw new Exception(m);}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;foreach(var k in keys){if(saved.TryGetValue(k,out int v))PlayerPrefs.SetInt(k,v);else PlayerPrefs.DeleteKey(k);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint94_visual_tests.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT94_VISUAL_PASS":failure));if(pass)Debug.Log("SPRINT94_VISUAL_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
