using System;using System.Collections.Generic;using System.IO;using CosmicBlock.Core;using CosmicBlock.UI;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;
public static class Sprint74HomePlayProbe{
 static double started;static int frames,oldEnergy,oldVersion;static bool hadEnergy,hadVersion;static string errors="";static readonly List<string> results=new List<string>();static GameSession session;static GameFlowController flow;static HomeViewController view;static Transform safe,home;static Sprite hero;
 public static void Run(){hadEnergy=PlayerPrefs.HasKey(PlanetRestoration.DefaultKey);hadVersion=PlayerPrefs.HasKey(PlanetRestoration.VersionKey);oldEnergy=PlayerPrefs.GetInt(PlanetRestoration.DefaultKey,0);oldVersion=PlayerPrefs.GetInt(PlanetRestoration.VersionKey,0);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,0);PlayerPrefs.SetInt(PlanetRestoration.VersionKey,PlanetRestoration.CurrentVersion);PlayerPrefs.Save();EditorSceneManager.OpenScene(Sprint73HomeBuilder.ScenePath);started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>180){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<35)return;try{session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();view=flow.HomeView;safe=GameObject.Find("GameCanvas").transform.Find("SafeArea");home=safe.Find("HomeRoot");Req(flow.Screen==FlowScreen.Home&&view!=null,"cold HOME");var heroImage=ImageAt(home,"HeroArea/HeroPlanet");hero=heroImage.sprite;Req(hero!=null&&hero.name=="home_planet_hero"&&heroImage.preserveAspect,"fixed hero");Req(home.Find("CurrentPlanetArea")==null,"stage card removed");Req(!ContainsStageInfo(home),"stage information removed");
 int[] total={0,20,50,90,100,115,190,290,390,400};int[] local={0,20,50,90,0,15,90,90,90,100};for(int i=0;i<total.Length;i++){session.DebugSetPlanetEnergy(total[i]);flow.RefreshHome();Req(Mathf.Abs(view.ProgressFill-local[i]/100f)<.011f,"stage fill "+total[i]);Req(view.EnergyText.Contains(local[i]+" / 100"),"energy text "+total[i]);Req(view.EnergyPercentText==local[i]+"%","percent "+total[i]);Req(ImageAt(home,"HeroArea/HeroPlanet").sprite==hero,"hero invariant "+total[i]);}results.Add("PASS fixed Hero and stage-local Energy 0/20/50/90/transition overflow/restored.");
 Capture(1080,1920,"9x16");Capture(1080,2400,"tall_safe");Capture(1080,1440,"short");results.Add("PASS responsive 1080x1920, 1080x2400 SafeArea, 1080x1440.");
 home.Find("MainActions/PlanetCollectionButton").GetComponent<Button>().onClick.Invoke();Req(view.ToastVisible,"collection toast");view.HideTransient();home.Find("BottomActions/SettingsButton").GetComponent<Button>().onClick.Invoke();Req(view.SettingsVisible,"settings");home.Find("SettingsPanel/Card/Close").GetComponent<Button>().onClick.Invoke();home.Find("BottomActions/QuitButton").GetComponent<Button>().onClick.Invoke();Req(view.QuitVisible,"quit");home.Find("QuitConfirmPanel/Card/Cancel").GetComponent<Button>().onClick.Invoke();Req(!view.QuitVisible&&!flow.QuitRequested,"quit cancel");Req(home.Find("DevButton").gameObject.activeSelf&&PlanetDebugPanel.ShouldShow(true)&&!PlanetDebugPanel.ShouldShow(false),"DEV contract");
 session.DebugSetPlanetEnergy(115);flow.RefreshHome();home.Find("MainActions/GameStartButton").GetComponent<Button>().onClick.Invoke();Req(flow.Screen==FlowScreen.Game,"PLAY");flow.RequestHome();flow.ConfirmHome();Req(flow.Screen==FlowScreen.Home&&ImageAt(home,"HeroArea/HeroPlanet").sprite==hero&&Mathf.Abs(view.ProgressFill-.15f)<.011f,"return refresh");Req(errors.Length==0,"runtime errors "+errors);results.Add("PASS actions, popups, DEV, HOME↔GAME and energy refresh.");Finish(true,"");}catch(Exception e){Finish(false,e.ToString());}}
 static bool ContainsStageInfo(Transform root){foreach(var t in root.GetComponentsInChildren<Text>(true)){string x=t.text;if(x.Contains("행성 01")||x.Contains("황폐함")||x.Contains("깨어남")||x.Contains("복원 단계"))return true;}return false;}
 static void Capture(int width,int height,string name){var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var camera=Camera.main;var sr=safe as RectTransform;var mode=canvas.renderMode;var wc=canvas.worldCamera;var target=camera.targetTexture;bool ortho=camera.orthographic;float os=camera.orthographicSize;var active=RenderTexture.active;var rt=new RenderTexture(width,height,24);Texture2D tex=null;try{rt.Create();camera.targetTexture=rt;camera.orthographic=true;camera.orthographicSize=height/2f;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=camera;canvas.planeDistance=10;sr.anchorMin=Vector2.zero;sr.anchorMax=Vector2.one;sr.offsetMin=sr.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();home.Find("HomeBackground").GetComponent<AspectFillBackground>().SendMessage("Apply");Canvas.ForceUpdateCanvases();CheckLayout(name);camera.Render();RenderTexture.active=rt;tex=new Texture2D(width,height,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,width,height),0,0);tex.Apply();Directory.CreateDirectory("Validation");File.WriteAllBytes("Validation/sprint74_home_"+name+".png",tex.EncodeToPNG());}finally{canvas.renderMode=mode;canvas.worldCamera=wc;camera.targetTexture=target;camera.orthographic=ortho;camera.orthographicSize=os;RenderTexture.active=active;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);sr.GetComponent<SafeArea>().SendMessage("Apply");}}
 static void CheckLayout(string n){string[] paths={"TitleArea","HeroArea","EnergyArea","MainActions","BestScoreArea","BottomActions"};Rect prev=new Rect();bool first=true;foreach(string p in paths){Rect r=World(home.Find(p) as RectTransform);Req(r.width>20&&r.height>20,"visible "+p+" "+n);if(!first)Req(r.yMax<=prev.yMin+4,"no overlap "+p+" "+n);prev=r;first=false;}Req(!World(home.Find("BottomActions/SettingsButton") as RectTransform).Overlaps(World(home.Find("BottomActions/QuitButton") as RectTransform)),"utility no overlap "+n);}
 static Rect World(RectTransform r){var c=new Vector3[4];r.GetWorldCorners(c);return Rect.MinMaxRect(c[0].x,c[0].y,c[2].x,c[2].y);}static Image ImageAt(Transform r,string p){var t=r.Find(p);if(t==null)throw new Exception("missing "+p);return t.GetComponent<Image>();}static void Req(bool v,string m){if(!v)throw new Exception("Sprint 7.4 test failed: "+m);}static void Log(string m,string s,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors+=m+"\n";}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;Application.logMessageReceived-=Log;if(hadEnergy)PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,oldEnergy);else PlayerPrefs.DeleteKey(PlanetRestoration.DefaultKey);if(hadVersion)PlayerPrefs.SetInt(PlanetRestoration.VersionKey,oldVersion);else PlayerPrefs.DeleteKey(PlanetRestoration.VersionKey);PlayerPrefs.Save();Directory.CreateDirectory("Validation");File.WriteAllText("Validation/sprint74.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT74_HOME_PASS":failure)+"\n");if(pass)Debug.Log("SPRINT74_HOME_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
