using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using CosmicBlock.Board;
using CosmicBlock.Blocks;
using CosmicBlock.Core;
using CosmicBlock.Effects;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Debug=UnityEngine.Debug;
public static class Sprint921PlayProbe {
 static bool after,running;static int frames,assertions;static double started;static string errors="";
 static GameSession session;static BoardView board;static GameFeedbackController feedback;static Action update;
 static readonly List<string> results=new List<string>();static readonly string[] keys={PlanetRestoration.DefaultKey,PlanetRestoration.VersionKey,GameSession.DefaultBestScoreKey};static readonly int[] saved=new int[3];static readonly bool[] had=new bool[3];
 const BindingFlags Flags=BindingFlags.Instance|BindingFlags.NonPublic;
 public static void RunBefore()=>Begin(false);public static void Run()=>Begin(true);
 static void Begin(bool value){after=value;for(int i=0;i<3;i++){had[i]=PlayerPrefs.HasKey(keys[i]);saved[i]=PlayerPrefs.GetInt(keys[i]);}EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-started>300){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<30||running)return;running=true;try{session=UnityEngine.Object.FindAnyObjectByType<GameSession>();board=UnityEngine.Object.FindAnyObjectByType<BoardView>();feedback=session.Feedback;UnityEngine.Object.FindAnyObjectByType<GameFlowController>().Play();feedback.enabled=false;update=(Action)Delegate.CreateDelegate(typeof(Action),feedback,typeof(GameFeedbackController).GetMethod("Update",Flags));foreach(string field in new[]{"session","board","feedback"})typeof(Sprint92PlayProbe).GetField(field,BindingFlags.Static|BindingFlags.NonPublic).SetValue(null,field=="session"?(object)session:field=="board"?board:feedback);Tests();Finish(true,"");}catch(Exception e){Finish(false,e.ToString());}}
 static T Field<T>(string name)=>(T)typeof(GameFeedbackController).GetField(name,Flags).GetValue(feedback);
 static void Set(string name,object value)=>typeof(GameFeedbackController).GetField(name,Flags).SetValue(feedback,value);
 static void Fixture(bool columns,int lines,int coordinate){session.Retry();session.DebugSetPlanetEnergy(400);var layer=GameObject.Find("GameCanvas").transform.Find("DragLayer") as RectTransform;for(int i=0;i<3;i++)session.Slots[i].Initialize(BlockCatalog.Shapes[new[]{2,4,5}[i]],board,layer,session);Set("random",new System.Random(921));Set("starCursor",0);Set("cellCursor",0);feedback.ResetFeedback();for(int y=0;y<8;y++)for(int x=0;x<8;x++)if(columns?x>=coordinate&&x<coordinate+lines:y>=coordinate&&y<coordinate+lines){board.Model.SetOccupied(x,y,true);board.PaintPlacement(BlockCatalog.Shapes[0],x,y,board.BlockSprite((x+y)%3));}Canvas.ForceUpdateCanvases();board.SendMessage("LateUpdate");var plan=new SequentialClearPlan(board.Model.SnapshotCompletedLines());int star=0,cell=0;foreach(var step in plan.Steps){feedback.PlayClear(step.Result,ScoreRules.LinePoints(star/12+1),star/12+1);board.Model.ClearCells(step.Cells);int line=star/12;for(int i=0;i<12;i++)Field<float[]>("starAges")[star+i]=.20f+(lines-1-line)*.16f-Time.unscaledDeltaTime;for(int i=0;i<step.Cells.Count;i++)Field<float[]>("cellAges")[cell+i]=.20f+(lines-1-line)*.16f-Time.unscaledDeltaTime;star+=12;cell+=step.Cells.Count;}Set("textAge",.20f-Time.unscaledDeltaTime);session.DebugSetScore(ScoreRules.AddPlacement(0,0,lines,0));update();}
 static void Tests(){int hierarchy=feedback.transform.childCount;Req(feedback.StarPoolCapacity==48,"pool48");foreach(var c in new[]{new[]{0,1,3},new[]{1,1,3},new[]{0,2,2},new[]{1,3,2}}){Fixture(c[0]==1,c[1],c[2]);Req(feedback.LastParticleCount==12&&feedback.ActiveStarCount<=12*c[1],"12 per line");Req(feedback.transform.childCount==hierarchy,"stable hierarchy");if(after){var images=Field<Image[]>("starlights");int large=0,medium=0,small=0;for(int i=(c[1]-1)*12;i<c[1]*12;i++){float factor=images[i].rectTransform.sizeDelta.x/59;Req(factor>=.75f&&factor<=1.35f,"size range");if(factor>=1.15f)large++;else if(factor>=.90f)medium++;else small++;}Req(large==4&&medium==5&&small==3,"4L/5M/3S per line");results.Add("MIX large="+large+" medium="+medium+" small="+small);}string name=(c[0]==1?"column":"row")+c[1];Capture(name,1080,1920);}
  foreach(var size in new[]{new[]{1080,1920},new[]{1080,2400},new[]{1080,1440}}){Fixture(false,1,0);Capture("edge_top_"+size[1],size[0],size[1]);Fixture(true,1,7);Capture("edge_right_"+size[1],size[0],size[1]);Fixture(false,1,7);Capture("edge_bottom_"+size[1],size[0],size[1]);Fixture(true,3,2);Capture("three_"+size[1],size[0],size[1]);}
  Fixture(false,1,3);var lights=Field<Image[]>("starlights");float mean=0;foreach(var im in lights)if(im.gameObject.activeSelf)mean+=im.rectTransform.sizeDelta.x;mean/=12;results.Add("MEAN_RECT="+mean+" PEAK_MEAN="+(mean*(after?1.15f:1.1f)));for(int i=0;i<12;i++)Req(Field<float[]>("starLives")[i]>=.35f&&Field<float[]>("starLives")[i]<=.65f,"unchanged life");MeasureSprite(mean*(after?1.15f:1.1f));var measurement=new Measurements{mean=mean,directions=new Vector2[12],sizes=new float[12]};for(int i=0;i<12;i++){measurement.directions[i]=Field<Vector2[]>("starDirections")[i];measurement.sizes[i]=lights[i].rectTransform.sizeDelta.x;}File.WriteAllText("Validation/sprint921_"+(after?"after":"before")+"_params.json",JsonUtility.ToJson(measurement,true));if(after){var baseline=JsonUtility.FromJson<Measurements>(File.ReadAllText("Validation/sprint921_before_params.json"));for(int i=0;i<12;i++)Req(Vector2.Distance(measurement.directions[i],baseline.directions[i]*1.35f)<.01f,"movement1.35x");var agesCheck=Field<float[]>("starAges");for(int i=0;i<12;i++)agesCheck[i]=.10001f-Time.unscaledDeltaTime;update();foreach(var im in lights)if(im.gameObject.activeSelf)Req(Mathf.Abs(im.rectTransform.localScale.x-.65f)<.001f,"start0.65");for(int i=0;i<12;i++)agesCheck[i]=.20f-Time.unscaledDeltaTime;update();foreach(var im in lights)if(im.gameObject.activeSelf)Req(Mathf.Abs(im.rectTransform.localScale.x-1.15f)<.001f,"pop1.15in0.10s");}
  Fixture(true,3,2);var ages=Field<float[]>("starAges");for(int i=0;i<48;i++)ages[i]=.18f;Set("textAge",1f);for(int i=0;i<64;i++)Field<float[]>("cellAges")[i]=1;for(int i=0;i<36;i++)Field<Image[]>("starlights")[i].gameObject.SetActive(true);for(int j=0;j<10;j++){for(int i=0;i<36;i++)ages[i]=.18f;update();}long controlBefore=GC.GetAllocatedBytesForCurrentThread(),controlHeap=UnityEngine.Profiling.Profiler.GetMonoUsedSizeLong();var control=new byte[1024*1024];GC.KeepAlive(control);long controlCounterDelta=GC.GetAllocatedBytesForCurrentThread()-controlBefore,controlHeapDelta=UnityEngine.Profiling.Profiler.GetMonoUsedSizeLong()-controlHeap;Req(controlHeapDelta>=1024*1024,"Mono heap counter calibration");results.Add("GC_COUNTER_CALIBRATION="+controlCounterDelta+" MONO_HEAP_CALIBRATION="+controlHeapDelta);var watch=new Stopwatch();long gc=GC.GetAllocatedBytesForCurrentThread(),heap=UnityEngine.Profiling.Profiler.GetMonoUsedSizeLong();int collections=GC.CollectionCount(0);Req(feedback.ActiveStarCount==36,"36 active for performance sample");watch.Start();for(int j=0;j<500;j++){for(int i=0;i<36;i++)ages[i]=.18f;update();}watch.Stop();long allocated=GC.GetAllocatedBytesForCurrentThread()-gc,heapDelta=UnityEngine.Profiling.Profiler.GetMonoUsedSizeLong()-heap;int collectionDelta=GC.CollectionCount(0)-collections;results.Add("ANIMATION_LOOP_500_GC_BYTES="+allocated+" CPU_MS_PER_UPDATE="+watch.Elapsed.TotalMilliseconds/500+" MONO_HEAP_DELTA="+heapDelta+" COLLECTIONS="+collectionDelta);Req(feedback.ActiveStarCount==36,"36 active after performance sample");Req(collectionDelta==0,"no collection in warmed animation loop");Req(controlCounterDelta==0?heapDelta==0:allocated<=128,"calibrated animation loop no allocation spike");Req(feedback.StarPoolCapacity==48&&feedback.transform.childCount==hierarchy,"pool/hierarchy after stress");for(int i=0;i<48;i++)ages[i]=1;update();Req(feedback.ActiveStarCount==0,"pool returned before1sec");Req(errors=="","runtime error "+errors);
 }
 [Serializable] sealed class Measurements {public float mean;public Vector2[] directions;public float[] sizes;}
 static Rect Bounds(RectTransform r){var v=new Vector3[4];r.GetWorldCorners(v);float x=float.MaxValue,y=float.MaxValue,X=float.MinValue,Y=float.MinValue;foreach(var p in v){x=Mathf.Min(x,p.x);y=Mathf.Min(y,p.y);X=Mathf.Max(X,p.x);Y=Mathf.Max(Y,p.y);}return Rect.MinMaxRect(x,y,X,Y);}
 static void Capture(string name,int w,int h){string tag="921_"+(after?"after_":"before_")+name;typeof(Sprint92PlayProbe).GetMethod("Capture",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{tag,w,h});string path="Validation/sprint92_"+tag+".png";string target="Validation/sprint921_"+(after?"after_":"before_")+name+".png";if(File.Exists(target))File.Delete(target);File.Move(path,target);if(after){var safe=(RectTransform)GameObject.Find("GameCanvas").transform.Find("SafeArea");var hud=Bounds((RectTransform)safe.Find("PlanetRestoration"));foreach(var image in Field<Image[]>("starlights"))if(image.gameObject.activeSelf)Req(Bounds(image.rectTransform).yMax<hud.yMin,"star belowHUD");}results.Add("CAPTURE "+target);}
 static void MeasureSprite(float size){var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var camera=Camera.main;var graphics=canvas.GetComponentsInChildren<Graphic>(true);var enabled=new bool[graphics.Length];var light=Field<Image[]>("starlights")[0];var r=light.rectTransform;var pos=r.anchoredPosition;var sz=r.sizeDelta;var scale=r.localScale;var rotation=r.localRotation;var color=light.color;var oldTarget=camera.targetTexture;var oldMode=canvas.renderMode;var oldCamera=canvas.worldCamera;var oldColor=camera.backgroundColor;var oldFlags=camera.clearFlags;var oldActive=RenderTexture.active;var rt=new RenderTexture(1080,1920,24);try{for(int i=0;i<graphics.Length;i++){enabled[i]=graphics[i].enabled;graphics[i].enabled=false;}light.enabled=true;light.color=Color.white;r.anchoredPosition=Vector2.zero;r.sizeDelta=Vector2.one*size;r.localScale=Vector3.one;r.localRotation=Quaternion.identity;rt.Create();camera.targetTexture=rt;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=camera;canvas.planeDistance=10;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=Color.black;Canvas.ForceUpdateCanvases();camera.Render();RenderTexture.active=rt;var tex=new Texture2D(1080,1920,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1080,1920),0,0);tex.Apply();var pixels=tex.GetPixels32();int xmin=1080,ymin=1920,xmax=-1,ymax=-1;for(int y=0;y<1920;y++)for(int x=0;x<1080;x++){var c=pixels[y*1080+x];if(Mathf.Max(c.r,Mathf.Max(c.g,c.b))<20)continue;xmin=Math.Min(xmin,x);xmax=Math.Max(xmax,x);ymin=Math.Min(ymin,y);ymax=Math.Max(ymax,y);}results.Add("RENDERED_STAR_BOUNDS="+(xmax-xmin+1)+"x"+(ymax-ymin+1)+" THRESHOLD_RGB20 RECT="+size);File.WriteAllBytes("Validation/sprint921_"+(after?"after":"before")+"_isolated.png",tex.EncodeToPNG());UnityEngine.Object.DestroyImmediate(tex);}finally{for(int i=0;i<graphics.Length;i++)graphics[i].enabled=enabled[i];r.anchoredPosition=pos;r.sizeDelta=sz;r.localScale=scale;r.localRotation=rotation;light.color=color;camera.targetTexture=oldTarget;canvas.renderMode=oldMode;canvas.worldCamera=oldCamera;camera.backgroundColor=oldColor;camera.clearFlags=oldFlags;RenderTexture.active=oldActive;rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}
 static void Req(bool value,string text){assertions++;if(!value)throw new Exception("Sprint921 "+text);}static void Log(string m,string s,LogType type){if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors+=m+"\n";}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;Application.logMessageReceived-=Log;for(int i=0;i<3;i++){if(had[i])PlayerPrefs.SetInt(keys[i],saved[i]);else PlayerPrefs.DeleteKey(keys[i]);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint921_"+(after?"after":"before")+"_tests.txt",string.Join("\n",results)+"\nAssertions="+assertions+"\n"+(pass?"SPRINT921_PASS":failure));if(pass)Debug.Log("SPRINT921_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
