using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using CosmicBlock.Audio;
using CosmicBlock.UI;
using CosmicBlock.Effects;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint1022AudioProbe {
 static BackgroundMusicController music;static GameFlowController flow;static GameFeedbackController sfx;static string errors="";static double began;static int frames;static Dictionary<string,int> ints=new Dictionary<string,int>();static bool hadVolume;static float oldVolume;static List<string> results=new List<string>();
 public static void Run(){foreach(var k in new[]{BackgroundMusicController.EnabledKey,BackgroundMusicController.SfxKey}){if(PlayerPrefs.HasKey(k))ints[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}hadVolume=PlayerPrefs.HasKey(BackgroundMusicController.VolumeKey);oldVolume=PlayerPrefs.GetFloat(BackgroundMusicController.VolumeKey);PlayerPrefs.DeleteKey(BackgroundMusicController.VolumeKey);PlayerPrefs.Save();EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");began=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Log(string m,string stack,LogType type){if(type==LogType.Warning||type==LogType.Error||type==LogType.Exception)errors+=m+"\n";}
 static void Check(){if(EditorApplication.timeSinceStartup-began>150){Finish(false,"시간 초과");return;}if(!EditorApplication.isPlaying||++frames<35)return;EditorApplication.update-=Check;music=UnityEngine.Object.FindAnyObjectByType<BackgroundMusicController>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();sfx=UnityEngine.Object.FindAnyObjectByType<GameFeedbackController>();music.StartCoroutine(Guard());}
 static IEnumerator Guard(){var e=Body();while(true){object v;try{if(!e.MoveNext())break;v=e.Current;}catch(Exception ex){Finish(false,ex.ToString());yield break;}yield return v;}Finish(errors.Length==0,errors);}
 static IEnumerator Body(){
  music.SendMessage("OnApplicationFocus",true);yield return new WaitForSecondsRealtime(.2f);
  Req(UnityEngine.Object.FindObjectsByType<BackgroundMusicController>(FindObjectsInactive.Include).Length==1,"오디오 관리자 단일 객체");Req(music.HomeSource.clip.name=="cosmic_block_home_bgm"&&music.GameSource.clip.name=="cosmic_block_main_bgm","실제 에셋 연결");Req(music.HomeSource.loop&&music.GameSource.loop&&music.HomeSource.clip.loadType==AudioClipLoadType.Streaming&&music.GameSource.clip.loadType==AudioClipLoadType.Streaming,"Loop/Streaming");Req(Mathf.Approximately(music.MusicVolume,.35f)&&music.HomeSource.isPlaying&&!music.GameSource.isPlaying,"최초 HOME/35% volume="+music.MusicVolume+" home="+music.HomeSource.isPlaying+" game="+music.GameSource.isPlaying+" suspended="+music.Suspended);float time=music.HomeSource.time;flow.ShowCollection();yield return new WaitForSecondsRealtime(.25f);Req(music.HomeSource.time>time&&music.GameMix==0&&!music.GameSource.isPlaying,"도감 HOME 음악 재시작 없음");flow.ReturnFromCollection();
  EnterGame();yield return new WaitForSecondsRealtime(.7f);Req(music.GameMix>.35f&&music.GameMix<.6f&&music.HomeSource.isPlaying&&music.GameSource.isPlaying,"1.5초 실제 크로스페이드 중간");Req(Mathf.Abs(music.HomeSource.volume+music.GameSource.volume-.35f)<.001f,"중간 총 볼륨 유지");yield return new WaitForSecondsRealtime(.9f);Req(music.GameMix==1&&music.GameSource.isPlaying&&!music.HomeSource.isPlaying,"GAME 완료/이전 소스 정지");time=music.GameSource.time;EnterGame();yield return new WaitForSecondsRealtime(.2f);Req(music.GameSource.time>time,"동일 GAME 재시작 없음");results.Add("PASS HOME/도감/GAME 1.5초 전환/동일 음악 유지");
  for(int i=0;i<6;i++){flow.ShowHome();yield return new WaitForSecondsRealtime(.07f);EnterGame();yield return new WaitForSecondsRealtime(.07f);}yield return new WaitForSecondsRealtime(1.6f);Req(music.GameMix==1&&!music.HomeSource.isPlaying&&music.GameSource.isPlaying,"빠른 왕복 최종 소스 정상");flow.ShowHome();yield return new WaitForSecondsRealtime(1.6f);Req(music.GameMix==0&&music.HomeSource.isPlaying&&!music.GameSource.isPlaying,"HOME 복귀");
  flow.HomeView.ShowSettings();var settings=flow.HomeRoot.GetComponentInChildren<AudioSettingsView>();settings.BgmButton.onClick.Invoke();Req(!music.MusicEnabled&&music.HomeSource.volume==0&&music.GameSource.volume==0&&sfx.SoundEnabled,"BGM OFF 완전 무음/SFX 독립");EnterGame();yield return new WaitForSecondsRealtime(1.6f);int requests=sfx.AudioRequestCount;bool haptics=sfx.HapticsEnabled;sfx.HapticsEnabled=false;var clear=new CosmicBlock.Board.LineClearResult(new List<int>{0},new List<int>(),new List<Vector2Int>{Vector2Int.zero});sfx.PlayClear(clear,100,1);Req(sfx.AudioRequestCount==requests+1&&sfx.GetComponent<AudioSource>().isPlaying&&music.GameSource.volume==0,"BGM OFF에서도 실제 SFX 재생");sfx.HapticsEnabled=haptics;yield return new WaitForSecondsRealtime(.8f);flow.ShowHome();yield return new WaitForSecondsRealtime(1.6f);flow.HomeView.ShowSettings();settings.VolumeSlider.value=.62f;Req(music.MusicVolume==.62f&&music.HomeSource.volume==0,"OFF에서 볼륨 설정 유지");settings.BgmButton.onClick.Invoke();Req(Mathf.Abs(music.HomeSource.volume-.62f)<.001f,"볼륨 즉시 반영");float baseSfx=sfx.GetComponent<AudioSource>().volume;settings.SfxButton.onClick.Invoke();Req(!sfx.SoundEnabled&&music.MusicEnabled&&music.HomeSource.volume>.6f,"SFX OFF 독립");settings.SfxButton.onClick.Invoke();Req(sfx.SoundEnabled&&sfx.GetComponent<AudioSource>().volume==baseSfx,"SFX 기존 볼륨 유지");music.SetMusicEnabled(false);music.ReloadSettings();Req(!music.MusicEnabled&&music.MusicVolume==.62f&&music.SfxEnabled,"PlayerPrefs 복원");music.SetMusicEnabled(true);
  music.SendMessage("OnApplicationPause",true);float mix=music.GameMix;Req(!music.HomeSource.isPlaying&&music.Suspended,"백그라운드 정지");music.SendMessage("OnApplicationFocus",false);music.SendMessage("OnApplicationPause",false);Req(music.Suspended&&!music.HomeSource.isPlaying,"pause/focus 순서 안전");music.SendMessage("OnApplicationFocus",true);yield return null;Req(!music.Suspended&&music.HomeSource.isPlaying&&music.GameMix==mix&&!music.GameSource.isPlaying,"복귀 단일 음악");
  results.Add("PASS 빠른 전환/BGM·SFX 독립/볼륨/저장 설정/백그라운드 복귀");
  flow.HomeView.ShowSettings();Canvas.ForceUpdateCanvases();ScreenCapture.CaptureScreenshot(Path.GetFullPath("Validation/sprint1022_settings.png"));yield return new WaitForSecondsRealtime(.3f);
 }
 static void EnterGame()=>typeof(GameFlowController).GetMethod("EnterGame",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(flow,null);
 static void Req(bool b,string m){if(!b)throw new Exception(m);}
 static void Finish(bool pass,string reason){EditorApplication.update-=Check;Application.logMessageReceived-=Log;foreach(var k in new[]{BackgroundMusicController.EnabledKey,BackgroundMusicController.SfxKey}){if(ints.TryGetValue(k,out int v))PlayerPrefs.SetInt(k,v);else PlayerPrefs.DeleteKey(k);}if(hadVolume)PlayerPrefs.SetFloat(BackgroundMusicController.VolumeKey,oldVolume);else PlayerPrefs.DeleteKey(BackgroundMusicController.VolumeKey);PlayerPrefs.Save();File.WriteAllText("Validation/sprint1022_audio_tests.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT1022_PASS":reason));if(pass)Debug.Log("SPRINT1022_PASS");else Debug.LogError(reason);EditorApplication.Exit(pass?0:1);}
}
