using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using CosmicBlock.Core;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint101VisualProbe {
 static Dictionary<string,int> saved=new Dictionary<string,int>();static List<string> keys=new List<string>(),results=new List<string>();static int frames;static double start;static GameSession session;static GameFlowController flow;
 public static void Run(){keys.Add(PlanetSelection.Key);keys.Add(PlanetRestoration.VersionKey);keys.Add(GameSession.DefaultBestScoreKey);foreach(var d in PlanetDefinitions.All){keys.Add(d.EnergyKey);keys.Add(d.UnlockKey);}foreach(var k in keys){if(PlayerPrefs.HasKey(k))saved[k]=PlayerPrefs.GetInt(k);PlayerPrefs.DeleteKey(k);}PlayerPrefs.SetInt(PlanetRestoration.VersionKey,2);PlayerPrefs.SetInt(PlanetRestoration.DefaultKey,1500);PlayerPrefs.SetInt(PlanetRestoration.Planet02UnlockKey,1);PlayerPrefs.SetInt(GameSession.DefaultBestScoreKey,15930);EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");start=EditorApplication.timeSinceStartup;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Check(){if(EditorApplication.timeSinceStartup-start>240){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<35)return;EditorApplication.update-=Check;try{
 RunSaveStore.PathOverride=Path.GetFullPath("Validation/sprint101-visual-run.json");RunSaveStore.Delete();session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();
 foreach(int height in new[]{1920,2400,1440}){
 foreach(var d in PlanetDefinitions.All){PlayerPrefs.SetInt(d.UnlockKey,1);PlayerPrefs.SetInt(d.EnergyKey,0);PlayerPrefs.SetInt(PlanetCompletionNotice.Key(d.Id),2);}PlayerPrefs.Save();
 foreach(var d in PlanetDefinitions.All){PlanetSelection.Select(d.Id);flow.StartNewRun();foreach(int percent in new[]{0,25,50,75,99,100}){session.DebugSetPlanetEnergy(d.Total*percent/100);Capture(height,"game"+d.Id+"_percent"+percent,()=>UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>().RefreshVisual());var v=UnityEngine.Object.FindAnyObjectByType<PlanetRestorationView>();Req(Mathf.Abs(v.ProgressFill-percent/100f)<.0001f&&Mathf.Abs(v.ImageFillAmount-percent/100f)<.0001f,"actual fill "+percent);}}
 PlanetSelection.Select(1);flow.StartNewRun();var popup=UnityEngine.Object.FindAnyObjectByType<PlanetCompletionPopup>();popup.Show(session.Restoration.PlanetId);popup.PopupRoot.GetComponent<CanvasGroup>().alpha=1;popup.PopupRoot.transform.Find("Card").localScale=Vector3.one;Capture(height,"completion",()=>{});popup.Next();Capture(height,"confirmation",()=>{});popup.CloseTransient();
 }Finish(true,"");}catch(Exception e){Finish(false,e.ToString());}}
 static void Capture(int h,string tag,Action refresh){int w=1080;var canvas=GameObject.Find("GameCanvas").GetComponent<Canvas>();var safe=(RectTransform)canvas.transform.Find("SafeArea");var area=safe.GetComponent<SafeArea>();var cam=Camera.main;var oldMode=canvas.renderMode;var oldCamera=canvas.worldCamera;var oldTarget=cam.targetTexture;var oldActive=RenderTexture.active;var oldMin=safe.anchorMin;var oldMax=safe.anchorMax;bool oldEnabled=area.enabled;var rt=new RenderTexture(w,h,24);Texture2D tex=null;var backgrounds=new List<Tuple<AspectFillBackground,Vector2,Vector2,bool>>();try{area.enabled=false;rt.Create();cam.targetTexture=rt;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=10;safe.anchorMin=h==2400?new Vector2(.02f,.04f):Vector2.zero;safe.anchorMax=h==2400?new Vector2(.98f,.94f):Vector2.one;safe.offsetMin=safe.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();refresh();Canvas.ForceUpdateCanvases();if(flow.Screen==FlowScreen.Collection){var c=flow.CollectionView;var button=(RectTransform)c.transform.Find("SelectPlanet");Req(Inside(button,safe),"selection safe");var icon=(RectTransform)c.transform.Find("Hero/HeroLock");Req(icon.rect.width>0&&icon.rect.height>0,"lock rect valid");foreach(var text in c.GetComponentsInChildren<Text>())Req(text.cachedTextGenerator.characterCountVisible>=text.text.Replace("\n","").Length,"clipped "+tag+" "+h+" "+text.name);if(c.CanSelect){Req(Inside((RectTransform)c.transform.Find("Hero"),safe),"hero inside safe");var track=(RectTransform)c.transform.Find("ProgressFrameArea/ProgressFrame/Progress");var fill=(RectTransform)track.Find("Fill");Req(Mathf.Abs(fill.rect.width/track.rect.width-c.Progress)<.0001f,"actual rendered bar width");}Req(c.transform.Find("Previous/Icon").GetComponent<Image>().preserveAspect&&c.transform.Find("Next/Icon").GetComponent<Image>().preserveAspect,"navigation aspect");}
 if(flow.Screen==FlowScreen.Game){foreach(string path in new[]{"Board","PlanetRestoration","BlockArea","GameScorePresentation/CurrentScore"})Req(Inside((RectTransform)safe.Find(path),safe),"game safe "+path);var v=UnityEngine.Object.FindAnyObjectByType<PlanetRestorationView>();foreach(string field in new[]{"currentImage"}){var image=(Image)typeof(PlanetRestorationView).GetField(field,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(v);Req(image.preserveAspect&&image.sprite!=null,"HUD aspect");}}
 foreach(var bg in canvas.GetComponentsInChildren<AspectFillBackground>(true)){var r=(RectTransform)bg.transform;backgrounds.Add(Tuple.Create(bg,r.sizeDelta,r.anchoredPosition,bg.enabled));bg.enabled=false;var reference=new SerializedObject(bg).FindProperty("referenceSize").vector2Value;var full=(RectTransform)canvas.transform;r.sizeDelta=reference*Mathf.Max(full.rect.width/reference.x,full.rect.height/reference.y);r.anchoredPosition=((RectTransform)r.parent).InverseTransformPoint(full.TransformPoint(full.rect.center));}Canvas.ForceUpdateCanvases();
 foreach(var popup in canvas.GetComponentsInChildren<PlanetCompletionPopup>()){if(popup.Visible){foreach(var text in popup.PopupRoot.GetComponentsInChildren<Text>())Req(text.cachedTextGenerator.characterCountVisible>=text.text.Replace("\n","").Length,"popup clipped "+text.name+" "+h);if(popup.ConfirmationVisible)foreach(var text in popup.ConfirmationRoot.GetComponentsInChildren<Text>())Req(text.cachedTextGenerator.characterCountVisible>=text.text.Replace("\n","").Length,"confirmation clipped "+text.name+" "+h);}}
 cam.Render();RenderTexture.active=rt;tex=new Texture2D(w,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,w,h),0,0);tex.Apply();var view=UnityEngine.Object.FindAnyObjectByType<PlanetRestorationView>();var gaugeFill=(Image)typeof(PlanetRestorationView).GetField("progressFill",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(view);var gaugeTrack=(RectTransform)gaugeFill.transform.parent;var corners=new Vector3[4];gaugeTrack.GetWorldCorners(corners);var a=cam.WorldToScreenPoint(corners[0]);var b=cam.WorldToScreenPoint(corners[2]);File.AppendAllText("Validation/sprint101_gauge_rects.csv",tag+","+h+","+a.x+","+(h-b.y)+","+b.x+","+(h-a.y)+","+view.ImageFillAmount+"\n");
 File.WriteAllBytes("Validation/sprint101_"+tag+"_"+h+".png",tex.EncodeToPNG());results.Add("PASS "+tag+" "+h);
 }finally{foreach(var bg in backgrounds){var r=(RectTransform)bg.Item1.transform;r.sizeDelta=bg.Item2;r.anchoredPosition=bg.Item3;bg.Item1.enabled=bg.Item4;}canvas.renderMode=oldMode;canvas.worldCamera=oldCamera;cam.targetTexture=oldTarget;RenderTexture.active=oldActive;safe.anchorMin=oldMin;safe.anchorMax=oldMax;area.enabled=oldEnabled;if(tex!=null)UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);}}
 static bool Inside(RectTransform child,RectTransform parent){var c=new Vector3[4];child.GetWorldCorners(c);foreach(var p in c)if(!parent.rect.Contains(parent.InverseTransformPoint(p)))return false;return true;}
 static void Req(bool b,string m){if(!b)throw new Exception(m);}
 static void Finish(bool pass,string failure){EditorApplication.update-=Check;if(session!=null)session.LeaveForHome();RunSaveStore.Delete();foreach(var k in keys){if(saved.TryGetValue(k,out int v))PlayerPrefs.SetInt(k,v);else PlayerPrefs.DeleteKey(k);}PlayerPrefs.Save();File.WriteAllText("Validation/sprint101_visual_tests.txt",string.Join("\n",results)+"\n"+(pass?"SPRINT101_VISUAL_PASS":failure));if(pass)Debug.Log("SPRINT101_VISUAL_PASS");else Debug.LogError(failure);EditorApplication.Exit(pass?0:1);}
}
