using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using CosmicBlock.Core;
using CosmicBlock.UI;
using CosmicBlock.Board;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint93PlayProbe {
 static readonly string[] keys={PlanetRestoration.DefaultKey,PlanetRestoration.VersionKey,PlanetRestoration.Planet02Key,PlanetRestoration.Planet02UnlockKey,GameSession.DefaultBestScoreKey};
 static int[] saved=new int[keys.Length];static bool[] had=new bool[keys.Length];static int frames,assertions;static double started;static string errors="";static List<string> results=new List<string>();
 static GameSession session;static GameFlowController flow;static PlanetRestorationView view;
 public static void Run(){for(int i=0;i<keys.Length;i++){had[i]=PlayerPrefs.HasKey(keys[i]);saved[i]=PlayerPrefs.GetInt(keys[i]);}PlayerPrefs.SetInt(keys[0],0);PlayerPrefs.SetInt(keys[1],2);PlayerPrefs.DeleteKey(keys[3]);PlayerPrefs.SetInt(keys[4],15930);Domain();EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");started=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Check;EditorApplication.EnterPlaymode();}
 static void Domain(){string[] names={"황폐","싹틈","깨어남","회복","완성"};for(int i=0;i<5;i++)Req(PlanetRestoration.NameForStage(i+1)==names[i],"stage name");Req(PlanetRestoration.StageForEnergy(630)==3&&PlanetRestoration.StageEnergyForTotal(630)==230&&PlanetRestoration.RequiredForStage(3)==350&&PlanetRestoration.PercentForTotal(630)==42,"630 example");int[] totals={0,149,150,399,400,749,750,1199,1200,1499,1500};int[] stages={1,1,2,2,3,3,4,4,5,5,5};int[] current={0,149,0,249,0,349,0,449,0,299,300};int[] required={150,150,250,250,350,350,450,450,300,300,300};for(int i=0;i<totals.Length;i++){Req(PlanetRestoration.StageForEnergy(totals[i])==stages[i],"stage "+totals[i]);Req(PlanetRestoration.StageEnergyForTotal(totals[i])==current[i],"current "+totals[i]);Req(PlanetRestoration.RequiredForStage(stages[i])==required[i],"required "+totals[i]);Req(Mathf.Abs(PlanetRestoration.OverallProgressForTotal(totals[i])-totals[i]/1500f)<.000001f,"fill "+totals[i]);Req(PlanetRestoration.PercentForTotal(totals[i])==(int)Math.Floor(totals[i]*100.0/1500),"percent "+totals[i]);results.Add("BOUNDARY "+totals[i]+" stage="+stages[i]+" current="+current[i]+" required="+required[i]+" percent="+PlanetRestoration.PercentForTotal(totals[i]));}
  string k="Sprint93.TestEnergy",v=k+"Version";PlayerPrefs.SetInt(k,365);PlayerPrefs.SetInt(v,2);var m=new PlanetRestoration(k,v);Req(m.CurrentEnergy==365,"existing raw value retained");m.SetEnergy(1200);Req(m.Stage==5&&!m.IsRestored,"stage5 not complete");m.SetEnergy(1800);Req(m.IsRestored&&m.CurrentEnergy==1500,"clamp complete");PlayerPrefs.SetInt(k,1800);PlayerPrefs.DeleteKey(v);Req(new PlanetRestoration(k,v).CurrentEnergy==1500,"over-max value clamps even without version");PlayerPrefs.DeleteKey(k);PlayerPrefs.DeleteKey(v);var p2=new PlanetRestoration(PlanetRestoration.Planet02Key,PlanetRestoration.VersionKey,2);p2.SetEnergy(320);Req(p2.Stage==2&&p2.StageEnergy==120&&p2.StageRequired==300&&p2.OverallProgress==.16f,"planet2 independent 2000 target");int sum=0;for(int i=1;i<=5;i++)sum+=PlanetRestoration.RequiredForStage(i,2);Req(sum==2000,"planet2 amounts");int[] p2Amounts={200,300,450,600,450},p2Starts={0,200,500,950,1550};for(int i=0;i<5;i++){Req(PlanetRestoration.RequiredForStage(i+1,2)==p2Amounts[i],"planet2 requirement "+i);Req(PlanetRestoration.StartForStage(i+1,2)==p2Starts[i]&&PlanetRestoration.StageForEnergy(p2Starts[i],2)==i+1,"planet2 boundary "+i);}Req(PlayerPrefs.GetInt(keys[0])==0&&PlayerPrefs.GetInt(keys[4])==15930,"planet2 isolates global best and planet1");}
 static void Check(){if(EditorApplication.timeSinceStartup-started>360){Finish(false,"timeout");return;}if(!EditorApplication.isPlaying||++frames<30)return;EditorApplication.update-=Check;session=UnityEngine.Object.FindAnyObjectByType<GameSession>();flow=UnityEngine.Object.FindAnyObjectByType<GameFlowController>();view=UnityEngine.Object.FindAnyObjectByType<PlanetRestorationView>(FindObjectsInactive.Include);session.StartCoroutine(Tests());}
 static IEnumerator Tests(){IEnumerator body=Body();while(true){object value;try{if(!body.MoveNext())break;value=body.Current;}catch(Exception e){Finish(false,e.ToString());yield break;}yield return value;}Finish(true,"");}
 static IEnumerator Body(){flow.Play();var board=UnityEngine.Object.FindAnyObjectByType<BoardView>();foreach(var f in new[]{"session","board","feedback"})typeof(Sprint92PlayProbe).GetField(f,BindingFlags.Static|BindingFlags.NonPublic).SetValue(null,f=="session"?(object)session:f=="board"?board:session.Feedback);
  foreach(int total in new[]{0,149,150,399,400,749,750,1199,1200,1499,1500}){session.DebugSetPlanetEnergy(total);Req(view.ShownStage==session.Restoration.Stage&&view.PresentedEnergy==total,"view stage "+total);Req(Near(view.ProgressFill,total/1500f)&&Near(view.ImageFillAmount,total/1500f),"actual bar "+total);Req(view.transform.Find("Stage").GetComponent<Text>().text.Contains(session.Restoration.StageName),"stage name "+total);Req(view.transform.Find("Energy").GetComponent<Text>().text=="별빛 "+session.Restoration.StageEnergy+" / "+session.Restoration.StageRequired,"stage amount text");}
  PlayerPrefs.DeleteKey(keys[3]);session.DebugSetPlanetEnergy(1200);Req(!session.Restoration.IsRestored&&!session.Restoration.IsPlanet02Unlocked,"stage5 entry does not complete or unlock");session.DebugSetPlanetEnergy(1499);Req(!session.Restoration.IsRestored&&!session.Restoration.IsPlanet02Unlocked,"1499 remains incomplete and locked");
  foreach(int before in new[]{140,390,740,1190,1490}){session.DebugSetPlanetEnergy(before);session.DebugPrepareNextRow();int count=view.CompletionPlayCount;Req(session.TryPlacePiece(session.Slots[0],3,3),"boundary placement");Req(session.Restoration.CurrentEnergy==before+10&&PlayerPrefs.GetInt(keys[0])==before+10,"durable save immediate");Req(view.PresentedEnergy==before,"visual delayed");yield return new WaitForSecondsRealtime(.8f);Req(view.ActiveFragmentCount>=6&&view.PresentedEnergy==before,"visible flight before arrival");yield return new WaitForSecondsRealtime(4.5f);Req(session.State==GameState.Playing&&view.PresentedEnergy==before+10&&!view.FeedbackActive,"run continues after boundary");Req(view.CompletionPlayCount==count+1,"transition once");Req(session.Score>0,"score run preserved");}
  Req(session.Restoration.IsPlanet02Unlocked,"planet2 unlock");Req(new PlanetRestoration().IsRestored&&PlayerPrefs.GetInt(keys[3])==1,"completion and unlock persisted on reload");var planet2=new PlanetRestoration(keys[2],keys[1],2);planet2.AddEnergy(10);Req(planet2.CurrentEnergy==330&&session.Restoration.CurrentEnergy==1500&&PlayerPrefs.GetInt(keys[0])==1500&&session.BestScore==15930,"planet2 progress preserves completed planet1/global best");session.Retry();Req(session.Restoration.IsRestored&&session.BestScore==15930&&session.Score==0,"retry retains complete/global best");flow.ShowHome();flow.ShowCollection();flow.CollectionView.Next();Req(flow.CollectionView.Status=="발견 완료 · 탐험 준비 중"&&flow.CollectionView.Message==PlanetCollectionData.DiscoveredMessage&&!flow.CollectionView.transform.Find("HeroLock").gameObject.activeSelf,"collection unlocked without temporary art");flow.CollectionView.GoBack();flow.Play();Req(session.Restoration.IsRestored&&session.HasPlaceableRemainingBlock(),"home play after complete");
  session.DebugSetPlanetEnergy(140);session.DebugPrepareCross();Req(session.TryPlacePiece(session.Slots[0],3,3)&&session.Restoration.CurrentEnergy==165,"overflow25 immediate");yield return new WaitForSecondsRealtime(5.5f);Req(view.ShownStage==2&&view.PresentedEnergy==165&&Near(view.ProgressFill,.11f),"overflow15 with overall11%");session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"clear before cancel");flow.ShowHome();flow.Play();Req(session.Score==0&&session.Restoration.CurrentEnergy==175&&!view.FeedbackActive&&session.State==GameState.Playing,"cancel settled once clean play");yield return new WaitForSecondsRealtime(2);Req(session.Score==0&&view.PresentedEnergy==175,"no stale callback");
  session.Retry();session.DebugSetScore(15800);session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"best lower run");session.DebugCompleteTurnForProbe();Req(session.BestScore==15930,"lower run preserves best");session.Retry();session.DebugSetScore(15925);session.DebugPrepareNextRow();Req(session.TryPlacePiece(session.Slots[0],3,3),"best higher run");session.DebugCompleteTurnForProbe();Req(session.BestScore==16035&&PlayerPrefs.GetInt(keys[4])==16035,"global best improves");session.Retry();Req(session.BestScore==16035&&session.Score==0,"retry resets score retains best");
  var visual=UnityEngine.Object.FindAnyObjectByType<GameVisualPresentation>();foreach(var size in new[]{new[]{1080,1920},new[]{1080,2400},new[]{1080,1440}}){foreach(int best in new[]{9999,15930,99999,999999,1000000,int.MaxValue}){Sprint92PlayProbe.CaptureBestOverride=best;Sprint92PlayProbe.CaptureScoreOverride=1280;typeof(Sprint92PlayProbe).GetMethod("Capture",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{"93_"+size[1]+"_"+best,size[0],size[1]});Sprint92PlayProbe.CaptureBestOverride=-1;visual.RenderValues(1280,best);visual.BestText.ForceMeshUpdate();Req(!visual.BestText.isTextOverflowing,"best overflow "+size[1]+" "+best);Req(visual.BestText.fontSize<visual.ScoreText.fontSizeMax,"current score hierarchy");}}
  Req(errors.Length==0,"runtime errors "+errors);results.Add("PASS immediate durable save, arrival delay, five boundaries/completion once, overflow, unlock, retry/Home, responsive/Best overflow.");}
 static bool Near(float a,float b)=>Mathf.Abs(a-b)<.0001f;
 static void Req(bool b,string m){assertions++;if(!b)throw new Exception("Sprint93 "+m);}
 static void Log(string m,string s,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors+=m+"\n";}
 static void Finish(bool pass,string fail){EditorApplication.update-=Check;Application.logMessageReceived-=Log;for(int i=0;i<keys.Length;i++){if(had[i])PlayerPrefs.SetInt(keys[i],saved[i]);else PlayerPrefs.DeleteKey(keys[i]);}PlayerPrefs.Save();Directory.CreateDirectory("Validation");File.WriteAllText("Validation/sprint93_tests.txt",string.Join("\n",results)+"\nAssertions="+assertions+"\n"+(pass?"SPRINT93_PASS":fail));if(pass)Debug.Log("SPRINT93_PASS");else Debug.LogError(fail);EditorApplication.Exit(pass?0:1);}
}
