using System;
using System.IO;
using CosmicBlock.Core;
using CosmicBlock.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
public static class Sprint94Builder {
 
 public static void Build(){
  AssetDatabase.Refresh();var path="Assets/Resources/PlanetArtCatalog.asset";Directory.CreateDirectory("Assets/Resources");var art=AssetDatabase.LoadAssetAtPath<PlanetArtCatalog>(path);if(art==null){art=ScriptableObject.CreateInstance<PlanetArtCatalog>();AssetDatabase.CreateAsset(art,path);}var entries=new System.Collections.Generic.List<PlanetArtCatalog.Art>();
  foreach(var definition in PlanetDefinitions.All){if(!definition.ContentReady)continue;int id=definition.Id;var a=new PlanetArtCatalog.Art{planetId=id,stages=new Sprite[5],scales=id==2?new[]{1f,1.20f,1.16f,1.18f,1.25f}:new[]{1f,1f,1f,1f,1f}};a.bodyCenters=id==2?new[]{new Vector2(.5f,.5f),new Vector2(.5f,.549f),new Vector2(.501f,.537f),new Vector2(.509f,.545f),new Vector2(.517f,.543f)}:new[]{Vector2.one*.5f,Vector2.one*.5f,Vector2.one*.5f,Vector2.one*.5f,Vector2.one*.5f};for(int i=0;i<5;i++){string p=definition.StagePaths[i];a.stages[i]=Import(p);}entries.Add(a);}
  art.planets=entries.ToArray();art.homeBrand=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/UI/Home/home_planet_hero.png");if(art.homeBrand==null)throw new Exception("Missing existing HOME branding art");art.lockedPlanet=Import("Assets/Art/Planets/Common/planet_locked.png");art.smallLock=Import("Assets/Art/UI/Common/planet_lock_simple.png");EditorUtility.SetDirty(art);AssetDatabase.SaveAssets();
  var scene=EditorSceneManager.OpenScene("Assets/Scenes/Game.unity");var canvas=GameObject.Find("GameCanvas");var root=canvas.transform.Find("SafeArea/CollectionRoot");var view=root.GetComponent<PlanetCollectionView>();var hero=(RectTransform)root.Find("Hero");var lockImage=(root.Find("HeroLock")??hero.Find("HeroLock")).GetComponent<Image>();lockImage.sprite=art.smallLock;lockImage.type=Image.Type.Simple;lockImage.preserveAspect=true;lockImage.raycastTarget=false;var lr=lockImage.rectTransform;lr.SetParent(hero,false);lr.anchorMin=new Vector2(.375f,.375f);lr.anchorMax=new Vector2(.625f,.625f);lr.offsetMin=lr.offsetMax=Vector2.zero;
  foreach(var image in root.GetComponentsInChildren<Image>(true))if(image.name=="Lock")image.sprite=art.smallLock;
  var old=root.Find("SelectPlanet");if(old!=null)UnityEngine.Object.DestroyImmediate(old.gameObject);var go=new GameObject("SelectPlanet",typeof(RectTransform),typeof(Image),typeof(Button));go.transform.SetParent(root,false);var r=(RectTransform)go.transform;r.anchorMin=new Vector2(.29f,.008f);r.anchorMax=new Vector2(.71f,.055f);r.offsetMin=r.offsetMax=Vector2.zero;go.GetComponent<Image>().color=new Color(.025f,.12f,.25f,.96f);var text=new GameObject("Label",typeof(RectTransform),typeof(Text));text.transform.SetParent(go.transform,false);var tr=(RectTransform)text.transform;tr.anchorMin=Vector2.zero;tr.anchorMax=Vector2.one;tr.offsetMin=tr.offsetMax=Vector2.zero;var t=text.GetComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.fontSize=26;t.resizeTextForBestFit=true;t.resizeTextMinSize=18;t.resizeTextMaxSize=26;t.alignment=TextAnchor.MiddleCenter;t.color=new Color(1,.8f,.35f);t.raycastTarget=false;view.ConfigureSelection(go.GetComponent<Button>());
  var home=canvas.transform.Find("SafeArea/HomeRoot");var info=home.Find("HeroArea/SelectedPlanetInfo");if(info==null){var obj=new GameObject("SelectedPlanetInfo",typeof(RectTransform),typeof(Text));obj.transform.SetParent(home.Find("HeroArea"),false);info=obj.transform;}var ir=(RectTransform)info;ir.anchorMin=new Vector2(0,.10f);ir.anchorMax=new Vector2(1,.27f);ir.offsetMin=ir.offsetMax=Vector2.zero;var label=info.GetComponent<Text>();label.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");label.fontSize=label.resizeTextMaxSize=24;label.resizeTextMinSize=14;label.resizeTextForBestFit=true;label.fontStyle=FontStyle.Bold;label.alignment=TextAnchor.MiddleCenter;label.color=new Color(.65f,.92f,1);label.raycastTarget=false;info.gameObject.SetActive(false);var hs=new SerializedObject(home.GetComponent<HomeViewController>());hs.FindProperty("selectedPlanetInfo").objectReferenceValue=label;hs.ApplyModifiedPropertiesWithoutUndo();EditorUtility.SetDirty(home.GetComponent<HomeViewController>());EditorUtility.SetDirty(view);EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();Debug.Log("SPRINT94_SCENE_READY");if(Application.isBatchMode)EditorApplication.Exit(0);
 }
 static Sprite Import(string path){if(!File.Exists(path))throw new Exception("Missing planet asset "+path);var t=AssetImporter.GetAtPath(path)as TextureImporter;if(t==null)throw new Exception("No texture importer "+path);if(path.Contains("Planet01/"))return AssetDatabase.LoadAssetAtPath<Sprite>(path);t.textureType=TextureImporterType.Sprite;t.spriteImportMode=SpriteImportMode.Single;t.alphaSource=TextureImporterAlphaSource.FromInput;t.alphaIsTransparency=true;t.mipmapEnabled=false;t.filterMode=FilterMode.Bilinear;t.wrapMode=TextureWrapMode.Clamp;t.textureCompression=TextureImporterCompression.Uncompressed;t.maxTextureSize=2048;var android=t.GetPlatformTextureSettings("Android");android.overridden=true;android.maxTextureSize=2048;android.format=TextureImporterFormat.ASTC_6x6;android.compressionQuality=100;t.SetPlatformTextureSettings(android);t.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Sprite>(path);}
}
