using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public static class StarlightUiTheme
{
    public static readonly Color Gold=new Color(.98f,.76f,.32f,1),GoldSoft=new Color(.98f,.76f,.32f,.62f),White=new Color(.96f,.98f,1,1),Blue=new Color(.60f,.78f,1,1),Glass=new Color(.015f,.035f,.10f,.82f),GlassStrong=new Color(.012f,.028f,.085f,.96f),Secondary=new Color(.035f,.075f,.17f,.84f),Dim=new Color(.003f,.008f,.035f,.80f);
    const string RoundedPath="Assets/Art/UI/StarlightRoundedPanel.png";
    static Sprite Rounded=>AssetDatabase.LoadAssetAtPath<Sprite>(RoundedPath);
    public static void EnsureAssets(){if(!File.Exists(RoundedPath)){Directory.CreateDirectory("Assets/Art/UI");var texture=new Texture2D(32,32,TextureFormat.RGBA32,false);for(int y=0;y<32;y++)for(int x=0;x<32;x++){float dx=Mathf.Max(0,5-Mathf.Min(x,31-x)),dy=Mathf.Max(0,5-Mathf.Min(y,31-y));float alpha=dx*dx+dy*dy<=25?1:0;texture.SetPixel(x,y,new Color(1,1,1,alpha));}texture.Apply();File.WriteAllBytes(RoundedPath,texture.EncodeToPNG());Object.DestroyImmediate(texture);AssetDatabase.ImportAsset(RoundedPath,ImportAssetOptions.ForceSynchronousImport);}var importer=AssetImporter.GetAtPath(RoundedPath) as TextureImporter;importer.textureType=TextureImporterType.Sprite;importer.spriteImportMode=SpriteImportMode.Single;importer.alphaIsTransparency=true;importer.mipmapEnabled=false;importer.filterMode=FilterMode.Bilinear;importer.spriteBorder=new Vector4(7,7,7,7);importer.textureCompression=TextureImporterCompression.Uncompressed;importer.SaveAndReimport();}
    public static void Panel(Image image,Color color,bool border=true){var old=image.GetComponent<Outline>();if(old!=null)Object.DestroyImmediate(old);image.sprite=Rounded;image.type=Image.Type.Sliced;image.raycastTarget=image.GetComponent<Button>()!=null;if(!border){image.color=color;return;}image.color=GoldSoft;var child=image.transform.Find("ThemeFill") as RectTransform;if(child==null){child=new GameObject("ThemeFill",typeof(RectTransform),typeof(Image)).GetComponent<RectTransform>();child.SetParent(image.transform,false);}child.anchorMin=Vector2.zero;child.anchorMax=Vector2.one;child.offsetMin=new Vector2(2,2);child.offsetMax=new Vector2(-2,-2);child.SetAsFirstSibling();var fill=child.GetComponent<Image>();fill.sprite=Rounded;fill.type=Image.Type.Sliced;fill.color=new Color(color.r,color.g,color.b,1);fill.raycastTarget=false;}
    public static void Button(Button button,bool primary){var image=button.targetGraphic as Image;if(image==null)image=button.GetComponent<Image>();Panel(image,primary?GlassStrong:Secondary);image.color=primary?Gold:new Color(.43f,.64f,.94f,.70f);var colors=button.colors;colors.normalColor=Color.white;colors.highlightedColor=primary?new Color(1,1,.90f,1):new Color(.90f,.95f,1,1);colors.pressedColor=primary?new Color(1,.91f,.72f,1):new Color(.78f,.88f,1,1);colors.fadeDuration=.08f;button.colors=colors;var feedback=button.GetComponent<CosmicBlock.UI.ButtonPressFeedback>();if(feedback==null)button.gameObject.AddComponent<CosmicBlock.UI.ButtonPressFeedback>();}
    public static void Modal(RectTransform panel,RectTransform card){var dim=panel.GetComponent<Image>();if(dim!=null)dim.color=Dim;var image=card.GetComponent<Image>();if(image!=null)Panel(image,GlassStrong);}
    public static void Border(GameObject go,Color color,Vector2 distance){var outline=go.GetComponent<Outline>();if(outline==null)outline=go.AddComponent<Outline>();outline.effectColor=color;outline.effectDistance=distance;outline.useGraphicAlpha=false;}
    public static void Text(Text text,Color color,bool glow=false){text.color=color;if(glow){var shadow=text.GetComponent<Shadow>();if(shadow==null)shadow=text.gameObject.AddComponent<Shadow>();shadow.effectColor=new Color(1,.62f,.15f,.32f);shadow.effectDistance=new Vector2(2,-2);shadow.useGraphicAlpha=true;}}
}
